### ISSUE TITLE
Change the IntegrationTests client grant type to ClientCredentials

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#100]
Use the clientid/secret for authentication instead of password for non-interactive usage.
Change the [IntegrationTests ](https://github.com/jasontaylordev/CleanArchitecture/blob/bd88f17c6d3a5974f755888973dccdffc2118acc/src/Infrastructure/DependencyInjection.cs#L47)client grant type to ClientCredentials

Also remove the unnecessary [test user ](https://github.com/jasontaylordev/CleanArchitecture/blob/bd88f17c6d3a5974f755888973dccdffc2118acc/src/Infrastructure/DependencyInjection.cs#L51)

Then use the test client like the [example.](https://github.com/IdentityServer/IdentityServer4/blob/128464a8b372ba4a8534faf066e5268f1062b180/samples/Quickstarts/1_ClientCredentials/src/Client/Program.cs#L27)

**Comment by jasontaylordev** [comment]
Thanks for the suggestion, I've since decommissioned the old-style integration tests. So this no longer applies. See Application.IntegrationTests for the new approach.
