### ISSUE TITLE
How to map mutiple tables in ASP.net core 8.0

### ISSUE THREAD

**Issue by SheikPyari** [jasontaylordev/CleanArchitecture#1000]
Hi Jason,
I have created the API project using visual studio 2022 with asp.net core 8.0 

I want to get details of ASNHeader but want to map this table  vendor id with  Vendor Table Vendorid.  both the tables have VendorId column. how to do that.

getting error like
 Unable to create a map expression from ASNHEDR.Vendor (VCPAPI.Domain.Entities.Vendor) to IReadOnlyCollection`1.Vendor (System.Collections.Generic.IReadOnlyCollection`1[VCPAPI.Application.ASNHeader.Queries.GetASN.VendorDto])

Regards,
Sheik.

**Comment by SheikPyari** [comment]
can you help me on this.

**Comment by jasontaylordev** [comment]
This is not really specific to the template, perhaps try getting support on StackOverflow?
