### ISSUE TITLE
Unable to move to NativeAOT

### ISSUE THREAD

**Issue by olegtar83** [jasontaylordev/CleanArchitecture#1002]
After i add nativeAot properties to .csproj
```
 <PublishAot>true</PublishAot>
 <StripSymbols>false</StripSymbols>
```
I got the following error 

`Error	RDG002	Unable to statically resolve endpoint handler method. Only method groups, lambda expressions or readonly fields/variables are allowed. Compile-time endpoint generation will skip this endpoint and the endpoint will be generated at runtime. For more information, please see aka.ms/aot-known-issues	`

Do you have any other comptabile implementation for endpoints, that make this error go away?

**Comment by pbn4** [comment]
Same problem here, how did you solve?

**Comment by olegtar83** [comment]
No, i didn't find any example for this.
