### ISSUE TITLE
Blazor Server Template

### ISSUE THREAD

**Issue by Mehdi-Aghaei** [jasontaylordev/CleanArchitecture#1003]
I was listening to your latest talk in Copenhagen and realized that there is no template for Blazor,
I want to ask you to have a clean architecture with minimal API and a Blazor server template.

**Comment by neozhu** [comment]
This project is written using Blazor Server with the Clean Architecture. You can refer to it. https://github.com/neozhu/CleanArchitectureWithBlazorServer

**Comment by Mehdi-Aghaei** [comment]
> This project is written using Blazor Server with the Clean Architecture. You can refer to it. https://github.com/neozhu/CleanArchitectureWithBlazorServer
> 

Thanks for sharing 😊

**Comment by jasontaylordev** [comment]
> I was listening to your latest talk in Copenhagen and realized that there is no template for Blazor,
> 
> I want to ask you to have a clean architecture with minimal API and a Blazor server template.
> 
> 
> 
> 

Thanks for watching. Yes, I have this project too; https://github.com/jasontaylordev/RapidBlazor. It needs an upgrade, I'll get to that soon.
