### ISSUE TITLE
dotnet tools for ef migrations and stuff

### ISSUE THREAD

**Issue by cvalerio** [jasontaylordev/CleanArchitecture#1006]
**Is your feature request related to a problem? Please describe.**
When adding migrations it's a PITA to always have to add 2 projects refs and 1 directory ref.

**Describe the solution you'd like**
A set of dotnet tools (ca-add-migration, ca-db-update, ...) that install alongside the template would be useful.

**Describe alternatives you've considered**
At the moment I've created a PS module that does that stuff, but every dev must import the module manually, which is not ideal.

**Comment by jasontaylordev** [comment]
Please can you give some examples including your current workaround?
