### ISSUE TITLE
Can you add an example of an endpoint's FromForm request with IFormFile?

### ISSUE THREAD

**Issue by tzdevelopteam** [jasontaylordev/CleanArchitecture#1013]

**Comment by jasontaylordev** [comment]
You can just follow the examples within the Microsoft Learn Docs:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-7.0#file-uploads-using-iformfile-and-iformfilecollection

**Comment by tzdevelopteam** [comment]
Hey, thanks
But I don't understand how to pass the IFormFile command to CQRS, maybe you
can help me with that.
Hmm... maybe open the stream and send the content? But I lose the file name
and some other properties

Other suggestions please?

בתאריך יום ו׳, 13 באוק׳ 2023 ב-7:35 מאת Jason Taylor <
***@***.***>:

**Comment by stijnvddonk** [comment]
Did you manage to solve this? 
When i try to compile it failed giving me the following error:
 System.InvalidOperationException: command must have a valid TryParse method to support converting from a string. No public static bool UploadComponentBookCommand.TryParse(string, out UploadComponentBookCommand) method found for command.
 
 My method is:
     public async Task UploadComponentBook(ISender sender, [FromForm] UploadComponentBookCommand command)
    {
       await sender.Send(command);
    }
and the record is:
    public int StartPage { get; init; }
    public required IFormFile File { get; init; }

**Comment by tzdevelopteam** [comment]
Hey, no sorry

‫בתאריך יום ו׳, 10 בנוב׳ 2023 ב-14:36 מאת ‪stijnvddonk‬‏ <‪
***@***.***‬‏>:‬
