### ISSUE TITLE
serilog logging integration

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#102]
the .net core default logging is too dry.
[serilog logging integration](https://serilog.net/)

**Comment by jasontaylordev** [comment]
Great suggestion, Serilog is awesome and I use it with most real-world applications. However, this template is focused on the simplest approach, and for that Logging in .NET Core is great.

For those interested in learning more:

- [Logging in .NET Core and ASP.NET Core
](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1)
- [Setting up Serilog in ASP.NET Core 3
](https://nblumhardt.com/2019/10/serilog-in-aspnetcore-3/)

Happy Coding! 😃
