### ISSUE TITLE
when building the project in production mode due to the requirement of Duende License.

### ISSUE THREAD

**Issue by Jeongyong-park** [jasontaylordev/CleanArchitecture#1020]
**Is your feature request related to a problem? Please describe.**

 I consistently face an issue when building the project in production mode due to the requirement of a Duende license. This leads to additional cost implications.

**Describe the solution you'd like**

I'd like a solution that either removes or replaces the paid license library associated with Duende in this project. 

**Describe alternatives you've considered**

**Additional context**

<PackageReference Include="Microsoft.AspNetCore.ApiAuthorization.IdentityServer" Version="7.0.7" />

**Comment by jasontaylordev** [comment]
Duende IdentityServer is no longer used in this project.
