### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gelik111555** [jasontaylordev/CleanArchitecture#1023]
An error occurs when installing the template

1 - Instaled Visual Studio 2022 Preview vith dotnet 8

2 - dotnet new ca-sln --client-framework Angular --output YourProjectName
3 - dotnet build -tl

`
PS C:\Users\glebs\source\repos\react\YourProjectName> dotnet build -tl
Версия MSBuild 17.8.0+6cdef4241 для .NET
Восстановление завершено (1,2 с)
  Domain completed (0,4 с) → src\Domain\bin\Debug\net8.0\YourProjectName.Domain.dll
  Infrastructure.IntegrationTests успешно выполнено (0,5 с) → tests\Infrastructure.IntegrationTests\bin\Debug\net8.0\YourProjectName.Infrastructure.IntegrationTests.dll
  Web.AcceptanceTests completed  (0,6 с) → tests\Web.AcceptanceTests\bin\Debug\net8.0\YourProjectName.Web.AcceptanceTests.dll
  Application успешно выполнено (0,2 с) → src\Application\bin\Debug\net8.0\YourProjectName.Application.dll
  Domain.UnitTests completed  (0,2 с) → tests\Domain.UnitTests\bin\Debug\net8.0\YourProjectName.Domain.UnitTests.dll
  Infrastructure completed  (0,3 с) → src\Infrastructure\bin\Debug\net8.0\YourProjectName.Infrastructure.dll
  Application.UnitTests completed  (0,4 с) → tests\Application.UnitTests\bin\Debug\net8.0\YourProjectName.Application.UnitTests.dll
  Web erorr (3,1 с) → src\Web\bin\Debug\net8.0\YourProjectName.Web.dll
    C:\Users\glebs\source\repos\react\YourProjectName\src\Web\Web.csproj(60,5): warning MSB3073: выход из команды "dotnet "C:\Users\glebs\.nuget\packages\nswag.msbuild\13.19.0\buildTransitive\../tools/Net70/dotnet-nswag.dll" run config.nswag /variables:Configuration=Debug" с кодом -1.
    C:\Users\glebs\source\repos\react\YourProjectName\src\Web\Web.csproj(66,5): error : NSwag command line tool for .NET Core Net70, toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0));Visit http://NSwag.org for more information.;NSwag bin directory: C:\Users\glebs\.nuget\packages\nswag.msbuild\13.19.0\tools\Net70;Executing file 'config.nswag' with variables 'Configuration=Debug'...;Launcher directory: C:\Users\glebs\.nuget\packages\nswag.msbuild\13.19.0\tools\Net70;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.;---> System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Identity.UI.Services.IEmailSender' from assembly 'Microsoft.Extensions.Identity.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.;at Microsoft.AspNetCore.Identity.IdentityBuilderUIExtensions.AddDefaultUI(IdentityBuilder builder);at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionUIExtensions.AddDefaultIdentity[TUser](IServiceCollection services, Action`1 configureOptions);at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionUIExtensions.AddDefaultIdentity[TUser](IServiceCollection services);at Microsoft.Extensions.DependencyInjection.DependencyInjection.AddInfrastructureServices(IServiceCollection services, IConfiguration configuration) in C:\Users\glebs\source\repos\react\YourProjectName\src\Infrastructure\DependencyInjection.cs:line 35;at Program.<Main>$(String[] args) in C:\Users\glebs\source\repos\react\YourProjectName\src\Web\Program.cs:line 9;at Program.<Main>(String[] args);at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor);at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr);--- End of stack trace from previous location ---;at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost() in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 271;at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args) in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 75;at NSwag.Commands.ServiceProviderResolver.GetServiceProviderWithHostFactoryResolver(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 146;at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 70;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 27;at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor);at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr);--- End of inner exception stack trace ---;at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr);at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture);at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters);at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132;System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 231;at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275;at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81;at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85;at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32;at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input);at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input);at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61

`

**Comment by steveoshima** [comment]
See: https://github.com/jasontaylordev/CleanArchitecture/issues/1034

**Comment by jasontaylordev** [comment]
It should be resolved with the latest version of the template and .NET 8. Try again and shout out if you run into any issues.
