### ISSUE TITLE
After implementing jwt I always got HttpContext.User is null

### ISSUE THREAD

**Issue by salmanshafiq00** [jasontaylordev/CleanArchitecture#1031]
**Describe the bug**
I clone .net 7.0 project and implement jwt on this project. Also I used MS default Web API project instead SPA. After successful login and I tried to get data from another action which has authorize attribute. But unfortunately, I always found unauthorized even though it authorized request.

Here is my jwt provider class which in infrastructure layer.

public async Task<string> GenerateJwtAsync(string userId)
{
    var user = await _userManager.FindByIdAsync(userId);

    var userRoles = await _userManager.GetRolesAsync(user);

    var roleClaims = new List<Claim>();
    foreach (var role in userRoles)
    {
        var identityRole = await _roleManager.FindByNameAsync(role);
        roleClaims.AddRange(await _roleManager.GetClaimsAsync(identityRole));
    }

    var claims = new[]
    {
        new Claim(JwtRegisteredClaimNames.Sub, user.Id),
        new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
        new Claim(JwtRegisteredClaimNames.Email, user.Email),
        new Claim("username", user.UserName),
        new Claim("ip", GetIpAddress())
    }
    .Union(roleClaims);

    var signingCredentials = new SigningCredentials(
        new SymmetricSecurityKey(
            Encoding.UTF8.GetBytes(_jwtOptions.SecretKey)),
            SecurityAlgorithms.HmacSha256);

    var token = new JwtSecurityToken(
         _jwtOptions.Issuer,
         _jwtOptions.Audience,
         claims,
         null,
         DateTime.Now.AddMinutes(_jwtOptions.DurationInMinutes),
         signingCredentials
        );
    string tokenValue = new JwtSecurityTokenHandler().WriteToken(token);
    return await Task.FromResult(tokenValue);
}

Here, is the dependency register in DependencyInjection classs.

![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/7198d086-0fc3-4a06-800b-5054a933f383)

Unfortunately, I got null from HttpContext's User.

![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/5dffce65-048d-4553-a6ed-d458e8219ad0)

Here, is my CurrentUser service for getting the current user

![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/7ddfddaa-785a-4352-ba21-31bab73e0400)

I tried a lot can't find any solutions. I have nothing what should to do. pls help.

**Comment by ramax495** [comment]
Check values of claim constants.
When you create a token you use `JwtRegisteredClaimNames.Sub` constant with value `"sub"`.
And when you get claim in CurrentUser service you use `ClaimTypes.NameIdentifier` and its value is `"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier"`

**Comment by salmanshafiq00** [comment]
NameIdentifier  bind the Sub type value.

Also, more clearify, I added another Claim to jwt which is "uid" claim type.

Here, is my decoded token value in jwt
![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/1b0f1118-b802-4079-8e19-4e9b3da65eda)

Little bit change in CurrentUser class
![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/682d2d07-96d0-4722-8da2-5492a946fb8d)

still,  user of httpcontext shows null
![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/37a66c03-6a21-4891-8deb-fe1858c0aae4)

is there any possibility that when i request with Bearer token, the action can't verify bearer token?

but i get the bearer token in request header. 
![image](https://github.com/jasontaylordev/CleanArchitecture/assets/103124821/6c9f9d39-9b3f-4576-be0b-492142703b49)

**Comment by Chris-Mingay** [comment]
@salmanshafiq00 I've been wrestling with similar in an effort to implement a more 'vanilla' JWT and I believe it's because the system isn't recognising your DefaultAuthenticationScheme and because of it, is not calling the [Authorize] attribute in the way you'd expect.

I believe you can decorate controllers with:

```cs
[Authorize(AuthenticationSchemes = "Bearer")]
```

however I've done my JWT set up in a slightly different way which achieves the same.

```cs
services
        .AddAuthentication(options =>
        {
            options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultSignInScheme = JwtBearerDefaults.AuthenticationScheme;
            options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
        })
        .AddJwtBearer(options =>
        {
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateAudience = false,
                ValidAudience = Constants.Domain,
                ValidateIssuer = false,
                ValidIssuer = Constants.Domain,
                ValidateLifetime = false,
                ValidateIssuerSigningKey = false,
                IssuerSigningKey = new SymmetricSecurityKey(System.Text.Encoding.UTF8.GetBytes(Constants.JwtKey)),
            };
        });
```

Take with a pinch of salt though and I'm by no means stating this is the way to go!

**Comment by salmanshafiq00** [comment]
@iamcymentho @Chris-Mingay ,
For your concern I push my repo in GitHub and here is the link https://github.com/salmanshafiq00/LMS
