### ISSUE TITLE
DI on Endpoints

### ISSUE THREAD

**Issue by nestenius** [jasontaylordev/CleanArchitecture#1047]
How do I make Endpoints work with DI as in following code:

```
public class Accounts : EndpointGroupBase
{
    private readonly ITokenService _identityService;

    public Accounts(
        ITokenService identityService)
    {
        _identityService = identityService;
    }

    public override void Map(WebApplication app)
    {
        app.MapGroup(this)
            .MapPost(Login);
    }

    public async Task Login(ISender sender, TokenRequest model)
    {
        var response = await _identityService.LoginAsync(model);
        return await sender.Send(command);
    }
}
```

**Comment by jasontaylordev** [comment]
As far as I am aware, this is not supported. The idea is that each endpoint can define its own dependencies. If you want to dig deeper, the main concepts used in this template include:

* [Route groups](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0#route-groups)
* [DI parameter binding](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0#parameter-binding)
* [Endpoint defined outside of Program.cs](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0#endpoint-defined-outside-of-programcs)

I'd recommend you just inject identity service wherever it is required.
