### ISSUE TITLE
NSwagStudio

### ISSUE THREAD

**Issue by steveoshima** [jasontaylordev/CleanArchitecture#1048]
**NSwagStudio 13.20.0.0 Not compatible**
Using latest version of the template Template::8.0.0-preview.7.2 and using the fix for the build from https://github.com/jasontaylordev/CleanArchitecture/issues/1034
All builds fine. But how do we use NSwagStudio to generate web-api-client.ts?

**To Reproduce**
1. NSwagStudio '...'
2. Click on Runtime Net70
3. Then go to .Net Assembly tab
4. Enter the location of your built solutions Web dll
5. Load Assembly

**Expected behavior**
Be able to see the classes to get the client outputs.

**Additional context**
Maybe NSwagStudio wasnt used to create the web-api-client.ts in the ClientApp/Src folder?

Can you point to how web-api-client.ts was created.
Thanks.

**Comment by jasontaylordev** [comment]
You should be able to do it now. However, you'll need to get the latest version of the template first and also the preview version of NSwag; https://github.com/RicoSuter/NSwag/releases.

The template is currently running the preview version to support .NET 8.
