### ISSUE TITLE
Readme does not link to https://github.com/jasontaylordev/CleanArchitecture

### ISSUE THREAD

**Issue by eisbaer66** [jasontaylordev/CleanArchitecture#1050]
**Describe the bug**
The template generates a Readme.md.
But instead of linking to https://github.com/jasontaylordev/CleanArchitecture it will replace the "CleanArchitecture" with the name of the project.

**To Reproduce**
```
mkdir readme-test
cd readme-test
dotnet new ca-sln --client-framework None -us
cat .\README.md
```

**Expected behavior**
I'd expect the first line to read
`The project was generated using the [Clean.Architecture.Solution.Template](https://github.com/jasontaylordev/CleanArchitecture) version 8.0.0.`
instead it reads
`The project was generated using the [Clean.Architecture.Solution.Template](https://github.com/jasontaylordev/readme_test) version 8.0.0.` 

At the bottom of the readme is a similar link, that is wrong too: `To learn more about the template go to the [project website](https://github.com/JasonTaylorDev/readme_test).`

**Additional context**
```
> dotnet --version
8.0.100
```
```
> dotnet new uninstall
Currently installed items:
   Clean.Architecture.Solution.Template
      Version: 8.0.0
      Details:
         Author: JasonTaylorDev
         Owners: JasonTaylorDev
         Reserved: ?
         NuGetSource: https://api.nuget.org/v3/index.json
      Templates:
         Clean Architecture Solution (ca-sln) C#
         Clean Architecture Solution Use Case (ca-usecase) C#
      Uninstall Command:
         dotnet new uninstall Clean.Architecture.Solution.Template
```

**Comment by jasontaylordev** [comment]
Thanks for reporting this issue!
