### ISSUE TITLE
Web project seems to miss a reference to Microsoft.EntetyFrameworkCore.Design/Tools in order to do EF migrations

### ISSUE THREAD

**Issue by HjalteParner** [jasontaylordev/CleanArchitecture#1055]

**Comment by jasontaylordev** [comment]
I did a quick test and it is working. Check the [Database](https://github.com/jasontaylordev/CleanArchitecture#database) section in the README. This was my test:

```bash
cd .\src\Infrastructure\
dotnet ef migrations add "NewMigration" --startup-project ..\Web\
```

I'll close this issue, but let me know if you encounter further troubles.
