### ISSUE TITLE
[Feature request] Angular interceptor

### ISSUE THREAD

**Issue by giovanellij** [jasontaylordev/CleanArchitecture#106]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. 

I'm always frustrated when I have to handle each error in the angular application.

**Describe the solution you'd like**
I would like to have an interceptor to handle all the errors and only worry about the ok response.

**Additional context**
I have tried to make this work but the catchError does not catch the response body.

**Comment by jasontaylordev** [comment]
This is a good idea. Take a look at this resource:

- [Expecting the Unexpected — Best practices for Error handling in Angular](https://medium.com/angular-in-depth/expecting-the-unexpected-best-practices-for-error-handling-in-angular-21c3662ef9e4)

It outlines a comprehensive approach. What do you think?

**Comment by jasontaylordev** [comment]
I think there's already a lot of good guidance on this topic, such as the article above. 

Closing.
