### ISSUE TITLE
can't start angular site?  

### ISSUE THREAD

**Issue by punkouter24** [jasontaylordev/CleanArchitecture#1069]
Any idea ? 

> ca.web@0.0.0 start:windows
> ng serve --port 44447 --ssl --ssl-cert "%APPDATA%\ASP.NET\https\%npm_package_name%.pem" --ssl-key "%APPDATA%\ASP.NET\https\%npm_package_name%.key"

Node.js version v21.2.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
Unknown error: Error: Cannot find module './analytics-parameters'
Require stack:
- C:\Users\punko\Downloads\Ca\src\Web\ClientApp\node_modules\@angular\cli\src\analytics\analytics-collector.js
- C:\Users\punko\Downloads\Ca\src\Web\ClientApp\node_modules\@angular\cli\src\command-builder\command-module.js
- C:\Users\punko\Downloads\Ca\src\Web\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\punko\Downloads\Ca\src\Web\ClientApp\node_modules\@angular\cli\lib\init.js
PS C:\Users\punko\Downloads\Ca\src\web\ClientApp>

**Comment by miguelzakharia** [comment]
Maybe caused by the same thing listed in issue #961 ?
