### ISSUE TITLE
[question] Authorization without OIDC

### ISSUE THREAD

**Issue by ramax495** [jasontaylordev/CleanArchitecture#107]
If my app consists only of client(SPA) and server side and it don't need using OAUTH at all, just simple token authentication. What is the best way to implement it ? 
Remove Identity Server and use ASP.NET Identity ?
Or there is any configuration of Identity Server that allows to simplify the auth process ?
First of all, I want to remove unnecessary redirects.

**Comment by sk0gen** [comment]
I also have same question. I followed CodeMaze tutorial and just have asp net core identity implementation. But what when I want to add Google auth to my app? I couldn't find any good resource

**Comment by ramax495** [comment]
@sk0gen The solution is to configure IdentityServer with ResourceOwnerPassword flow. Here is tutorial how to implement it in ASP.NET Core: https://codebrains.io/how-to-add-jwt-authentication-to-asp-net-core-api-with-identityserver-4-part-1/
