### ISSUE TITLE
Referring Entityframework in Application layer or use case layer

### ISSUE THREAD

**Issue by vinaykasireddy** [jasontaylordev/CleanArchitecture#1086]
I have noticed you have referred 
Microsoft.EntityFrameworkCore in Application layer project. Isn't this violating the principles.

Thought any sort of entityframework related nuget should only be referred in infrastructure layer.

**Comment by thaerzaghal** [comment]
#439

**Comment by jasontaylordev** [comment]
I've created an architecture decision record for this topic: https://github.com/jasontaylordev/CleanArchitecture/wiki/ADR-001-Use-EFCore-In-Application-Layer. Feel free to suggest any changes.
