### ISSUE TITLE
Spa Service Failure when running

### ISSUE THREAD

**Issue by danielmackay** [jasontaylordev/CleanArchitecture#109]
**Describe the bug**
when using 'dotnet run'  I get many errors in the output.  I can browse the website, but the 'todo' page does not work

**To Reproduce**
1. Create a new solution via the template
2. navigate to src\webui
3. run 'dotnet build'
4. run 'dotnet run'

**Expected behavior**
running the site should not produce errors, and I should be able to navigate to the 'todo' page.

**Additional context**
Terminal output attached
[ca-output.txt](https://github.com/jasontaylordev/CleanArchitecture/files/4521907/ca-output.txt)

**Comment by jasontaylordev** [comment]
Thanks for reporting this issue. One question, when you browse the website - what URL are you using?

**Comment by danielmackay** [comment]
Thanks for the prompt response!

URL I am hitting is: http://localhost:6090/

Also, I have noticed the readme.md and LICENCE are included in the solution, but don't exist on disk

![image](https://user-images.githubusercontent.com/2636640/80090930-a43f5980-85a3-11ea-8370-15268117183f.png)

**Comment by jasontaylordev** [comment]
Try https://localhost:5001

**Comment by jasontaylordev** [comment]
> Also, I have noticed the readme.md and LICENCE are included in the solution, but don't exist on disk

Thanks, I'll try to fix that.

**Comment by danielmackay** [comment]
Success!  Thanks Jason.

Any idea about those Spa services errors?

Watched your goto presso in Copenhagen recently, and am really psyched to get a good understanding of the entire architecture.  Once that's done, I'd like to try switching the FE to React.

Thanks for putting this together mate, it's excellent work.

**Comment by jasontaylordev** [comment]
That's great! Thanks for the feedback. You might like to check out the new Clean Testing video too - https://www.youtube.com/watch?v=2UJ7mAtFuio. I really love this testing approach.

I think what you are seeing is that ASP.NET Core SPA Services is constantly monitoring Angular CLI to see if the front end has been built and is being served. The Angular build process takes quite a lot of time so you keep seeing fail. However, eventually, you see:

```
info: Microsoft.AspNetCore.SpaServices[0]
      : Compiled successfully.
```
You can learn more about the approach here; https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio.

> I'd like to try switching the FE to React.

You might like to check out the ASP.NET Core React template too - https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react?view=aspnetcore-3.1&tabs=visual-studio.

Happy Coding! 😃
