### ISSUE TITLE
newly created solution is missing "Solution Items" LICENSE and README.md

### ISSUE THREAD

**Issue by NickFranceschina** [jasontaylordev/CleanArchitecture#111]
**Describe the bug**

I just created a new solution from the template and inside the `Solution Items` folder there are two files pointing to `LICENCE` and `README.md` but they are not on the drive.

**To Reproduce**
`dotnet new ca-sln`

**Screenshots**
![Screen Shot 2020-04-24 at 4 44 29 AM](https://user-images.githubusercontent.com/419831/80152777-79c2c000-85e6-11ea-96a1-2ccdc6d2b1f3.png)

**Comment by jasontaylordev** [comment]
Hi @NickFranceschina. Thanks for raising, I'll try to get this fixed tonight.

**Comment by jasontaylordev** [comment]
Adding @danielmackay, so you'll know when it's resolved.

**Comment by jasontaylordev** [comment]
Thanks, this is fixed. Please run:

```
dotnet new --install Clean.Architecture.Solution.Template::1.1.1
```
