### ISSUE TITLE
Add Web.GrpcServer [gRPC Server]

### ISSUE THREAD

**Issue by GhorbaniAli** [jasontaylordev/CleanArchitecture#1111]
Hey 👋 , Thanks a lot for this architecture example.
The current architecture for the WebApi is very good and I think it can be improved for the gRPC server (Web.GrpcServer) as well. I want to start this as well.

**Comment by jasontaylordev** [comment]
Hi @GhorbaniAli. You're welcome. Thanks for the suggestion. gRPC is not something I'm looking to include in this template. The template goal is the most straightforward approach to enterprise application development with Clean Architecture and ASP.NET Core, so I've chosen minimal API.
