### ISSUE TITLE
Invalid Operation Exception on dotnet run when following initial get started

### ISSUE THREAD

**Issue by dobla-jgauthier** [jasontaylordev/CleanArchitecture#112]
**Describe the bug**
Following the README to get the code up and running. When I perform dotnet run in the WebUI folder I am receiving an error about an invalid certificate with IdentityServer

**To Reproduce**
(Follow steps listed in ReadMe)
1. Download lastest .NET Core SDK
2. Download Latest NodeJS LTS
3. Install Clean Architecture Template
4. Create a new project using dotnet new ca-sln
5. Navigate to src\WebUI and execute dotnet run

**Expected behavior**
As stated in the README, I expected the for the project to startup successfully, open the browser and go to the start page. 

**Screenshots**
![image](https://user-images.githubusercontent.com/24664858/80268680-69a6f100-8677-11ea-95ef-a9de22dbcb70.png)

**Additional context**
Running Windows 10 1909 64-bit. 
Have latest .NET Core SDK (3.1.201) and latest NodeJS LTS 12.16.2

**Comment by jasontaylordev** [comment]
Please check, are you running in Debug or Release mode? I think Release. The error you have encountered indicates that it is trying to access Production configuration.

Also worth checking the ASP.NET Core Environment. When the application launches you should see:
Hosting environment: Development

Learn more here, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1.

Let me know if this helped.

**Comment by dobla-jgauthier** [comment]
Jason, 

This did help. I noticed that there was an enviroment variable for DOTNET_ENVIRONMENT but not one for ASPNETCORE_ENVIRONMENT. After adding this latter one, it ran fine. I don't know if the DOTNET_ENVIRONMENT variable is from me or from the project, but I don't think it had an effect.

![image](https://user-images.githubusercontent.com/24664858/80715202-075d4e80-8ac4-11ea-80c2-f549ce35fd61.png)

Thanks for your help!
