### ISSUE TITLE
Question: This template vs Ardalis one

### ISSUE THREAD

**Issue by sturlath** [jasontaylordev/CleanArchitecture#113]
Ok this might be totally unfair question to ask but I'm just starting out using this kind of architecture in practice (have been reading about them for years) so I´m trying to pick the right starting point.

I have watched few of @jasontaylordev presentations on Northwind and few of Ardalis videos also and  I'm wondering about the difference between this one and [Steves](https://github.com/dotnet-architecture/eShopOnWeb) clean architecture approach?

Any pointers for me? Is it just slightly different styles or something more fundamental?

**No stress** as I´m going through both ones and making up my own mind but I would really like to choose the "best" starting point. 

And if nobody has any idea just close this question :-)

**Comment by MCCshreyas** [comment]
See choosing architecture style is solely depend upon the problem statement. However following  an architecture style, will ensures that one following best practices while developing. 

I will suggest you to build something small with both of the architecture, then you will learn more about both of them, and will be able to choose your favorite one in which you enjoyed yourself developing.

**Comment by sturlath** [comment]
Yes I think I will just do that. Right off the bat there is something I like I see here but only time will tell :-) Thanks for quick answer. I'll close this now.
