### ISSUE TITLE
Angular 17, standalone

### ISSUE THREAD

**Issue by jaresus** [jasontaylordev/CleanArchitecture#1133]
Hi,
This template is great! It would be even better if it was Angular 17 with standalone components.

**Comment by jasontaylordev** [comment]
Do you mean separate projects for the API server and the Angular client?

**Comment by jasontaylordev** [comment]
I'll assume you mean separate projects for client and server. This is not something I'm looking to demonstrate in this solution. I find the convenience of developing, building, and deploying the client and server as a single unit to be productive and straightforward. 

If you want to implement the separate approach and would like some guidance, you can see an example using the new ASP.NET Core 8  templates; https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022.

Happy coding! 🙂
