### ISSUE TITLE
[Feature Request] .Net client

### ISSUE THREAD

**Issue by KuraiAndras** [jasontaylordev/CleanArchitecture#114]
Where would a .net based client(Blazor/WPF/Xamarin/Avalonia/etc..) be placed in this?
How much logic should be shared? (Validation? HttpClient?)
Would it be possible for the application layer be re used by the client also? (Think downloading a part of the database, and then store it for offline use with SQLite/EfInMemory)

**Comment by charleshaye** [comment]
send me this stuff that your having promplams with

**Comment by MCCshreyas** [comment]
The presentation layer it the place where you can put anything to which user can interact to the system, like ASP.NET Core MVC, SPA, or even blazor.

**Comment by jasontaylordev** [comment]
Here is a Blazor example; https://github.com/jasontaylordev/CleanArchitecture/tree/blazor

**Comment by jasontaylordev** [comment]
Hope that helped, closing issue.
