### ISSUE TITLE
Question: GraphQL

### ISSUE THREAD

**Issue by Hulkstance** [jasontaylordev/CleanArchitecture#116]
Since GraphQL becomes more famous and it will possibly replace REST in the future, I thought that it would be a good idea to create a template for it. Others might like it as well. 

I don't know what's your opinion. I look forward hearing from you.

**Comment by jasontaylordev** [comment]
Hi @Hulkstance. A good suggestion, but it's not a technology I'm looking to incorporate into this template right now. Thanks any and happy coding.
