### ISSUE TITLE
upgrade angular spa client to 17

### ISSUE THREAD

**Issue by underwater** [jasontaylordev/CleanArchitecture#1162]
Currently the generated angular spa client code is using angular 15 
Any plan to upgrade to angular 17

**Comment by ManuelNinyo** [comment]
I am interested in working on this.

**Comment by juliengloria** [comment]
Angular 18 ^_^

**Comment by Samandar02** [comment]
> Angular 18 ^_^
I'll try to upgrade

**Comment by jasontaylordev** [comment]
Thanks, it's done, appreciate the help @Samandar02

**Comment by Arggon** [comment]
Hi @jasontaylordev Maybe I'm missing something but I'm not seeing the standalone components in the main branch.

**Comment by jasontaylordev** [comment]
I need more detail. Can you explain what you mean by standalone components?

**Comment by ManuelNinyo** [comment]
> Hi [@jasontaylordev](https://github.com/jasontaylordev) Maybe I'm missing something but I'm not seeing the standalone components in the main branch.

you could use `ng generate @angular/core:standalone` for migrate to standalone components
