### ISSUE TITLE
Azure.Identity 1.10.4 moderate severity vulnerability

### ISSUE THREAD

**Issue by Wosiu6** [jasontaylordev/CleanArchitecture#1171]
**Describtion**
When installing the new version an Azure.Identity 1.10.4 moderate severity vulnerability is preventing you from running it. When trying to update that library to the latest, the application throws an NSwag error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. dotnet new install Clean.Architecture.Solution.Template::8.0.5
2. dotnet new ca-sln --client-framework Angular --output test (or React one)
3. cd test/src/Web -> dotnet run
4. see error

if you disable warnings as errors you get another error, see attached
[log.txt](https://github.com/jasontaylordev/CleanArchitecture/files/15082154/log.txt)

-- Alternatively --
1. dotnet new install Clean.Architecture.Solution.Template::8.0.5
2. dotnet new ca-sln --client-framework Angular --output test (or React one)
3. update the Azure.Identity 1.10.4 to the latest
4. try to run again
6. see error

**Expected behaviour**
The code to either support the latest version with no vulnerability or clarification on if the warning as error should be bypassed despite the vulnerability

**Comment by betty2310** [comment]
Change version of Azure.Identity in `Directory.Packages.props` file from 1.10.4 to 1.11.0 solve this problem
More information in [GitHub Advisory Database](https://github.com/advisories/GHSA-wvxc-855f-jvrv)

**Comment by Wosiu6** [comment]
> Change version of Azure.Identity in `Directory.Packages.props` file from 1.10.4 to 1.11.0 solve this problem More information in [GitHub Advisory Database](https://github.com/advisories/GHSA-wvxc-855f-jvrv)

That did not work and I still get the same error as seen in the log file I uploaded

**Comment by furritos** [comment]
The answer @betty2310 provided worked perfectly, thanks!

**Comment by JasonFoglia** [comment]
In VS 2022 nuget manager, this showed the issue/error/vulnerability, I was able to update the package to the latest 1.11.3 and it works fine for me. 

Tip: You can click on "Show only vulnerable" and this package should show.

**Comment by Wosiu6** [comment]
I did not manage to resolve this on my local and went with one of the other, similar projects.
