### ISSUE TITLE
SqlException: Invalid object name 'Serilogs'.

### ISSUE THREAD

**Issue by LokenLaishram** [jasontaylordev/CleanArchitecture#1176]
Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while saving the entity changes. See the inner exception for details.'
SqlException: Invalid object name 'Serilogs'.
Please help to fix this issue.

**Comment by mariasehar** [comment]
I am having the same issue i don't have any table in my database while all my migrations are applied correctly but still i am getting this error saying: Invalid object name 'MembershipTypes' when i am updating my database. Any solution? Thank you in anticipation.

**Comment by jasontaylordev** [comment]
These seem to be two separate issues relating to individual tables. Since @LokenLaishram didn't respond I'll assume he no longer requires assistance.

@mariasehar, if you still require assistance, can you please raise a new issues and include some steps to reproduce?

Thanks
