### ISSUE TITLE
{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occurred while processing your request.","status":500}

### ISSUE THREAD

**Issue by LokenLaishram** [jasontaylordev/CleanArchitecture#1178]
{"type":"https://tools.ietf.org/html/rfc7231#section-6.6.1","title":"An error occurred while processing your request.","status":500}
Error occur while login the application.

**Comment by jasontaylordev** [comment]
Unfortunately, I don't have enough information to support this issue. If you still require assistance, please create a new issue and share the steps to reproduce it, including a sample repo.
