### ISSUE TITLE
Question: Relating ApplicationUser to entities in the domain

### ISSUE THREAD

**Issue by BenyErnest** [jasontaylordev/CleanArchitecture#118]
Hi,
I would like to know how to create a navigation property from an entity in the domain to the ApplicationUser entity, since the latter is in the Infrastructure layer. Regards.

**Comment by nikibreg** [comment]
They've answered this [`here`](https://github.com/jasontaylordev/CleanArchitecture/issues/87#issuecomment-599281162)

**Comment by BenyErnest** [comment]
Thanks.
