### ISSUE TITLE
Internal server error if a invalid parameter is sent on the route

### ISSUE THREAD

**Issue by alamadorm** [jasontaylordev/CleanArchitecture#1191]
**Describe the bug**
If i have an endpoint todo/:id in wich de id is int and i send an string is causing an internal server error, it should respond with a bad request.
To fix this I handled the exception in the exception Handler, but for some reason, if the ASPNETCORE_ENVIROMENT is set to  Production there is not detail in the response, otherwise is returning the details on the response.

**To Reproduce**
1. Call the [PUT] /api/TodoItems/{id} endpoint with an string intead of a integer

**Expected behavior**
It should return a bad request

**Comment by jasontaylordev** [comment]
There's a lot to unpack here, can you share a repo that reproduces the issue please?

**Comment by jasontaylordev** [comment]
This issue is being closed due to inactivity.
