### ISSUE TITLE
Question: Using IDateTimeService in DTO mapping

### ISSUE THREAD

**Issue by molntamas** [jasontaylordev/CleanArchitecture#120]
I am returning a View Model of invoice data from a handler where I would like to check if the invoice is overdue.
I would like to compare a date field to the current date.

I wanted to implement this in the Mapping method of the DTO class.
Is this somehow possible with the CleanArchitecture template setup? Or should I do this logic in the handler?

**Comment by MCCshreyas** [comment]
As you are returning ViewModel from the handler, better you associate the logic in handler itself, as its the business logic, it's better to write it in the handler itself.

**Comment by jasontaylordev** [comment]
Try injecting the `IDateTime` service into an AutoMapper [Custom Value Resolver](https://docs.automapper.org/en/stable/Custom-value-resolvers.html#custom-value-resolvers).

**Comment by jasontaylordev** [comment]
Thanks for your question, closing.
