### ISSUE TITLE
NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0));

### ISSUE THREAD

**Issue by Scott-Atkinson** [jasontaylordev/CleanArchitecture#1212]
**Describe the bug**
Installed the clean architecture cli and created a web api only project

**To Reproduce**
Ran the project straight after creation, gives me the following error:

NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0));

**Expected behavior**
To run and see the swagger api documentation

**Comment by Scott-Atkinson** [comment]
Following also happens when opening the project on a Windows machine, all projects can't be loaded.

![image](https://github.com/user-attachments/assets/d87a07e6-9050-4d36-b325-2b06243484dd)

**Comment by jasontaylordev** [comment]
I'm a little lost here, 'NSwag command line tool for .NET Core Net80, toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0));' is not an error. Can you share more information?

If you want to try again, follow these steps:

Download and install .NET 9 - https://dotnet.microsoft.com/en-us/download/dotnet/9.0

Install the latest template:
```bash
dotnet new install Clean.Architecture.Solution.Template::9.0.1
```

Create and build a new app:
```bash
dotnet new ca-sln -cf none --output WebApi
cd .\WebApi\
dotnet build
```

If you encounter an NSwag error, run the following to skip NSwag:
```bash
$env:SkipNSwag = "True"
dotnet build
```
This is useful in case the error is not actually NSwag but something else in the build.

If all going well, run the app:
```bash
cd .\src\Web\
dotnet run
```


Let me know if you encounter any errors along the way.

**Comment by jasontaylordev** [comment]
This issue is being closed due to inactivity.
