### ISSUE TITLE
Add support for DDD Specification pattern

### ISSUE THREAD

**Issue by rupeshkaslay** [jasontaylordev/CleanArchitecture#1219]
**Describe the solution you'd like**
https://en.wikipedia.org/wiki/Specification_pattern. Specifications allow recombination/chaining the business rules together using boolean logic. The pattern is frequently used in the context of Domain Driven Design.

Do you have any plan to introduce them in the near future?

**Comment by jasontaylordev** [comment]
I don't intend to implement support for the Specification pattern. I keep the template as simple as possible for better understanding and future development. You can check out a great implementation of the pattern here; https://github.com/ardalis/CleanArchitecture.
