### ISSUE TITLE
Create new migrations with cli

### ISSUE THREAD

**Issue by huenchunb** [jasontaylordev/CleanArchitecture#1232]
When I Create a new Migrations with this command, ```dotnet ef migrations add "SampleMigration" --project src\Infrastructure --startup-project src\Web --output-dir Data\Migrations``` I have an error. The message is: "Your startup project 'project.Web' doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for the Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again." Isn't the web layer supposed to have these references to Microsoft.EntityFrameworkCore.Design?

**Comment by jasontaylordev** [comment]
Thank you for reporting the issue; I've corrected it in the latest version.
