### ISSUE TITLE
The login & register pages are using default razor pages. Please provide option to create theses also in React so that they can be customized

### ISSUE THREAD

**Issue by parashgoswami** [jasontaylordev/CleanArchitecture#1236]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jasontaylordev** [comment]
Providing alternative options in Angular and React would require considerable effort and would also add complexity to the template, making it more difficult to maintain or enhance in the future.

If you would like to address this issue yourself, you can start by scaffolding the UI at https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-8.0&tabs=visual-studio. This will give you a solid understanding of how it works, allowing you to create a separate version in React afterward.
