### ISSUE TITLE
SPA Development server

### ISSUE THREAD

**Issue by Buutyful** [jasontaylordev/CleanArchitecture#1247]
**Describe the bug**
can't get the project template running
**To Reproduce**
run the project with web as a start-up project

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f2bc3230-fa94-461c-a1e5-9c0de0810550)

**Additional context**
Collaborators having the same problem

**Comment by jasontaylordev** [comment]
What type of project did you create Angular or React?
Try the following and let me know if you encounter errors.

Install npm packages:
```bash
cd src\Web\ClientApp
npm install
```

Run the Web project:
```bash
dotnet build
dotnet run
```

**Comment by JarrodWichers** [comment]
> thanks for the answer! it is the react client and yes i did install the npm of the client app! ![image](https://private-user-images.githubusercontent.com/115831639/380757018-9af96cef-87b2-4c7a-ab38-a65751a4407f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODg4NTIsIm5iZiI6MTczMTc4ODU1MiwicGF0aCI6Ii8xMTU4MzE2MzkvMzgwNzU3MDE4LTlhZjk2Y2VmLTg3YjItNGM3YS1hYjM4LWE2NTc1MWE0NDA3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNlQyMDIyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzNjYTdjOTU4NzM0YzIzNzQyZmFhY2M1N2E0Y2I4ZWQ1MDk3ZGU5NWUyMGQyMzUzYjkxYmUzMTRkZWQ0MmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.36WNA8zUUOG49RWCcUedF0kSmu7uEsSk4WUgc7UaxSo)

Hi @Buutyful , I hope you were able to solve this issue but if you haven't I ran into the same problem when trying to use the template for an angular version, I solved it by creating the /ASP.NET/https folder/s in %APPDATA% on windows. @jasontaylordev maybe consider adding a line like this in aspnetcore-https.js so it creates the folder in appdata if it doesn't already exist

`if (!fs.existsSync(baseFolder)) {
  fs.mkdirSync(baseFolder, { recursive: true });
}`

**Comment by jasontaylordev** [comment]
I've released a new version of the template with the above fix. Please try the following steps:

Download and install .NET 9 - https://dotnet.microsoft.com/en-us/download/dotnet/9.0

Check the prerequisites:
```bash
dotnet --version
node -v
npm -v
```
I'm running 9.0.100, v20.15.0, and 10.7.0.

Install the latest template:
```bash
dotnet new install Clean.Architecture.Solution.Template::9.0.1
```

Create and build a new react app:
```bash
dotnet new ca-sln -cf react --output ReactApp
cd .\ReactApp\
dotnet build
```

Build the react front end:
```
cd .\src\Web\ClientApp
npm run build
```
There will be some warnings but the front end should build.

Run the app:
```bash
cd ..
dotnet run
```


Let me know if you encounter any errors along the way.

**Comment by jasontaylordev** [comment]
This issue is being closed due to inactivity.

**Comment by carloswm85** [comment]
> I've released a new version of the template with the above fix. Please try the following steps:
> 
> Download and install .NET 9 - https://dotnet.microsoft.com/en-us/download/dotnet/9.0
> 
> Check the prerequisites:
> 

✅ This one answer **WORKED well** for my Angular project.

The only problem I had was this one time screen:

<img width="1278" height="742" alt="Image" src="https://github.com/user-attachments/assets/6e3043ff-a0c1-42d5-80fc-85b46bb365ec" />
