### ISSUE TITLE
Decoupling SPA and API

### ISSUE THREAD

**Issue by ChristopherEtter** [jasontaylordev/CleanArchitecture#126]
Is there a simple way to decouple the SPA and the WebAPI project to run the SPA from a console window and make changes and debug the WebAPI without having to recompile the SPA every time?

Typically I would just replace:
`spa.UseAngularCliServer(npmScript: "start");`
with
`spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");`
in Startup.cs.

However I can't seem to find the configuration to allow this in this Solution. The SPA keeps trying to find the WebAPI at at port 4200 and getting a 404 error.

**Comment by jasontaylordev** [comment]
That's really all you need to do. Just so we're on the same page:

1. Within **WebUI\Startup.cs**, replace:
   ```csharp
   spa.UseAngularCliServer(npmScript: "start");
   ```
   With:
   ```csharp
   spa.UseProxyToSpaDevelopmentServer("http://localhost:4200");
   ```
2. Launch the backend from `\WebUI` with the command:
   ```
   dotnet run
   ```
3. Launch the front end from `\WebUI\ClientApp` with the command:
   ```
   npm start
   ```

4. Navigate to  https://localhost:5001.

Let me know if that works.

**Comment by ChristopherEtter** [comment]
Hi, Thank you for your time. Yes this fixed this for me. The problem I was facing was that I had not been running it through the CLI, but through IIS Express, and then not starting from port 5001. It was user error, but thank you for your response. I am sure someone else will find this as helpful as I did.

**Comment by diegogvieira** [comment]
@jasontaylordev Could you help me understand how the application works. I see that the login implementation in angular uses some file to request configuration from API using fetch and localhost:5000 address... Could you provide me more information on how this works? Thanks
