### ISSUE TITLE
Breaking change to command dotnet dev-certs

### ISSUE THREAD

**Issue by Quotas** [jasontaylordev/CleanArchitecture#1266]
There has been a breaking change to the behaviour of dotnet dev-certs, it no longer creates a file path if its missing.

In the npm start https prerun script aspnetcore-https.js it runs the dev-certs command but errors if the file path does not exist due to the behaviour change. Needs to be updated to instead check if the dir exists and create it instead. 

Can see the changes documented here - [link](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/9.0/certificate-export)

**Comment by jasontaylordev** [comment]
Fixed in #1271. Thanks for raising this issue and providing the link.
