### ISSUE TITLE
Nswag configuration does not take into account the environment 

### ISSUE THREAD

**Issue by BenyErnest** [jasontaylordev/CleanArchitecture#127]
Trying to configure NSwag in this way 

![image](https://user-images.githubusercontent.com/12765321/81202810-1eed7900-8f95-11ea-93e3-83b8ca090b69.png)

but always read from appsetings.json although I have configured different settings in appsetings.Development.json. In fact if I remove the IdentityServer object from appsetings.json I get a build error in this line:
![image](https://user-images.githubusercontent.com/12765321/81203511-0c277400-8f96-11ea-9d60-ab4a66c1d0db.png)

**Comment by jasontaylordev** [comment]
Can you share a repo? I'd be happy to try.

**Comment by BenyErnest** [comment]
Hi Jason,
I've changed my project since the time I post the issue, but I forked this project and have reproduced the error, so I will share the forked project with you. Greets

**Comment by jasontaylordev** [comment]
Closing this issue, however just in case anyone encounters a similar issue, the biggest gotcha for this type of approach is that the MSBuild task only runs during development, i.e. Debug:

```xml
  <Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core31) run /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

If you want it to run for other configurations just remove `Condition="'$(Configuration)' == 'Debug'"`.

I take this approach to simplify my CI/CD pipeline.

**Comment by blackjack6809** [comment]
Encountered the same issue. There is no changes done in the .csproj file. It simply gives build error stating "dotnet dotnet-nswag.dll run /variables:Configuration=Debug" exited with code -1. Everything was running fine previously, but suddenly it fails to debug. Is there something i need to check in my machine? I would be happy to share repository, if needed.
