### ISSUE TITLE
Doesn't the sample you provided look like an anemic domain model ? 

### ISSUE THREAD

**Issue by barisvelioglu** [jasontaylordev/CleanArchitecture#130]
I think the domain layer should do more than just defining entities and their relationships as Martin Fowler suggested. However your todolist sample seems like anemic. What's your opinion about it? 

https://martinfowler.com/bliki/AnemicDomainModel.html

**Comment by jasontaylordev** [comment]
Hi @barisvelioglu - thanks for your question. I've haven't chosen to demonstrate a DDD-approach with this template. It's up to you to implement your preferred approach. I tend to follow this advice; https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/.

Happy Coding! 😊
