### ISSUE TITLE
NSwag and Client generating

### ISSUE THREAD

**Issue by sk0gen** [jasontaylordev/CleanArchitecture#131]
So I had trouble generating client on linux, because there was no clear way how to do this.
I found [nswagNPM](https://www.npmjs.com/package/nswag) package and finally generated api-client.

My suggestion is write a script to generate client from specification (or directly from nswag.json, because it's well configured)

**Comment by michalkrzych** [comment]
https://github.com/RicoSuter/NSwag/issues/2444

**Comment by michalkrzych** [comment]
https://github.com/RicoSuter/NSwag/issues/2444

**Comment by michalkrzych** [comment]
Duplicate of https://github.com/RicoSuter/NSwag/issues/2444
