### ISSUE TITLE
getting current user id in in cookie base authentication

### ISSUE THREAD

**Issue by farshidtorkaman** [jasontaylordev/CleanArchitecture#132]
hi. I have problem in getting current user id in my web application.
 I am not using identity server  or token base authentication in my project. i am using cookie base authentication with identity 3.1 but when i want to get current user id this code in CurrentUserService class doesn't work.
`httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier);`
but exactly this code works in controller.
can anyone help because i can not get current user id in other layers

**Comment by PhantomParadox** [comment]
@farshidtorkaman check #119 it might help

**Comment by farshidtorkaman** [comment]
@PhantomParadox yes i saw that but the solution was to put an authorize attribute in top of contoller but I don't want to be dependent to controller so I can use it in other layers

**Comment by flensrocker** [comment]
What ever you do in other layers, everything is done on behalf on some request. If this request isn't decorated with an `Authorize` attribute, there is no "current user".

With cookie authentication there's a corresponding middleware which extracts the cookie and transforms it into the `ClaimsPrincipal` of the `HttpContext`.

If you call your deeper layer from something different like a request (e.g. a hosted background service) you have to replace the `ICurrentUserService` in the service scope inside your background service so that the called code can use it.

Or what exactly is your use case?

**Comment by farshidtorkaman** [comment]
yes i have Authorize attribute on top of my controller. 
`httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier)` returns null in my case.
but i did not understand your solution for my problem. should I do something in startup.cs for transforming cookie to ClaimsPrincipal? I would be appreciate if you could explain more. thank you

**Comment by flensrocker** [comment]
How do you setup exactly the authentication in startup?

If you break on that line, which object is null? httpContextAccessor, HttpContext or User?

If httpContextAccessor is null, you have to add `services.AddHttpContextAccessor();` to your Startup.

When I use the default cookie authentication of Microsoft.Identity with `services.AddIdentity<...>()` (I haven't worked with IdentityServer so far), the `HttpContext.User` gets populated by some middleware with the data from the cookie.

**Comment by farshidtorkaman** [comment]
this is in startup.cs
![Screenshot (100)](https://user-images.githubusercontent.com/52992954/82349283-29852500-9a0f-11ea-9caa-b18936173ae2.png)
and this is in infrastructure layer dependency injection
![Screenshot (101)](https://user-images.githubusercontent.com/52992954/82349355-3d308b80-9a0f-11ea-9086-9ff8eb8f708b.png)
and httpContextAccessor.HttpContext.User is not null but when I collapse User this is what I get
![Screenshot (102)](https://user-images.githubusercontent.com/52992954/82350133-32c2c180-9a10-11ea-984d-f275829fcc7f.png)
and I am completely sure that I had logged in.

**Comment by flensrocker** [comment]
These parts seem to be ok.

Next step is the login code. Do you use the SignInManager to authenticate the user?

**Comment by farshidtorkaman** [comment]
yes. this is how I do it.
`await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false)`

**Comment by flensrocker** [comment]
I'm running out of ideas...

What kind of resource do you access, an api controller or a razor page?

If you inspect httpContext.Request.Cookies, do you see your authentication cookie? Do you see it in your browser?

Without seeing the whole code and the possibility to debug myself, I'm done...

**Comment by farshidtorkaman** [comment]
Razor page. Shoud’nt I add custom claims after registering a user? Right now i am just use simple UserManager and CreateUserAsync

**Comment by flensrocker** [comment]
Have you added that page via the razor page options to authorization?

https://docs.microsoft.com/en-us/aspnet/core/security/authorization/razor-pages-authorization?view=aspnetcore-3.1

**Comment by farshidtorkaman** [comment]
@flensrocker I mention this before and I think it would be better I do it again
`httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier)` is working in controllers. but it is not working in independent class

**Comment by flensrocker** [comment]
What exactly do you mean with "independent class"? If this is a class which is injected on a razor page, it should work, if this razor page is protected by authorization.

Can you access that page without login?

**Comment by farshidtorkaman** [comment]
i meant it is not inherited from any other class except ICurrentUserService.
and no it will send me to login page

**Comment by flensrocker** [comment]
Sorry, but I'm lost...

Can you share the code of that class?

**Comment by farshidtorkaman** [comment]
I have the project in my repositories. leo-coin

**Comment by flensrocker** [comment]
That helps. Which page has the problem?

**Comment by farshidtorkaman** [comment]
src/WebUI/Area/Panel/DashboardContoller.cs - index action
CurrentUserService is in WebUI/Services
Actually I have not commit my changes but I need userid in that action and i have to recieve it from currentUserService

**Comment by flensrocker** [comment]
I will look into the code tomorrow.

**Comment by flensrocker** [comment]
I can reproduce your problem, but I don't know a solution yet.

**Comment by farshidtorkaman** [comment]
Thank you so much for your help.

**Comment by flensrocker** [comment]
Ok, now I have a clue.

The constructor of `CurrentUserService` gets executed before the authorization middleware kicks in to populate the `HttpContext.User`. I don't know if it's related to cookie authentication or if it's a general problem. If I change the `CurrentUserService` to some kind of lazy evaluation of the `UserId` everything seems to work.

```c#
    public class CurrentUserService : ICurrentUserService
    {
        public CurrentUserService(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        private bool _init = false;
        private IHttpContextAccessor _httpContextAccessor;
        private string _userId;
        public string UserId
        {
            get
            {
                if (!_init)
                {
                    _userId = _httpContextAccessor.HttpContext?.User?.FindFirstValue(ClaimTypes.NameIdentifier);
                    _init = true;
                }
                return _userId;
            }
        }
    }
```
With this the `ICurrentUserService` can be injected into your query-handler and it will have the right userId.

**Comment by farshidtorkaman** [comment]
It worked!! 
I really dont know what to say. Thank you so much
