### ISSUE TITLE
xUnit IntegrationTests, ApplicationInsightsTelemetry - Mediator.Send(request)  throws exception

### ISSUE THREAD

**Issue by vthattai** [jasontaylordev/CleanArchitecture#133]
My aspnetcore 3.1 web api uses Azure AppInsights. it's Startup.ConfigureServices() has a services.AddApplicationInsightsTelemetry(). 

I'm using Testing.cs (or SliceFixture) from a xUnit integration test project. both projects appsettings have the same appInsights/instrumentation key setting.

Mediator.Send(request) throws the following exception when called from a  xUnit Test (fact) method. The handler never gets called. If i comment the AddApplicationInsightsTelemetry() from the WebApi startup it works fine.

"Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'."

**Comment by vthattai** [comment]
@alcidesfmelof can you step thru and put a try catch where it fails and post the exception message/stack?

**Comment by alcidesfmelof** [comment]
It's the same as you reported.
`
Unable to resolve service for type 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' while attempting to activate 'Microsoft.AspNetCore.Hosting.DefaultApplicationInsightsServiceConfigureOptions'.'
`

**Comment by vthattai** [comment]
try adding this line
services.AddSingleton(Mock.Of<IHostingEnvironment>());

**Comment by alcidesfmelof** [comment]
Yeah, it works apparently. I am getting a DI error so my test is not running but I guess I can find out what it is.

Thank you.

ERROR I have now.
`
System.InvalidOperationException : Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Empient.Infrastructure.Email.SendGridSender'.`

**Comment by vthattai** [comment]
try commenting out the 3 lines - Mock of IWebHostEnvironment

**Comment by alcidesfmelof** [comment]
I rollback the first `services.AddSingleton(Mock.Of<IHostingEnvironment>());` and added `services.AddSingleton<IConfiguration>(Configuration); `and this sorted my whole problem. Tests running now.
