### ISSUE TITLE
The project folder should be organized in Git Submodules

### ISSUE THREAD

**Issue by pcarvsilva** [jasontaylordev/CleanArchitecture#134]
Suppose the base classes change with a modification on the template, how could I update it ? 
I've should be able to get new code from the modules calling git pull on submodules. 

Suppose the template now has a new feature like sending emails. How would I get it ?
I've should be able to get new code adding a new submodule to my project.

Possible solution:

* On Application create a submodule with  Common folder
* On Domain do the same for the Common folder 
* On Infrastructure/Files create a Common submodule and insert the CsvBuilder.cs
* On Infrastructure/Persistance make a Common submodule and let the user generate the config in  and migration folders by extending  the base classes on Infrastructure/Persistence/MyContext in case you use multiple databases
* On Infrastructure/Identity use the same logic to make it easier to add user permissions
* On Controllers  same thing

If a new feature like email appears on Infrastructure I've should be able to add it creating the folder structure Infrastructure/Email/Commons and make custom code on Infrastructure/Emails/MyEmailService

Another nice feature whould be that I could also create a  custom submodule for my Infrastructure code containing all Infrastructure submodules so if I have a lot of microservices that use the infrastructure I would be able keep it all tied up with minimum effort

Thanks in advance. 
Such a nice project.

**Comment by jasontaylordev** [comment]
HI @pcarvsilva - that is an awesome idea and some that I might look into in the future. However, for now, I will leave it out as I am trying to keep the template as simple as possible.
