### ISSUE TITLE
Foreign Key to ApplicationUser from Domain Entities

### ISSUE THREAD

**Issue by erkinyldz** [jasontaylordev/CleanArchitecture#136]
Currently in the sample application ToDoList items are public and same for every user. I think this sample would be more complete if ToDoList items would belong to users, so each user would have their own list.

To manage something like that, what would be the best way to have a foreign key to AspNetUsers table?

**Comment by sk0gen** [comment]
I get to same point. How to manage to create Entity that belongs to User?
Any help would be appreciated

**Comment by jpsullivan** [comment]
It would appear that this question has been asked and answered [here](https://github.com/jasontaylordev/CleanArchitecture/issues/87#issuecomment-599281162).

**Comment by erkinyldz** [comment]
It seems like this question is indeed answered. Correct me if I'm wrong but, the ideal way seems to be having UserID saved but not referenced to any other place. Saving UserId is as simple as inheriting from AuditableEntity
