### ISSUE TITLE
[Feature request] Use fluent validation rules on controller query parameters, body parameters

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#139]
Use fluent validation rules on controller query parameters, body parameters so we return a meaningful error message.

Ex: when the required query parameter is missing, it returns 500.

{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "title": "An error occurred while processing your request.",
    "status": 500
}

**Comment by jasontaylordev** [comment]
Hi, @litan1106 - thanks for your continued support. As per #153 this should be fixed. Let me know if it's not the case.
