### ISSUE TITLE
Should Application know about EntityFramework?

### ISSUE THREAD

**Issue by NickFranceschina** [jasontaylordev/CleanArchitecture#140]
First, thank you for this project, it has been very helpful! 

`IApplicationDbContext` is defined inside of the Application project and uses `DbSet` in the interface... which requires a reference to EntityFramework... which is more of an Infrastructure detail, is it not?  Wouldn't it be more correct to define a generic interface (repository or not) then have the infrastructure implement that with whatever tooling it decides?

**Comment by MCCshreyas** [comment]
You might. I think the `DbSet<>` are just there in the interface just to enforce implementing class that these are the domain entities, and you should have the corresponding DbSet for them to perform operations.

**Comment by flensrocker** [comment]
See #42

**Comment by jasontaylordev** [comment]
Thanks @NickFranceschina, you're welcome. I think #42 covers it well, closing.

**Comment by NickFranceschina** [comment]
apologies... I thought I had searched around for a previous issue before posting new
