### ISSUE TITLE
Q: Dispose of _currentTransaction in ApplicationDbContext

### ISSUE THREAD

**Issue by flensrocker** [jasontaylordev/CleanArchitecture#141]
I like the methods around transactions in your `ApplicationDbContext`. But I wonder if there is some kind of leak with the `_currentTransaction` if neither `CommitTransactionAsync` or `RollbackTransaction` is called, maybe due to an exception.

Normally I would write something like
```
using (var transaction = await appDbContext.Database.BeginTransactionAsync())
{
  ...
  await transaction.CommitAsync();
}
```
where I dispose the transaction and get an automatic rollback on an exception before the commit.

Shouldn't the `ApplicationDbContext` implement `IDisposable` and rollback the `_currentTransaction` on dispose? Or will this be automatically disposed from within the `DbContext` base class?

**Comment by jasontaylordev** [comment]
Actually, these methods are not in use and I have removed them. I used them when I was trying out different approaches to automated testing but forgot to remove afterwards.
