### ISSUE TITLE
Protecting Routes in Client App

### ISSUE THREAD

**Issue by altumcon** [jasontaylordev/CleanArchitecture#143]
I am trying my hands into this code base. I want to know how can we protect routes in client app with roles. As the authorise attribute is working fine but my protected routes are showing to user who are not holding the admin rights.
Is there a way I can hide the routes based on the role.

**Comment by AlQuraian** [comment]
Yes, there's a way. However, you would have to do this on the frontend.
In your frontend project, get the the user's roles from the backend and create a [route guard.](https://angular.io/guide/router#preventing-unauthorized-access)

**Comment by jasontaylordev** [comment]
Thanks @AlQuraian, closing.
