### ISSUE TITLE
[Question] Presentation Layer Depend On Application and Infrastructure

### ISSUE THREAD

**Issue by Admiralkheir** [jasontaylordev/CleanArchitecture#146]
I watched the GOTO2019 video and liked this template too much but I didn't get it truly. When I looked WebUI.csproj, I have noticed the Presentation layer depends on Application and Infrastructure. According to the video, Presentation and Infrastructure should be depended

**Comment by MrKonstantinSh** [comment]
The README.md file says "WebUI layer is a single page application based on Angular 9 and ASP.NET Core 3.1. This layer depends on both the Application and Infrastructure layers, however, the dependency on Infrastructure is only to support dependency injection. Therefore only Startup.cs should reference Infrastructure." 😄

**Comment by AlQuraian** [comment]
The clean architecture or onion architecture implies that the most outer layers depend on inner layers. So, presentation and infrastructure would depend on application and domain, see:
https://jasontaylor.dev/clean-architecture-getting-started/

**Comment by Admiralkheir** [comment]
Thanks for explanations, I should have been more careful, sorry :sweat_smile:
