### ISSUE TITLE
caniuse-lite Oudated

### ISSUE THREAD

**Issue by tparikka** [jasontaylordev/CleanArchitecture#15]
**Is your feature request related to a problem? Please describe.**
On build, there is a notification that caniuse-lite requires an update:
![image](https://user-images.githubusercontent.com/7715790/70359345-4f43b680-1841-11ea-8265-fec9d70e00ca.png)

**Describe the solution you'd like**
I would suggest that the project be updated to use the current version of caniuse-lite.

**Comment by jasontaylordev** [comment]
This has been resolved. Thanks.
