### ISSUE TITLE
[Question] using IFormFile in Application Layer ?

### ISSUE THREAD

**Issue by abdullahahmedmohamed** [jasontaylordev/CleanArchitecture#150]
**is that acceptable to declare property of type `IFormFile` in command and use it in Application Layer ?**

Because i think the `IFormFile`  type is more related to the framework and presentation layer
for example in asp net mvc to bind files we used `HttpPostedFileBase` now in asp core we use `IFormFile` and maybe tomorrow there is new type for files  .

**so should i make abstraction on it ?** and if so can you give me an example how to make it
also if i shouldn't how i can use it  !
**maybe just passing it to a service in Infrastructure to save it ... ?**

**Comment by altumcon** [comment]
I have used IfromFile in command request of the application layer.

**Comment by baffourt** [comment]
I have handled the `IFormFile` just at the presentation layer and then either save the content to MemoryStream to be used at the Application layer level. 
This is an example
```
public class ImportDataCommand : IRequest
{
   public MemoryStream FileData {get; set; } 
}
```
Then in my view, I create a property of `IFormFile` with a `[BindProperty]`, 
OnPostAsync I get the content into a memory stream before calling Mediator.Send
```
if(ImportFile != null)
{
   using var memoryStream = new MemoryStream();
   ImportFile.CopyTo(memoryStream);
   var command = new  ImportDataCommand(){ FileData = memoryStream};
   Mediator.Send(command);
}
```
