### ISSUE TITLE
.Net Core MVC

### ISSUE THREAD

**Issue by iozcelik** [jasontaylordev/CleanArchitecture#152]
I try to implement this template without using Angular. But I have some problems. My problems;

- I want to use create and edit page same. But how to convert or use Dtos or ViewModels in here?
- I have multiple Dto and Domain class. And sometimes I may miss a property. Why we do not use an interface and implement this interface to Dto and Domain model? If it is a good implementation, where we keep them?
- I have 2 seperate databases. They are MsSql and MongoDb. There is no good example on internet. I do something but I am new at Mediatr and CQRS. How do I learn best practices?

So I think, this template and also NortwindTraders repository are great. I learn lots of thing from them. I suggest to add a clear asp .net core mvc application. So we could learn how to implement it. Also some another database example will be good. Because I watch your videos and read blogs. You and also lots of developer say you can use easily different ui and database. Ok, in theory, it is perfect. However in real application?

**Comment by danijel88** [comment]
Hi @iozcelik ,
Instead to use WebUI, you should just create new project MVC, and start to use Mediatr there.
WebUi is just presenting layer.
In MVC if you want to have ViewModels you have two options:

1. Create same classes as DTOs  in ViewModels folder
2. use already exist DTO's inside of you Controllers

I had saw both options to be used, and I think it is only the matter of practice.

About Multiple Dto and Domain class. You can use interfaces for Domain,for DTO I didn't saw till now any developer to use Interface to develop Dto. Probably reason is that Dto some can contain different properties which can be mapped from different Domain.

I hope I had help you a little bit.

**Comment by iozcelik** [comment]
Actually, I do not decide which one is correct in case of the below code. Now I need a model to shown some values when page loading. But using Dto or using a command is critical here.

Using command:
```
        [HttpGet]
        public async Task<IActionResult> UpsertAsync(long? id) {
            if (id == null) {
                return View();
            }
            var category = await Mediator.Send(new GetCategoryQuery { Id = id.Value });
            var categoryCommand = Mapper.Map<UpsertCategoryCommand>(category);
            return View(categoryCommand);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Upsert(UpsertCategoryCommand command) {
            if (ModelState.IsValid) {
                await Mediator.Send(command);
                return RedirectToAction(nameof(Index));
            } else {
                return View(command);
            }
        }
```

Using DTO: (Validator not working as expected.)
```
        [HttpGet]
        public async Task<IActionResult> UpsertAsync(long? id) {
            if (id == null) {
                return View();
            }
            var category = await Mediator.Send(new GetCategoryQuery { Id = id.Value });
            return View(category);
        }

        [HttpPost]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesDefaultResponseType]
        public async Task<IActionResult> Upsert(CommandDto dto) {
            if (ModelState.IsValid) {
                var command = Mapper.Map<UpsertCategoryCommand>(dto);
                await Mediator.Send(command);
                return RedirectToAction(nameof(Index));
            } else {
                return View(command);
            }
        }
```
In my opion, using command is good choice but mapping in here, is right?

**Comment by danijel88** [comment]
Hi @iozcelik ,
May I kindly ask you to upload the code in repository for checking so I can give you proper replay ?
Regards,
Danijel

**Comment by iozcelik** [comment]
Hi @danijel88 ,

I create a [repository](https://github.com/iozcelik/NorthwindTraders).

What I did?

- Use asp .net core 3
- Add IMapFrom<CategoryDto> to UpsertCategoryCommand
- Add UpsertCategoryCommandValidator
- Add GetCategoryQuery
- Added all views and related controller

**Comment by danijel88** [comment]
Hi,
I have check code. I'm thinking how we can move Mapping inside of business logic , for the moment leave as it is till not find proper solution.

**Comment by scottkuhl** [comment]
Has there ever been any requests to provide a front end in this solution template for MVC, Razor Pages or Blazor?  I'm wondering how popular the Angular frontend really is and if most people using the template or swiping parts of the code are just removing that part.

**Comment by nixonad** [comment]
I use this template just for my API layers, I have a separate project with a React UI utilising the API

**Comment by jasontaylordev** [comment]
Hey all, thanks for your feedback. I'll likely be switching the template to just use Web API. This way, it can be useful for more people.
