### ISSUE TITLE
How to handle Validation exceptions for razor views?

### ISSUE THREAD

**Issue by jawand** [jasontaylordev/CleanArchitecture#153]
Hello Jason,

Great work on this template project.

I have one question i.e. how to handle validation exceptions thrown by `Application Layer`?

```
public async Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate<TResponse> next)
{
      ValidationContext context = new ValidationContext(request);

      var validationResults = await Task.WhenAll(_validators.Select(v => v.ValidateAsync(context, cancellationToken)));
      List<ValidationFailure> failures = validationResults.SelectMany(r => r.Errors).Where(f => f != null).ToList();

      if (failures.Count != 0)
          throw new ValidationException(failures);

      return await next();
}
```

Now, in the ApiExceptionFilter we have handled the exception, but since the sample is just an API it returns a JSON object.

Whereas in my case I want to re-display the same MVC Razor page and display all the validation errors as per the Model properties.

Now, this is what I have attempted to do. I hope you might be able to help me out.

In `ApiExceptionFilter.cs`

```
private void HandleValidationException(ExceptionContext context)
{
	var exception = context.Exception as ValidationException;

	foreach (var item in exception.Errors)
        {
		context.ModelState.AddModelError(item.Key, item.Value[0]);
        }
        
        // it does bring all the model properties. But, how can I make it a full object and set it inside `result.Model` ??
        foreach (var item in context.ModelState)
        {
		string parameter = item.Key;
                object rawValue = item.Value.RawValue;
                string attemptedValue = item.Value.AttemptedValue;

                System.Console.WriteLine($"Parameter: {parameter}, value: {attemptedValue}");
        }

        if (context.ActionDescriptor is ControllerActionDescriptor controllerActionDescriptor)
        {
                //How pass here Model from context??
		var result = new ViewResult
                {
                    ViewName = controllerActionDescriptor.ActionName,
                    ViewData = new ViewDataDictionary(_modelMetadataProvider, context.ModelState),
		    Model = //???? 
                };

                
                context.Result = result;
        }
	context.ExceptionHandled = true;
}
```

Can you please help me with this issue?

**Comment by baffourt** [comment]
@jawand , did you get a solution to this scennario. I am facing the same  challenge

**Comment by baffourt** [comment]
The solution suggested above works half the time since you start experiencing errors. (Test failures)
with Error `A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.`

This error occurs where Validator Classes have MustAsync with ApplicationDbContext injected.

**Comment by baffourt** [comment]
I was finally able to solve the above with the help of JeremySkinner, I added FluentValidation.AspNetCore to the Razor project and added it to the StartUp class with this
`services.AddRazorPages().AddFluentValidation()` without specifying the Validator class from the Application project. I left the ApiExceptionHandler as it is and then errors are properly shown and the `HandleValidationException` is not even hit as FluentValidation.AspNetCore sees and populates the ModelState immediately a validation exception occurred on the Application library.

**Comment by jasontaylordev** [comment]
Hi @baffourt. I was going to respond with something completely different but then I realised that this is in fact, a good approach. The goal of running the validators within the Application layer is that you're independent of the UI, this means you won't need to re-implement validation if you switch technologies. Of course, you still have to figure out how the client will handle the validation exceptions, as you've have identified above. 

Using the approach you've implemented, you haven't duplicated any validation, you're just saving the Application layer the effort. It's still using the same validators, it's just that anything passing through to the Application layer will already be valid. If you build a Console UI, the RequestValidationBehaviour will still run and validate any requests throwing a ValidationException as necessary.

Good job, and thanks for taking the time to describe your solution. ❤

**Comment by alcidesfmelof** [comment]
Trying to do the same, but I get the following error in my StartUp class, any ideas? I tried to downgrade the version to 8.6.2 and the same happen.

@baffourt 

`System.MissingMethodException: 'Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection FluentValidation.ServiceCollectionExtensions.AddValidatorsFromAssembly(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Reflection.Assembly, Microsoft.Extensions.DependencyInjection.ServiceLifetime)'.'`

**Comment by alcidesfmelof** [comment]
Just find out that the versions of FluentValidation between my WebUI and Application were different and were causing the error. I will leave the comments in case someone faces the same problem.

**Comment by alcidesfmelof** [comment]
but I did not manage to get the validation error to display through the page.

it occurs as an Exception
Any ideas of what I can be happening?

![image](https://user-images.githubusercontent.com/34923255/91758116-5f69a600-ebc7-11ea-9ba6-43a66bb5b0e9.png)

**Comment by baffourt** [comment]
@alcidesfmelof Can you check the  ModelState before trying to post?
`if (ModelState.IsValid)
            {
                await Mediator.Send(Command);
                return RedirectToPage("Index");
            }
            return Page();
`
The point is to populate the Validation errors  before the Command is executed.

**Comment by iayti** [comment]
> @alcidesfmelof Can you check the ModelState before trying to post?
> `if (ModelState.IsValid) { await Mediator.Send(Command); return RedirectToPage("Index"); } return Page(); `
> The point is to populate the Validation errors before the Command is executed.

#224 PullRequest ValidateModelFilterAttribute.cs globally handle ModelState.IsValid issue and create JSON conversion error response. Check my solution.

**Comment by baffourt** [comment]
@iayti The problem @alcidesfmelof faces is to display Validation Errors on the model to the client on the page. Not to return a detailed JSON object with the description of the error.

**Comment by jawand** [comment]
@baffourt Thanks a lot for taking the initiative and solving this issue. 
Sorry, I was not around for any help. Thanks a lot!!! cheers 😎

**Comment by neozhu** [comment]
FIY:FluentValidation [Use with Page Models](https://docs.fluentvalidation.net/en/latest/aspnet.html#use-with-page-models)
It's been well in my project [RazorPageCleanArchitecture](https://github.com/neozhu/RazorPageCleanArchitecture)

**Comment by jawand** [comment]
@neozhu thanks for the help. I did checked out your codebase.

But, Our issue is with JSON response. what we wanted was simple model error i.e. bind with model classes and same errors can be shown on the cshtml page without any additional handling. (the out of the box model binding is what we wanted to achieve here)

Your codebase has all the response handled with JSON Request and response using AJAX. Which is something we are not using.
