### ISSUE TITLE
Sorting and Pagination

### ISSUE THREAD

**Issue by sk0gen** [jasontaylordev/CleanArchitecture#154]
How do you provide sorting and pagination for your queries?

Do you think an abstract class with properties for sorting like page, pagesSze and sort field and order is good solution?

**Comment by MCCshreyas** [comment]
Hi @sk0gen 
Recently I have opened pull request for the solution with pagination support. 
You might wanna check out that for help. 
#121

**Comment by jasontaylordev** [comment]
Thanks @MCCshreyas
