### ISSUE TITLE
What is best way to refer ApplicationUser in Domain Entities

### ISSUE THREAD

**Issue by ShamalFdo129** [jasontaylordev/CleanArchitecture#155]
@jasontaylordev  Could you let me know what is best way to add a relationship between ApplicationUser and other Domain Entities in EF? Since ApplicationUser in Infrastructure proj and other entities are in Domain proj.

**Comment by MCCshreyas** [comment]
Hi @ShamalFdo129 
The following issue threads will help you to understand. 

#71 #58

**Comment by ShamalFdo129** [comment]
@MCCshreyas 
Thank you very much. I got the idea.
