### ISSUE TITLE
[Question] Modify Registration

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/CleanArchitecture#156]
Hello,
I have only one question, how we can modify template for registration of new users ?
Regards,
Danijel

**Comment by thechadc** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization

**Comment by danijel88** [comment]
> https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=visual-studio#scaffold-identity-into-a-razor-project-with-authorization

@thechadc  Sorry I'm not so good in Front-end, that part I did already, but how I can now change to be used _Layout ? because still when I open Registration my changes are not visible. Probably I need something to do in Angular setup ?
