### ISSUE TITLE
"Root element is missing" when trying 'dotnet run'

### ISSUE THREAD

**Issue by JanOonk** [jasontaylordev/CleanArchitecture#158]
Followed all the installation steps, but when doing the last step 'dotnet run' I got an error:
```
C:\Program Files\dotnet\sdk\3.1.300\NuGet.targets(128,5): error : Root element is missing. [c:\Temp\clean-architecture-jasontaylor\src\WebUI\WebUI.csproj]

The build failed. Fix the build errors and run again.
```

Also opening the project in Visual Studio and doing a rebuild solution give errors.
The solution for me was clearing NuGet caches:
Tools > Nuget Package Manager > Package Manager Settings > General > Clear all Nuget Caches

Just wanted to document / let you know.

**Comment by jasontaylordev** [comment]
Thanks for sharing @JanOonk - much appreciated. 👍
