### ISSUE TITLE
HTTP Error 500.30 - ANCM In-Process Start Failure

### ISSUE THREAD

**Issue by gitprabin** [jasontaylordev/CleanArchitecture#160]
When i publish and run the application i got, ANCM In-Process Start Failure in browser, 
My publish method is File System, Deployement Mode is Framework-Dependent, Target Runtime is Portable.

-I Used to solve by microsoft docs from this references link,
https://docs.microsoft.com/en-gb/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1
but not resolved from known methods.
-Others app which runs 3.1 core have no problem, all run well in same iis configuration.
What is the problem on this project template ?

Image mention below,
(https://user-images.githubusercontent.com/9878542/83894868-97e91780-a771-11ea-8409-945b38365b0a.png)

**Comment by workcontrolgit** [comment]
I often got this error when publishing to Azure App Services.  Where do you publish your app to?   For me, the error was related to network connectivity to the database server and database permission.   I had to enable stdout to see the error detail.

**Comment by Admiralkheir** [comment]
You can enable logs on web.config then check it. https://stackoverflow.com/questions/40536073/where-do-logs-go-when-running-asp-net-core-on-iis-7-5 Don't forget to give permission to IIS_IUSRS and check the event viewer

**Comment by gitprabin** [comment]
I have found the issue on identity server configuration, finally i have published, Thanks for you Admiralkheir  and workcontrolgit  for the response.
