### ISSUE TITLE
consumer attribute is ignored

### ISSUE THREAD

**Issue by altumcon** [jasontaylordev/CleanArchitecture#163]
**Describe the bug**
how to configure consumer attribute so the controller content type is changed to multipart/form-data.
or Is there a way to configure swagger to use multipart/formdata 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nikibreg** [comment]
Add `[FromForm]` inside the controller action, before the parameter.
Example: 
`[HttpPost("Add")]
async Task<ActionResult<string>> Add ([FromForm] AddCommand command)`

**Comment by altumcon** [comment]
controller 
 public async Task<ActionResult<long>> Create([FromForm] CreateNewsCommand command)
        {

           // var command = new CreateNewsCommand();
            //command.NewsMedia = file.;
            return await Mediator.Send(command);
        }
Reuest:

 public class CreateNewsCommand : IRequest<long>
    {  public long NewsDetailId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsDetails { get; set; }
        public string NewsExcerpt { get; set; }
        public bool IsPublished { get; set; }
        public  IFormFile NewsMedia { get; set; }
    }
Now the problem is after I select a file , execute button doesn't respond.
Execute button works only if I don't select any file and fill the other entries, however it pass a null request.
Please suggest me what went wrong.

**Comment by jasontaylordev** [comment]
Hi @altumcon - sounds like a good question for StackOverflow. Happy Coding. 👍
