### ISSUE TITLE
Does Infrastructures know/ depend on Presentation ? 

### ISSUE THREAD

**Issue by lehoangphan** [jasontaylordev/CleanArchitecture#172]
Presentation depends on Core 
Infrastructure depend on Core 

but does Infrastructure know anything in Presentation ? or Presentation know anythig in Infrastructure ?  (call class, method from other )

thanks.

**Comment by GFoley83** [comment]
> but does Infrastructure know anything in Presentation ? or Presentation know anythig in Infrastructure ? (call class, method from other )

No. The answer for this is in the README; Presentation references the other projects for dependency injection only.

**Comment by lehoangphan** [comment]
> > but does Infrastructure know anything in Presentation ? or Presentation know anythig in Infrastructure ? (call class, method from other )
> 
> No. The answer for this is in the README; Presentation references the other projects for dependency injection only.

thanks you !
