### ISSUE TITLE
[Question] How to separate nav menu links based on Role

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/CleanArchitecture#173]
Hi, 
Question, how we can choose what user see based on Role from FrontEnd side, authorization from api are clear ?

**Comment by GFoley83** [comment]
Clean Architecture doesn't currently support roles or checking claims E.g for a role. However there are working examples of how to add this feature in this issue:
https://github.com/jasontaylordev/CleanArchitecture/issues/56#issuecomment-611468861

After that, to check for a role or role claim in the front end you'd need to either add the claim to the access token that gets returned on sign in. Or create something like a /me API that returns information about the currently signed in user and add your role info there for the front end to call.

**Comment by danijel88** [comment]
Hi @GFoley83  thanks for the replay, I even before had saw that discussion. I like your suggestion. Since I'm quite new in Identity Server and for the fron end I'm newbie, my idea was to somehow change
```
export class User {
  constructor(settings: UserSettings);

  id_token: string;
  session_state: any;
  access_token: string;
  refresh_token: string;
  token_type: string;
  scope: string;
  profile: any;
  expires_at: number;
  state: any;

  toStorageString(): string;

  readonly expires_in: number | undefined;
  readonly expired: boolean | undefined;
  readonly scopes: string[];
}
```
to add roles as an array, and to read from authorization service.
Do you have any idea how I can change that and manage when user is logged to generate that new property ?

**Comment by GFoley83** [comment]
I've update my branch with an example of what you need. Check out the solution from here and run it:
https://github.com/GFoley83/CleanArchitecture/tree/feature/auth-behavior

After you sign in with the default admin account, you'll see the role in the header:
![image](https://user-images.githubusercontent.com/838788/85812930-0a1fab80-b7b6-11ea-94cf-e807602a6849.png)
See here for code required to retrieve the role on the client: https://github.com/GFoley83/CleanArchitecture/commit/e133bf192d2c7364cadabc563692468132f7d36d#diff-e6582da6798f06541019910bfd19c52dR21

**Comment by danijel88** [comment]
Thanks, it helped me a lot. 
Regards

**Comment by MattMash** [comment]
Thanks so much @GFoley83
