### ISSUE TITLE
[Question] How to reuse logic across applications

### ISSUE THREAD

**Issue by tomekole** [jasontaylordev/CleanArchitecture#175]
Hi Jason,

I am looking for a right way to reuse code in another application.  

Let's say I create a console app - Todo importer. It is reading data from file and creating Todo items. 

How to reuse Domain, Application and Infrastructure in the console app? 

How about bulk operations? Are there any recommended patterns?

Thanks,
Tomek

**Comment by MCCshreyas** [comment]
I mean its very simple, you can send the Command from your console app to the application layer and it will just work fine. 
The application layer doesn't concern about what the UI layer might be console or web. Application layer only deals with Commands & Queries which implements `IRequest<T>`
