### ISSUE TITLE
Can i use the same Dto/View Model between different queries on the same entity

### ISSUE THREAD

**Issue by emadalsous** [jasontaylordev/CleanArchitecture#178]
Hello Jason,

Big thanks for this nice template. I really love this project and i use with all my new development. I would like to share with you some thought and take your opinion about it. Do you think that it is a good idea to share the same Dto of the same entity when i see that the view field are the same ?

For example:
 public class GetTodosQuery : IRequest<**TodosVm**> //This contains TodoListDto property

what if i want to create another query with GetTodoListById //Do you think it is a good idea to use the same TodoListDto but to set it up like a single object so i might have the following VM or just for example return TodoListDto that has been created for the previous query ?
public class TodosVm
    {
        public IList<PriorityLevelDto> PriorityLevels =
            Enum.GetValues(typeof(PriorityLevel))
                .Cast<PriorityLevel>()
                .Select(p => new PriorityLevelDto { Value = (int)p, Name = p.ToString() })
                .ToList();

        public TodoListDto ToDoList{ get; set; }
    }

I feel that there is a bit of repetitive work if i create different DTO per query that might lead to alot of code changes if my model for any reason change ?

One last thing:
I create a BaseRequestHandler that initialize the DBContext and Mapper when needed. Instead of inject them to each command handler i just inject the serviceProvider.
    public abstract class BaseRequestHandler<Request, Response> : IRequestHandler<Request, Response> where Request : IRequest<Response>
    {
        private IApplicationDbContext _dbContext;
        protected IApplicationDbContext DBContext => _dbContext ?? (IApplicationDbContext)ServiceProvider.GetService(typeof(IApplicationDbContext));
        protected IServiceProvider ServiceProvider { get; }

        private IMapper _mapper;
        protected IMapper Mapper => _mapper ?? (IMapper)ServiceProvider.GetService(typeof(IMapper));
        public BaseRequestHandler(IServiceProvider serviceProvider)
        {
            ServiceProvider = serviceProvider;          
        }

        public abstract Task<Response> Handle(Request request, CancellationToken cancellationToken);

    }

What do you think about this approach ? 

Best regareds,
Emad

**Comment by JosephIaquinto** [comment]
I think the purpose for having DTOs isolated to each command is a principle of the CQRS pattern. Although this adds a bit more boilerplate work due to having multiple similar DTOs, the intent is that if you add additional functionality, for example, a priority or deadline for a ToDo item which is not retrieved in the GetTodoList command, your GetTodoListById's DTO is easier to modify and keeps the original command and DTO untouched. This is some overhead of clean architecture but allows projects to keep functionality contained and manageable, a benefit of the CQRS pattern.

**Comment by GFoley83** [comment]
JosephIaquinto has summed it up really well. 
Jimmy Bogard (author of MediatR and AutoMapper) mentioned this on one of his talks and his point was something along the lines of, ask yourself, are the models accidentally the same, or, will a change to the model (add/remove a property) make sense for every use-case i.e. everywhere it's used? The answer to that should tell you whether to create a seperate model or reuse an existing one. For CQRS/MediatR it's usually the former.

**Comment by emadalsous** [comment]
Thanks Josephlaquinto, GFoley for your answers. Finally, i did like Jimmy Bogard mentioned on this. I treat this case by case and when i find a DTO that could be without modifying it for special case, i use shared model but when i need to add or modify existing DTO for special case i create directly new custom DTO without touching the existing one.

Best regards,
Emad
