### ISSUE TITLE
Why Application layer depends on Entity Framework ?

### ISSUE THREAD

**Issue by sencagri** [jasontaylordev/CleanArchitecture#179]
Hello,
I am suprised when I first see the Entity Framework Core dependency inside Application Layer. 

```csharp
using CleanArchitecture.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using System.Threading;
using System.Threading.Tasks;

namespace CleanArchitecture.Application.Common.Interfaces
{
    public interface IApplicationDbContext
    {
        DbSet<TodoList> TodoLists { get; set; }

        DbSet<TodoItem> TodoItems { get; set; }

        Task<int> SaveChangesAsync(CancellationToken cancellationToken);
    }
}
```
I think we have some problem here by adding external frameworks. Should'nt it be inside Infrastructure layer instead of Application layer ?

**Comment by GFoley83** [comment]
Good question. This was a conscious decision from my understanding as Entity Framework is the go-to Db ORM for the vast  majority of .NET solutions anyway. So adding a layer of abstraction just for the sake of it, is a waste of time.

You could easily fix this yourself by creating your own interface to replace `DbDet` inside the application layer and leaving the logic that implements it in the Infrastructure layer.

**Comment by walpoles93** [comment]
I was initially concerned about this implementation too, but I think since EF Core is itself an abstraction of the actual data access anyway, it makes sense to have it here. You still have the option to change database provider (ie. SQL Server, MySQL etc) in the infrastructure layer, and creating an extra layer of abstraction just for the purpose of not referencing EF Core would be overkill.

**Comment by jasontaylordev** [comment]
Thanks all, closing.

**Comment by melfeqy** [comment]
Hi all,
Can we consider Dapper ORM as an abstraction like EF and adding its framework to application layer also ?

**Comment by neman** [comment]
You can do whatever you want or like. There is no silver bullet. It depends on the context. Don't do premature abstraction if you don't need it. 
I am myself guilty of doing it in the past to prove my architectural skills. Many years of experience later, made me to be more pragmatic than purist. Just follow YAGNI and do not build software to protect comet hitting the Earth.
Follow patterns, solid and other practice when you need. Let your code guide you and refactor with green lights.
