### ISSUE TITLE
Conversion from xUnit to NUnit

### ISSUE THREAD

**Issue by nixonad** [jasontaylordev/CleanArchitecture#185]
@jasontaylordev : This is just a question, I was wondering at your rationale behind converting from xUnit to NUnit for unit and integration tests? 
I see that NUnit is getting some attention these days, at a a stage a while ago the project seemed to have been abandoned.

**Comment by AliBayatGH** [comment]
Answered https://www.youtube.com/watch?v=2UJ7mAtFuio&t=718s
