### ISSUE TITLE
MVC Localization

### ISSUE THREAD

**Issue by Tbd19** [jasontaylordev/CleanArchitecture#188]
In the MVC there are the DataAnnotations that I used in previous projects where I add the Display attribute to localize the application.
I saw the other post about the MVC but I am still unclear on how to do this.
Is creating a ViewModel for the View in order to have the DataAnnotations a good solution? Is it OK to have double mapping: one in the feature and one in the presentation?

Or what solution would you recommend to support localization?

**Comment by ahmedatia** [comment]
Hello @Tbd19 ... I was going through the same and decided to go with [Localization](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization) using _a shared resource file_. I found this approach more easier than the use of additional ViewModels, DataAnnotations etc...

```
/// <summary>
/// Dummy class
/// </summary>
public class SharedResources
{
}
```

```
public interface ILocalizationService
{
        /// <summary>
        /// Gets a resource string based on the specified ResourceKey property.
        /// </summary>
        /// <param name="key">The resource key</param>
        /// <param name="arguments">The resource arguments</param>
        /// <returns></returns>
        string GetResource(string key, params string[] args);
}
```

```
public class LocalizationService : ILocalizationService
{
        private readonly IStringLocalizer _localizer;

        public LocalizationService(IStringLocalizerFactory factory)
        {
            _localizer = factory.Create("SharedResources", Assembly.GetExecutingAssembly().FullName);
        }

        public string GetResource(string key, params string[] args)
        {
            return args == null
                ? _localizer[key]
                : _localizer[key, args];
        }
}
```
And then you can inject `ILocalizationService` wherever needed to read resources values.

I hope this helps and would love to hear from others how they addressed it!

**Comment by shmutalov** [comment]
Good library for localization

https://github.com/VitaliiTsilnyk/NGettext

**Comment by Tbd19** [comment]
So should I understand that you are not using Html.LabelFor, Html.EditorFor and Html.XXXFor?
BTW my problem is not from where to take the resources. (I am already using a project that injects the localization service) My question is how to utilize the getting of resources in the context of using the Html.Label for that uses Display attribute.
Should I assume that you just write manually the <label> and <input> tags

**Comment by ahmedatia** [comment]
In the context of this template, I'm not using Display attributes at all. In fact, I've not used DataAnnotations with this template so far! I don't think it is needed especially with the use of localized resources and fluent validation.

In case of labels, you can still use `Html.LabelFor` as one of its parameters is `labelText` and hence in that case I'm passing the value of localized resources.

```
IHtmlContent LabelFor<TResult>(Expression<Func<TModel, TResult>> expression, string labelText, object htmlAttributes);
```

e.g.

```
@Html.LabelFor(c => c.Input, T.GetResource("ResourceKey"))
```

or like this in case of using the label tag helper (my preferred way)

```
<label asp-for="@Model.Input">@T.GetResource("ResourceKey")</label>
```

And for other inputs, I'm writing the tags manually with the help of built-in tag helpers or custom ones which take resource key as a parameter and it takes care of read of localized resource as well HTML element(s) rendering.

I hope this helps! What do you think?

**Comment by Tbd19** [comment]
It does help. So all the localization is done on the view and not on the view model with this type of template.

Thank you

**Comment by jasontaylordev** [comment]
Thanks all. ❤

**Comment by abdu292** [comment]
@ahmedatia Thanks for sharing as to how I did it. I was exactly looking for this.
Would you let me know where you keep each file, i.e; the interface, it's implementation and the resource resx files.?

I really appreciate your response. Sorry for asking on top of a closed ticket.

**Comment by ahmedatia** [comment]
@abdu292 Sure. I hope these two snapshots say it all.

![image](https://user-images.githubusercontent.com/670770/163972429-23cc0087-e6a8-4c4a-9a23-e29aee39fca9.png)
![image](https://user-images.githubusercontent.com/670770/163972830-76a3d135-11a4-4228-bc93-2e75276b17c3.png)

**Comment by ahmedatia** [comment]
@abdu292 Sure. I hope this screenshot says it all.

![image](https://user-images.githubusercontent.com/670770/163973741-2acc3619-e709-4323-9a92-15b0f046de3e.png)

**Comment by abdu292** [comment]
Yes it does. Thanks a bunch!
جزاك الله خيرا
