### ISSUE TITLE
Why does Application.IntegrationTests depend on WebUI?

### ISSUE THREAD

**Issue by FlaterF** [jasontaylordev/CleanArchitecture#189]
When setting up the service provider in the application integration tests, it uses the configuration from the WebUI.Startup class. I don't quite understand the reason why.

- Is this done purely to cut out some repeated code?
- Shouldn't the application integration tests be agnostic of its specific consumer? Why doesn't the Application.IntegrationTests project rely solely on the Application project, and thus the service configuration found in Application.DependencyInjection class?
- What should happen if there are two releaseable projects (e.g. WebUI and WinUI) which configure their services differently?

**Comment by ameyvaidya** [comment]
Yes, You can actually IntegrationTests that are not dependent on WebUI project. 

You can use `Microsoft.AspNetCore.Mvc.Testing` nuget package to write and assert test for integration test. It has `WebApplicationFactory `class that exposes methods `CreateDefaultClient `(among other methods) to test out API surface.

**Comment by nixonad** [comment]
Is the purpose of Integration tests not to test that all your services/modules etc are correctly integrated? Therefore we must test the configuration in Startup, otherwise our tests are not testing the setup that will be deployed.

**Comment by jasontaylordev** [comment]
I should probably rename the Application.IntegrationTests project to avoid confusion. The project contains subcutaneous tests and the goal is to exercise the production scenario as much as possible. For this, we need to wire-up all the services, and they are contained within Web UI. We are not testing the Web UI, just everything from the application layer and down.

If you're interested in learning more, please watch my video on Clean Testing; https://www.youtube.com/watch?v=2UJ7mAtFuio.
