### ISSUE TITLE
Any MassTransit Mediator example?

### ISSUE THREAD

**Issue by panosru** [jasontaylordev/CleanArchitecture#191]
Hello everyone,

**Not much of an issue, mostly a question** if there is an example of [MassTransit Mediator](https://masstransit-project.com/usage/mediator.html) implementation for this template.

I'm fairly new to .Net/C# and while I have successfully implemented MassTransit in my projects so far, I kind of stuck trying to modify [DependecyInjection.cs](https://github.com/jasontaylordev/CleanArchitecture/blob/master/src/Application/DependencyInjection.cs ) file from Application layer to use Mediator from MassTransit instead of MediatR.

I find MassTransit easier to integrate with RabbitMQ which I use since 2009, that's why I'm trying to use it with this template as well.

Thanks in advance!

## Update
The author of MassTransit ([@PhatBoyG](https://github.com/phatboyg)) was kind enough to [stream a video in Twitch](https://www.twitch.tv/videos/678888246) *(starting at 05:45)* [implementing](https://github.com/phatboyg/CleanArchitecture/tree/masstransit) MassTransit in CleanArchitecture template.

**Comment by MCCshreyas** [comment]
MassTransit is great library for building microservices as well. I love it.

**Comment by berkslv** [comment]
Twich stream is expried, it will be a good idea if anyone implement masstransit to template. Some events may come from masstransit directly and should be handeled by consumers.
