### ISSUE TITLE
After NPM Update can not build any more Angular App

### ISSUE THREAD

**Issue by danijel88** [jasontaylordev/CleanArchitecture#194]
Hello,
Today I had worked normally on solution on one moment I had run npm update, after that I can not build any more angular app
Can any one help me about this ?

```
ERROR in src/api-authorization/authorize.service.ts:52:5 - error TS2322: Type 'Observable<Profile>' is not assignable to type 'Observable<string>'.
  Type 'Profile' is not assignable to type 'string'.

52     return from(this.ensureUserManagerInitialized())
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
53       .pipe(mergeMap(() => from(this.userManager.getUser())),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
54         map(user => user && user.profile));
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/api-authorization/authorize.service.ts:82:29 - error TS2345: Argument of type 'Profile' is not assignable to parameter of type 'IUser'.
  Property 'role' is missing in type 'Profile' but required in type 'IUser'.

82       this.userSubject.next(user.profile);
                               ~~~~~~~~~~~~

  src/api-authorization/authorize.service.ts:34:3
    34   role: string;
         ~~~~
    'role' is declared here.
src/api-authorization/authorize.service.ts:93:31 - error TS2345: Argument of type 'Profile' is not assignable to parameter of type 'IUser'.

93         this.userSubject.next(user.profile);
                                 ~~~~~~~~~~~~
src/api-authorization/authorize.service.ts:119:29 - error TS2345: Argument of type 'Profile' is not assignable to parameter of type 'IUser'.

119       this.userSubject.next(user && user.profile);
                                ~~~~~~~~~~~~~~~~~~~~
src/api-authorization/authorize.service.ts:154:42 - error TS2339: Property 'data' does not exist on type 'SignoutResponse'.

154       return this.success(state && state.data);
                                             ~~~~
src/api-authorization/authorize.service.ts:199:5 - error TS2322: Type 'Observable<Profile>' is not assignable to type 'Observable<IUser>'.
  Type 'Profile' is not assignable to type 'IUser'.

199     return from(this.ensureUserManagerInitialized())
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
200       .pipe(
    ~~~~~~~~~~~~
201         mergeMap(() => this.userManager.getUser()),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
202         map(u => u && u.profile));
```

here is package.json
`{
  "name": "audit.webui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "echo Starting... && ng serve ",
    "build": "ng build",
    "build:ssr": "ng run Audit.WebUI:server:dev ",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.0.7",
    "@angular/common": "9.0.7",
    "@angular/compiler": "9.0.7",
    "@angular/core": "9.0.7",
    "@angular/forms": "9.0.7",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "9.0.7",
    "@angular/platform-browser-dynamic": "9.0.7",
    "@angular/platform-server": "9.0.7",
    "@angular/router": "9.0.7",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@nguniversal/module-map-ngfactory-loader": "8.0.0-rc.1",
    "@swimlane/ngx-datatable": "^17.0.0",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.6.5",
    "jquery": "^3.5.1",
    "ngx-bootstrap": "^5.2.0",
    "ng2-search-filter": "0.5.1",
    "ngx-pagination": "^5.0.0",
    "oidc-client": "^1.9.0",
    "popper.js": "^1.14.3",
    "rxjs": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.7",
    "@angular/cli": "9.0.7",
    "@angular/compiler-cli": "9.0.7",
    "@angular/language-service": "9.0.7",
    "@types/jasmine": "~3.3.9",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^5.0.9",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "typescript": "3.7.5",
    "webpack": "^4.43.0"
  },
  "optionalDependencies": {
    "node-sass": "^4.9.3",
    "protractor": "~5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}
`

**Comment by danijel88** [comment]
let me add update: I had fix some parts.
What I had found is that new oidc-client library do not support some stuff like 1.9.0 so I had moved this lib to this version.
Now I need to figure out why I'm seeing next error :
```
ERROR in node_modules/protractor/built/index.d.ts:5:10 - error TS2440: Import declaration conflicts with local declaration of 'PluginConfig'.

5 import { PluginConfig, ProtractorPlugin } from './plugins';
           ~~~~~~~~~~~~
node_modules/protractor/built/index.d.ts:5:24 - error TS2440: Import declaration conflicts with local declaration of 'ProtractorPlugin'.

5 import { PluginConfig, ProtractorPlugin } from './plugins';
```

**Comment by danijel88** [comment]
Ok, last update, I fix last issue with this link [https://github.com/angular/protractor/issues/5348](url)
Where I had downgrade typescript to 3.6.4

**Comment by jasontaylordev** [comment]
Thanks for sharing @danijel88, glad that you got it sorted. 👍
