### ISSUE TITLE
Adding Background Worker Project, then how to share interfaces in application layer

### ISSUE THREAD

**Issue by hassanrazakhalid** [jasontaylordev/CleanArchitecture#195]
Hi
I am using the clean template as starting point for my project. I also heard the talks on Clean architecture which were great on youtube. However i have one question. I need to have background worker to send notifications based some due date alone with usual web application. Worker will be background application and needs access to IDbContext and IDateTime both are defined in core in application layer according to template and there respective implementation are in Infrastructure. If i were to use IDbcontext and IDatetime then i will need to add a reference to Application since it defines the interfaces. Other solution is to make separate project and put all the application interfaces there. Then both Application and Worker project can reference it. Can some one please share the thoughts what is the best way while also following clean architecture principles. 
<img width="267" alt="Screen Shot 2020-07-22 at 2 19 58 AM" src="https://user-images.githubusercontent.com/15266641/88108225-eb001800-cbc1-11ea-8a0a-288bae4a0a4b.png">

**Comment by MCCshreyas** [comment]
From my point of view, Background Worker should be in the Application Layer because that holds some business logic. And as you mentioned you need `DbContext` interface, you can use as it is as this is available in Application layer.
