### ISSUE TITLE
Use GitHub Releases to Notify of New Versions

### ISSUE THREAD

**Issue by scottkuhl** [jasontaylordev/CleanArchitecture#198]
An easy way to follow along with the changes to this repo is to use the Watch button.  A full watch can be quite chatty at times.  I would like to suggest when new versions are pushed to NuGet you create a Release here in GitHub with notes on the change so we can subscribe to just Releases.

**Comment by jasontaylordev** [comment]
Hey Scott - hope all is going well. Agree, I really should use GitHub Releases. I'll keep it open as a reminder. Thanks. 👍
