### ISSUE TITLE
[Feature Request] Domain Events

### ISSUE THREAD

**Issue by scottkuhl** [jasontaylordev/CleanArchitecture#199]
We have added domain events to our application which is based on this solution template.  

Our domain events pattern provides for firing events as part of SaveChanges() in the database context that can participate in the same transaction.  

Alternatively, you can fire a domain event at any time.  For example, this provides for a case where you need to send an email message after the transaction is complete.   You would not want that message to go out during an open transaction and then have the transaction fail.

Is there interest in me creating a PR to integrate this into the template?

**Comment by rajasingh012** [comment]
I think it should be nice to include domain events in this template

**Comment by GFoley83** [comment]
Raising a domain event inside Save Changes is a bit limiting. I think a better strategy for domain events would be to add them as a post processor behaviour pipeline, as by then you know all logic in and around your handler has executed successfully.

**Comment by rajasingh012** [comment]
Thanks @GFoley83 , So it seems classes are always anemic, we can add logic in post processor behavior pipeline or mediatr Notification. Is that recommended practice?

**Comment by GFoley83** [comment]
Well what I've done in the past is both: a mediatr notification sent from a post processor behaviour pipeline. You can then have any number of classes in infrastructure listening to those events 
e.g. to add the event to a service bus or message queue, send an email etc.

**Comment by scottkuhl** [comment]
I'll put together a brach soon to show what we have.

I agree that the event firing in Save Changes has limits which is why we have both methods. But the Save Changes fire also provides for an easy way to keep events in the same transaction when needed.

Im looking forward to seeing what enhancements the community has based on these conversations.

**Comment by GFoley83** [comment]
>the Save Changes fire also provides for an easy way to keep events in the same transaction when needed.

Another strategy I've used in the past is to not expose `SaveChanges` to handlers at all (i.e. dont include a `SaveChanges` method on whatever interface you're injecting into your handlers for your `DbContext`) and instead call `SaveChanges` as part of a pipeline behavior e.g. as part of a Db transaction behavior pipeline. 

This can help insure that `SaveChanges` is only called when there are actually Db changes and also that it isn't being called multiple times within the same transaction. 

Of course, implementing something like this won't work for every scenario e.g. auto generated table Ids that get returned as part of the request response.

**Comment by scottkuhl** [comment]
I have a [fork going](https://github.com/scottkuhl/CleanArchitecture) with the first draft of my implementation.  This is the [first commit](https://github.com/scottkuhl/CleanArchitecture/commit/7314e44fc1af46ce55a93b2b63f2d05ee6e2d488).

I decided not to add transaction handling at least in this first draft.  Transaction handling is not currently in the solution template so I was concerned this would be adding too much.  I do have that built into our application so I can either add it or simply write something up on how to extend what is here.

There are two different ways to fire domain events.

1.  **During Save Changes.** This is based off Jimmy Bogart's [A Better Domain Events Pattern](https://lostechies.com/jimmybogard/2014/05/13/a-better-domain-events-pattern/).  This is a simple and straightforward way to attach events to the domain model that are fired when the object is persisted to the database.  Microsoft also has documentation on domain events with a similar implementation in the microservices architecture book in the section [Domain events: design and implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation).

2. **Independent of Persistence.** This one is based on Steve Smith's [Immediate Domain Event Salvation with MediatR](https://ardalis.com/immediate-domain-event-salvation-with-mediatr/).  It takes a different approach using a static method that lets you fire events at any time.

Some notable changes:

- This change is adding Mediator to the Domain project.
- The Events list must be ignored as part of the configuration.  I did this in the configuration classes because this fit the existing pattern.  I think this could be done for all classes in the OnModelCreating instead.

I look forward to feedback and discussion on this.

**Comment by Suhut** [comment]
> We have added domain events to our application which is based on this solution template.
> 
> Our domain events pattern provides for firing events as part of SaveChanges() in the database context that can participate in the same transaction.
> 
> Alternatively, you can fire a domain event at any time. For example, this provides for a case where you need to send an email message after the transaction is complete. You would not want that message to go out during an open transaction and then have the transaction fail.
> 
> Is there interest in me creating a PR to integrate this into the template?

can you give me example how to use your domain events ?
thanks

**Comment by scottkuhl** [comment]
In this example there are two ways a user account can be deactivated.  First is an application administrator does it through the user interface because you leave the department or company and the second is through a worker service that that detects that you have not logged in for a while.  

There is a Deactivated User Event that fires when an active user is deleted from the system or when the user is made inactive during an update.  Here is the delete command handler:  (similar but not identical logic would exist in the update)

```c#
public async Task<Unit> Handle(DeleteCommand request, CancellationToken cancellationToken)
{
    Guard.Against.Null(request, nameof(request));

    var entity = await _context.Users.FindAsync(request.Id);
    if (entity == null) throw new NotFoundException(request.Id, nameof(User));

    if (entity.IsActive)
        entity.Events.Add(new DeactivatedUserEvent(entity.Name, entity.EmailAddress));

    _context.Users.Remove(entity);
    await _context.SaveChangesAsync(cancellationToken);

    return Unit.Value;
}
```

The event handler then sends an email to the user letting them know their account is no longer active.

```c#

public class SendDeactivatedMessageHandler : INotificationHandler<DeactivatedUserEvent>
{
    ...
    /// mail stuff here
```

The event itself is just a container for parameters:

```c#
public class DeactivatedUserEvent : DomainEvent
{
    public DeactivatedUserEvent(string name, string emailAddress)
    {
        Name = name;
        EmailAddress = emailAddress;
    }
    public string EmailAddress { get; }
    public string Name { get; }
}
```

Now of course this could be done without an event handler and just call a method directly, but that provides a slightly tighter coupling.  The domain event pattern on the other hand can be harder to follow the flow the system.  So, it's a tradeoff.   But this example should give you an idea of its use case.

**Comment by Suhut** [comment]
> In this example there are two ways a user account can be deactivated. First is an application administrator does it through the user interface because you leave the department or company and the second is through a worker service that that detects that you have not logged in for a while.
> 
> There is a Deactivated User Event that fires when an active user is deleted from the system or when the user is made inactive during an update. Here is the delete command handler: (similar but not identical logic would exist in the update)
> 
> ```cs
> public async Task<Unit> Handle(DeleteCommand request, CancellationToken cancellationToken)
> {
>     Guard.Against.Null(request, nameof(request));
> 
>     var entity = await _context.Users.FindAsync(request.Id);
>     if (entity == null) throw new NotFoundException(request.Id, nameof(User));
> 
>     if (entity.IsActive)
>         entity.Events.Add(new DeactivatedUserEvent(entity.Name, entity.EmailAddress));
> 
>     _context.Users.Remove(entity);
>     await _context.SaveChangesAsync(cancellationToken);
> 
>     return Unit.Value;
> }
> ```
> 
> The event handler then sends an email to the user letting them know their account is no longer active.
> 
> ```cs
> public class SendDeactivatedMessageHandler : INotificationHandler<DeactivatedUserEvent>
> {
>     ...
>     /// mail stuff here
> ```
> 
> The event itself is just a container for parameters:
> 
> ```cs
> public class DeactivatedUserEvent : DomainEvent
> {
>     public DeactivatedUserEvent(string name, string emailAddress)
>     {
>         Name = name;
>         EmailAddress = emailAddress;
>     }
>     public string EmailAddress { get; }
>     public string Name { get; }
> }
> ```
> 
> Now of course this could be done without an event handler and just call a method directly, but that provides a slightly tighter coupling. The domain event pattern on the other hand can be harder to follow the flow the system. So, it's a tradeoff. But this example should give you an idea of its use case.

Big thanks

**Comment by MCCshreyas** [comment]
Good work @scottkuhl . But I am concern about one point, is that you're adding dependency of MediatR in 'Domain' project directly as I can see [here](https://github.com/scottkuhl/CleanArchitecture/blob/7314e44fc1af46ce55a93b2b63f2d05ee6e2d488/src/Domain/Domain.csproj)
One of the Clean architecture principles says that Domain should be clean and one should not depend upon any other library or framework. Domain should only contain POCO classes.

**Comment by scottkuhl** [comment]
@MCCshreyas Yes, that is true.  I did not like adding it, but I didn't see another way to handle it.  It is possible to put use the static version only and move the domain event class into the application layer but I'm not seeing an effective way to handle the save changes version without it.  In the end it seemed worth adding Mediator to the domain for the added functionality.

If you have another suggestion to remove the dependency, please let me know.

**Comment by MCCshreyas** [comment]
@scottkuhl Thanks for the reply. Yesterday only I did worked upon this on my fork! Here it is https://github.com/MCCshreyas/CleanArchitecture/commit/780e6d3b2827ca51ffa2abd7daf96a03b5d772a7

Right now if you see the implementation, I can have only one handler for one event, but I am working on having multiple handlers for an event, that handler might present in 'Domain' layer or in '	Application' layer, they both get called once the event gets raised.

After I saw your implementation to tackle the dependency of Meditr in 'Domain' I came up with this implementation!
Because CA's main principle is to keep domain clean, so that It can be shared across the different projects because it contains enterprise-wide logic. Having meditr there is kind not good from my point  of view!

**Comment by scottkuhl** [comment]
@MCCshreyas I like the way you used interfaces to remove the dependency on Mediator from the domain.

If one of the maintainers of the project would like to move forward with this, we can put together a PR and integrated your interfaces.

**Comment by MCCshreyas** [comment]
@scottkuhl Very thanks. My implementation is halfway done right now, I will ping here once I complete my feature implementation, then we will see how can get this forward.

**Comment by MCCshreyas** [comment]
Hi there @scottkuhl, I have completed my implementation of the domain events, I have changed the implementation to take advantage of `INotification<T>` without the dependency of 'Meditr' in Domain project with some help from [this ](https://cfrenzel.com/domain-events-efcore-mediatr/)blog post. Please check my latest commit - https://github.com/MCCshreyas/CleanArchitecture/commit/aecf258e665d83e7e14802dd575511b543bb3da8

Please let me know your thoughts and also changes on your fork if you think that we can have that here as well so that I can create PR for this!

**Comment by scottkuhl** [comment]
@MCCshreyas I have incorporated your changes which removes the domain dependence on MediatR and started a PR for the issue.  Thanks for the help.  Let's see what the maintainers think of our work.

https://github.com/jasontaylordev/CleanArchitecture/pull/217

**Comment by MCCshreyas** [comment]
@scottkuhl OK. Thanks. But right some more description content in PR, like how one should create new event, how to create event handler things like that. Please see my other PR to get idea. Along with feature idea, you should tell how one should take advantage of it.

**Comment by scottkuhl** [comment]
I didn't add any code comments because the current code base does not have them. I'm trying to follow the current standards.  But I do agree with you that the overall code base could use more in line documentation. It's possible that this is intentional because it's a solution template and every team has its own documentation standards.  In this case I am guessing what we ultimately will need to do is update offline documentation, or perhaps @jasontaylordev prefers to leave this for the conference videos and workshops.

**Comment by scottkuhl** [comment]
@MCCshreyas or are you referring to the description in the PR itself and not the code comments?

**Comment by MCCshreyas** [comment]
@scottkuhl correct. I am referring to PR description, I am not saying add comments in code, minimal comments are OK.
But as this is new feature, one should get some documentation about using it and right now we can provide it in PR. And maintainers will also read that, and get to know how to use it and if it's there any way to improve it, they will point out there itself, rather than self discovering.
See some my PR here - https://github.com/jasontaylordev/CleanArchitecture/pull/110 https://github.com/jasontaylordev/CleanArchitecture/pull/121

One of the advantage of this is if PR gets merged then we can include this in wiki as well.

**Comment by scottkuhl** [comment]
@MCCshreyas done.

**Comment by jasontaylordev** [comment]
Hi @scottkuhl and @MCCshreyas - thanks so much for your hard work! I've just merged the pull request now. I love the implementation, appreciate the contribution, and thanks for the descriptions. ❤
