### ISSUE TITLE
implementing a BulkInsert feature from EFCore.BulkExtensions

### ISSUE THREAD

**Issue by TheDonBenso** [jasontaylordev/CleanArchitecture#200]
I recently came across a project that requires me to insert transaction entries, 1000 transactions at a time. I came have been following the code template provided by Jason Taylor in his CleanArchitecture solution. 

In my attempt, I started by adding a function starting with a description in my interface IApplicationDbContext with the method BulkInsert(Entity). However, this wasn't working as I was hoping for and I'm still working on finding a good solution for it, I am hoping the community can assist in this as well. 

The bulk insert method comes from this NuGet **library  Install-Package EFCore.BulkExtensions**

**Comment by GFoley83** [comment]
This is a StackOverflow question.
