### ISSUE TITLE
Build SQL Db out of the box

### ISSUE THREAD

**Issue by maltbt** [jasontaylordev/CleanArchitecture#203]
**Describe the bug**
 I followed the instructions and expected to get a DB out of the box after running update-database command but I receive an error.

**To Reproduce**
1. "UseInMemoryDatabase": false,
2.dotnet ef migrations add "SampleMigration" --project src\Infrastructure --startup-project src\WebUI --output-dir Persistence\Migrations
3. update-database

**Expected behavior**
A successful build and create a DB in SQL explorer wit the name of CleanArchitecture.

**Screenshots**

![image](https://user-images.githubusercontent.com/45263852/89123202-84ce9b80-d4c5-11ea-96f2-2103ab59015a.png)

**Additional context**
PM> update-database
Build started...
Build succeeded.
Startup project 'src\Domain' targets framework '.NETStandard'. There is no runtime associated with this framework, and projects targeting it cannot be executed directly. To use the Entity Framework Core Package Manager Console Tools with this project, add an executable project targeting .NET Framework or .NET Core that references this project, and set it as the startup project; or, update this project to cross-target .NET Framework or .NET Core. For more information on using the EF Core Tools with .NET Standard projects, see https://go.microsoft.com/fwlink/?linkid=2034705

**Comment by ODumpling** [comment]
Hello @maltbt 

you do not need to run `update-database`.

The template has been setup to migrate at startup.

**Comment by jasontaylordev** [comment]
Hi @maltbt. It's correct that it will create the database (if it doesn't exist) and migrate at startup. Review WebUI/Program.cs for the implementation. 

When you ran the Update-Database command from the package management console need to change the default project to src\Infrastructure specify a few additional options relating to startup project and so on. I'd recommend not using the package management console. 

Instead, just using the .NET Core CLI and run this from the command line if you want to update the database without launching the project:

```bash
dotnet ef database update --project src\Infrastructure --startup-project src\WebUI
```

You need to run this command from the solution directory Anyway, hope this helps. 👍
