### ISSUE TITLE
WebAPI alternative to WebUI

### ISSUE THREAD

**Issue by ersenbasaransen** [jasontaylordev/CleanArchitecture#204]
It would be very nice to be an option for WebAPI instead of WebUI (just WebAPI without FrontEnd)

Some developers do use Vue, React instead of Angular. Also some developers develop the Front End app in a seperate solution, IDE etc. Also mostly Backend team iş seperated from the FrontEnd team.

I think there should be an option without the WebUI, just the WebAPI.

**Comment by nixonad** [comment]
It's relatively trivial to remove the UI references to have an API only project, this is how I use the template.

**Comment by ersenbasaransen** [comment]
> It's relatively trivial to remove the UI references to have an API only project, this is how I use the template.

Yes I do the same, but it must be trivial to put an option to generate the ui or not.

**Comment by jasontaylordev** [comment]
Agreed, I think I'll probably go that way soon.
