### ISSUE TITLE
Why use partial classes for some of the commands?

### ISSUE THREAD

**Issue by tafs7** [jasontaylordev/CleanArchitecture#205]
In browsing this codebase, I noticed that some (not all) of the command classes are defined as `partial class`.  Is there a reason for that? I did not find any other partial classes matching the existing ones, nor any code generators that might be adding to the partials.

There are 2 specific commands that are partials: `CreateTodoListCommand`, and `UpdateTodoItemCommand`.  The other commands are not partial, so it's inconsistent and not clear why.

Here's an example:
https://github.com/jasontaylordev/CleanArchitecture/blob/a5699983764391fba3d25ee69be92a83c2f9fefa/src/Application/TodoLists/Commands/CreateTodoList/CreateTodoListCommand.cs#L9

**Comment by MCCshreyas** [comment]
Hi @tafs7 . Thanks for pointing out. Seems like a typo, I guess. @jasontaylordev Any specific reason to have these commands partial?

**Comment by alcidesfmelof** [comment]
Good point. Noticed that as well.

**Comment by jasontaylordev** [comment]
They should be partial, no reason for that. I think it might have been added at some point as a result of refactoring. 

Regardless, thanks for pointing it out - all fixed.
