### ISSUE TITLE
usecase

### ISSUE THREAD

**Issue by hossy13** [jasontaylordev/CleanArchitecture#211]
hi
where is usecase directory ?

**Comment by rajasingh012** [comment]
Can you please elaborate why we need usecase directory. What is the purpose of it.

**Comment by MCCshreyas** [comment]
Hi @hossy13, seems like you mixing Hexagonal Architecture concepts with Clean architecture. You might want to take look at the Application Project in the template, where Commands & Queries mostly matched with Use cases!

**Comment by jasontaylordev** [comment]
Thanks @MCCshreyas
