### ISSUE TITLE
How to get User and Role information to application layer for a given user

### ISSUE THREAD

**Issue by Dishanx** [jasontaylordev/CleanArchitecture#212]
We want to get User and Role information to Application layer for a given user. I'm bit confuse with this code cz ApplicationUser is part of Infrastructure.

**Comment by GFoley83** [comment]
This question has been asked a few times; It's usually a good idea to search through issues before posting a new one.

User information is already accessible in the Application layer. Just inject `ICurrentUserService` into your handlers:
https://github.com/jasontaylordev/CleanArchitecture/blob/master/src/Application/Common/Interfaces/ICurrentUserService.cs
https://github.com/jasontaylordev/CleanArchitecture/blob/master/src/WebUI/Services/CurrentUserService.cs

If you need more info about the current user, just update `ICurrentUserService` and `CurrentUserService`.

For roles, see this comment for a working example:
https://github.com/jasontaylordev/CleanArchitecture/issues/56#issuecomment-638772812

Good luck.

**Comment by Dishanx** [comment]
@GFoley83 Thanks. But this project we don't use web front end and IdentityServer It's just an API with EF model first approch. We have to provide different API endpoints to customer to manage users and roles even for login. Right now all user management,password verification, jwt token logics implemented in Infrstrcuture layer. I'm thnking move it to application layer. What you think about that? what is the benifit of having Identity implementation in infastrcuture layer?  
By the way we heavily use AspNetCore.Identity libraries. 

Thank You.

**Comment by GFoley83** [comment]
I'm confused about what you're asking; is the solution you're currently working with built on this CleanArchitecture solution? 

The approach linked above supports everything you're talking about. This solution uses IdentityServer so did you take it out? 
The front-end is irrelevant as the API returns all the data needed. If you don't need the front-end then just delete the `ClientApp` folder. I suggest you checkout the solution above and see how close that get's you to where you need to be.

**Comment by Dishanx** [comment]
@GFoley83 Yes. I use CleanArchitecture template and deleted the ClientApp folder. Everything works fine except Identity. I'm not sure I can do everything what I need with IdentityServer(e.g: AD authentication)  But I'll check. If I create a new controller for user account management (CreateUser, AddRole, CreateADUser, ListAllUsers etc..)., do you think it's useful to keep Identity implementation in Infrastructure layer?

**Comment by GFoley83** [comment]
Yes you use IdentityServer to integrate with Azure AD. 
Creating new controllers and having identity implantation in the infrastructure layer have no correlation. Your concrete logic will be in the infrastructure layer but the interface will stay in the application layer.

**Comment by DishanH** [comment]
@GFoley83 Thanks.

**Comment by Dishanx** [comment]
@GFoley83 Thanks
