### ISSUE TITLE
Possible suggestion - Blazor Server App as another presentation layer 

### ISSUE THREAD

**Issue by mattkosmach** [jasontaylordev/CleanArchitecture#213]
Hello,

First of all, love the clean arhitecture, your templates, videos, code, ... Great job!

But, is it possible to add another project to the Presentation layer (Blazor Server App). 
If both (+ angular UI) are included in the template, developer could simply remove the redundant one. 

Or maybe someday you'll publish separate template intended for Blazor GUI?

I know it can be done/modified by individual, but still... 

Best regards, 

Matt

**Comment by KamranShahid** [comment]
Looking for same. Is it correct idea with using current architecture?

**Comment by jasontaylordev** [comment]
It's a good idea, I'd like to do this - maybe in the future. In the meantime, I can share two resources to help you get started:

1. https://www.youtube.com/watch?v=Oeh2IJw7Zig&t=2s
2. https://github.com/jasontaylordev/CleanArchitecture/tree/blazor (needs work)

Happy Coding. 👍

**Comment by KamranShahid** [comment]
Video looks concentrating on Blazor Webassembly while i am looking for Blazor Server Side with clean architecture. any way thanks Jason
