### ISSUE TITLE
Why the need to specify the Id in the Url as well as in the body in the command

### ISSUE THREAD

**Issue by M-Boukhlouf** [jasontaylordev/CleanArchitecture#214]
https://github.com/jasontaylordev/CleanArchitecture/blob/e1abd2eec1e55d00b0abeb49dd9f7285310ca26d/src/WebUI/Controllers/TodoListsController.cs#L36-L41

I think there is no need to specifiy the Id in the body when it's already specified in the Url. Instead of comparing if the Ids match, we can just set the Id in the command to the value of the Id in the Url.

**Comment by MCCshreyas** [comment]
As per REST convention, Id in body is optional, one should specify it in URL. But if in case one has supplied ID on both location, then it's API responsibility to check that both Id's (one in URL and one in body) should match otherwise return a BadRequest.

**Comment by M-Boukhlouf** [comment]
> As per REST convention, Id in body is optional, one should specify it in URL. But if in case one has supplied ID on both location, then it's API responsibility to check that both Id's (one in URL and one in body) should match otherwise return a BadRequest.

Thank you
