### ISSUE TITLE
What if the command has many properties?

### ISSUE THREAD

**Issue by M-Boukhlouf** [jasontaylordev/CleanArchitecture#215]
https://github.com/jasontaylordev/CleanArchitecture/blob/e1abd2eec1e55d00b0abeb49dd9f7285310ca26d/src/Application/TodoLists/Commands/CreateTodoList/CreateTodoListCommand.cs#L25-L29

What if the command has many properties? Is it advised to use AutoMapper to map the command to the entity?

**Comment by MCCshreyas** [comment]
Of course you can, because you're doing in Application Layer and that's OK to do it there.

**Comment by M-Boukhlouf** [comment]
> Of course you can, because you're doing in Application Layer and that's OK to do it there.

Thank you

**Comment by neman** [comment]
It is not recommended do use auto mapper from commands to domain model.
Avoid 2 way mapping.
https://lostechies.com/jimmybogard/2009/09/18/the-case-for-two-way-mapping-in-automapper/
https://enterprisecraftsmanship.com/posts/on-automappers/

Other guidelines by Jimmy Bogard:
https://jimmybogard.com/automapper-usage-guidelines/
