### ISSUE TITLE
Support for injecting DbcontextPool<T> in application layer

### ISSUE THREAD

**Issue by damikun** [jasontaylordev/CleanArchitecture#216]
It can be nice if you include support of DbcontextPool<DBcontext> in application layer...

From CQRS the application layer have only interface implementation of IDbContext which is in separate layer...  
 `DbContextPool<T>` require access to T as DBcontext object not interface...

Finding way to use DbcontextPool<T> inside application logic to keep layers dependency..

**Comment by jasontaylordev** [comment]
Closing stale issues.
