### ISSUE TITLE
VS Code support with this template

### ISSUE THREAD

**Issue by Sampath-Lokuge** [jasontaylordev/CleanArchitecture#22]
Hi,

Can I use the VS Code with this template? i.e. I would like to have 2 folders on VS code as one for Web API and Other for the Angular 8 project. Is this possible?

**Comment by JasonGT** [comment]
For sure, the solution works with your preferred IDE and .NET Core SDK, VS Code is perfectly fine.

Currently the solution uses the Angular SPA template, built in to .NET Core. You can read up on that template here; https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio. I've also written a blog post about it; http://www.codingflow.net/building-single-page-applications-on-asp-net-core-2-2/.

You will find that the template is just using the Angular CLI, and within the **ClientApp** folder is just a normal Angular 8 application. It is already quite separate, in that you can delete the contents of the **ClientApp** folder and replace it with another Angular CLI app and it will work just fine. 

If you want to separate it out further, got right ahead. Dependent on your approach you might need to configure CORS and adjust some settings within `Startup`. I have done this before so if you do, please share the steps. 😄
