### ISSUE TITLE
Any plan to upgrade to Angular 10 and .scss

### ISSUE THREAD

**Issue by marinehero** [jasontaylordev/CleanArchitecture#223]
Are there any plans to upgrade to Angular 10 and using .scss?

Now that it's been out for a while , would be nice that the template generates accordingly.

**Comment by jasontaylordev** [comment]
I've upgraded to Angular 10 - https://github.com/jasontaylordev/CleanArchitecture/commit/4766a1be31b628888cfce293c5d3356bd59b57be.

If someone would like to submit a PR for the upgrade to SCSS that would be appreciated. 😊

**Comment by jasontaylordev** [comment]
All done. 😊
