### ISSUE TITLE
Clean Architecture - .NET 5

### ISSUE THREAD

**Issue by Masherak** [jasontaylordev/CleanArchitecture#225]
Do you plan to port this amazing Clean Architecture to the .NET 5 ? Also in a preview version? Can we expect some significant changes?

**Comment by MCCshreyas** [comment]
I don't think so, we will some significant changes other than just package version number changes to V5.

**Comment by Masherak** [comment]
Clear, thank you very much for your answer.

**Comment by jasontaylordev** [comment]
Hi @Masherak Masherak, thanks for your question. I will upgrade to .NET 5 as soon as it hits RTM. I've found that attempting an upgrade before then is very frustrating, and best avoided. 😊

**Comment by litan1106** [comment]
.NET 5 released today.

**Comment by litan1106** [comment]
.NET 5 also had built in support for swagger / openapi with Swashbuckle.

https://www.davidhayden.me/blog/openapi-and-swagger-ui-in-asp-net-core-5-web-api
