### ISSUE TITLE
Question: How to implement BeginTransactionAsync in IApplicationDbContext?

### ISSUE THREAD

**Issue by GhorbaniAli** [jasontaylordev/CleanArchitecture#228]
I want to add `_dbContext.Database.BeginTransactionAsnyc` to Behaviours, but IApplicationDbContext doesn't have `DatabaseFacade Database { get; }` . Does anyone know how to do it? or does this template still not support this?

**Comment by AliGhIO** [comment]
I add `DatabaseFacade Database { get; set; }` to `Application.Common.Interface.IApplicationDbContext`. Is this the right way?

**Comment by andrewboudreau** [comment]
Hey AliGhIO, I've been exploring something similar but using a idea similar to how [eShopContainers transaction management behavior](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs) works. That eshop project has a lot of moving parts and [the reference docs] (https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections) speak to a pretty specific use case but I think there is some really good ideas here that can be distilled and applied to this template.  I'm not working on a solution for this template but am exploring similar ideas.

Regarding your approach, it is straightforward but may leak "database" which is likely seen as an infrastructure concern to the application interface. In many projects in the past I've found this to be useful but can blur the boundaries.

**Comment by AliGhIO** [comment]
Hey Andrew, Thank you for your time and guidance.
I did a thorough review and it was very useful, but this operation is not required for all requests and needed only for requests that lead to changes in the database. Do you have a solution to this problem?

> Hey AliGhIO, I've been exploring something similar but using a idea similar to how [eShopContainers transaction management behavior](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs) works. That eshop project has a lot of moving parts and [the reference docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections) speak to a pretty specific use case but I think there is some really good ideas here that can be distilled and applied to this template. I'm not working on a solution for this template but am exploring similar ideas.
> 
> Regarding your approach, it is straightforward but may leak "database" which is likely seen as an infrastructure concern to the application interface. In many projects in the past I've found this to be useful but can blur the boundaries.

**Comment by ecasperlk** [comment]
Hi AliGhiO, how did you overcome this and implement Transactions management into mediator pipe line? Your response is much appreciated!

**Comment by AliGhIO** [comment]
Hey @ecasperlk,
I implement database transactions using Pipeline behaviour. Look at this file [eShopContainers transaction management behaviour](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs).
But I still could not find a solution to the problem that transactions are not always necessary and I am looking for a solution to this issue and I hope someone help me ☺. @jasontaylordev 

> Hi AliGhiO, how did you overcome this and implement Transactions management into mediator pipe line? Your response is much appreciated!

**Comment by ecasperlk** [comment]
> Hey @ecasperlk,
> I implement database transactions using Pipeline behaviour. Look at this file [eShopContainers transaction management behaviour](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs).
> But I still could not find a solution to the problem that transactions are not always necessary and I am looking for a solution to this issue and I hope someone help me ☺. @jasontaylordev
> 
> > Hi AliGhiO, how did you overcome this and implement Transactions management into mediator pipe line? Your response is much appreciated!

It doesn't make any sense to add a transaction Pipeline at each transaction, I believe EF Core already does it. I'm also looking for a way to add it for a specific case.

**Comment by andrewtsw** [comment]
Hi @AliGhIO 
The main question for me is now "how". It is "why"?
Why do you need manual transaction management? 
EF implements the UoW pattern. So you can use `SaveChanges` and no need for any transaction management.

**Comment by AliGhIO** [comment]
Hi @andrewtsw,
Yes, but the point is, what should I do if I want to cancel the transaction based on the terms? `RollbackTransaction`

**Comment by AliGhIO** [comment]
> > Hey @ecasperlk,
> > I implement database transactions using Pipeline behaviour. Look at this file [eShopContainers transaction management behaviour](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.API/Application/Behaviors/TransactionBehaviour.cs).
> > But I still could not find a solution to the problem that transactions are not always necessary and I am looking for a solution to this issue and I hope someone help me ☺. @jasontaylordev
> > > Hi AliGhiO, how did you overcome this and implement Transactions management into mediator pipe line? Your response is much appreciated!
> 
> It doesn't make any sense to add a transaction Pipeline at each transaction, I believe EF Core already does it. I'm also looking for a way to add it for a specific case.

I don't think this method add a transaction pipeline for each transaction. 🤔 This will open pipeline for **each request**.

**Comment by marcoatribeiro** [comment]
> Hi @andrewtsw,
> Yes, but the point is, what should I do if I want to cancel the transaction based on the terms? `RollbackTransaction`

I'm looking for a similar solution and I also think this makes sense for transactions which deal with different aggregate entities using domain events.

Personally I like the idea of adding `DatabaseFacade Database { get; set; }` to `Application.Common.Interface.IApplicationDbContext`, but I agree with @andrewboudreau the name may be misleading in terms of mixing up concerns. Maybe _Storage_ or some other name would be better indeed. 
Please let me know your thoughts.

**Comment by andrewtsw** [comment]
Sorry, but could you provide more details - why do you need this rollback operation?
EF Core implements Unit Of Work. 
So you have to call SaveChanges only once.
I believe it is easier to check all conditions before call SaveChanges. And if you can not commit all changes - do not call SaveChanges.
It is easier then call SaveChanges multiple times and manually manage transactions.
Does it works for you?

**Comment by ecasperlk** [comment]
> EF Core implements Unit Of Work.
> So you have to call SaveChanges only once.

@andrewtsw this works for 99% of the time but transactions related to indenity is the issue.

**Comment by andrewtsw** [comment]
@ecasperlk 
I believe it depends on identity implementation.
Do you use a separate DB context for identity?

**Comment by jasontaylordev** [comment]
Within Application, create an interface to represent this special case. Define it in terms of the business, with necessary inputs and outputs. 

Within Infrastructure, create a new service to implement this interface. The service will contain the necessary transaction management and logic. It can interact directly with identity and the DbContext.

Simply inject the interface into the relevant comment and invoke when necessary.

Hope this helps, happy coding! 😀
