### ISSUE TITLE
Feature Request: Blazor Presentation Layer

### ISSUE THREAD

**Issue by MaherJendoubi** [jasontaylordev/CleanArchitecture#23]
Dear Jason,

For Blazor, there are 2 hosting model choices that could affect the architecture : 

![image](https://user-images.githubusercontent.com/1798510/70615320-749f3e80-1c0c-11ea-82c9-e0396dfb0300.png)

**Comment by AnassL** [comment]
Great idea !!

**Comment by JasonGT** [comment]
Just this week I was talking to my good friend @jernejk (JK) about implementing Blazor for this solution. Clearly we will need to think about the approach, but he had some good ideas. JK (and others) if you have some time, could you please provide suggestions for recommended approach?

**Comment by AnassL** [comment]
An awesome thing would be to insert in the architecture a new Blazor project which would act as client app, and let the current server side as it is. With Balzor you can share classes between the server side and the client side, with Typescript you needed to duplicate every class you are using, Blazor eliminates this need. I've heared people saying that a complete Blazor Client side will be available in May 2020, but you can see on the web that peopel are impressed and they already started some attempts.

**Comment by jernejk** [comment]
I agree, @AnassL.

Personally, I'm using client-side Blazor hosted on GitHub pages + Azure Functions on a few pet projects, where I don't need much server-side logic. You can already use it, however, it's still in the early stages and I wouldn't recommend it for production until May 2020.

I used server-side Blazor on a pet project and it's interesting, however, I find client-side Blazor more interesting, while server-side Blazor is more practical. (being stable and faster)

Finding the right architecture for Blazor has been a journey for me and I'm looking forward to a really deep dive on this topic with @JasonGT. :)

**Comment by davidhenley** [comment]
All your API responses can be put in a separate project that is referenced by the application and blazor layers

**Comment by AnassL** [comment]
@davidhenley can you please elaborate a bit more ? I am sorry, didn't get your point.

**Comment by davidhenley** [comment]
@AnassL You can share code between your Blazor client and your API so it makes sense to put your contracts/dtos/request and response models in a separate assembly that both can reference

**Comment by hypervtechnics** [comment]
@davidhenley Or maybe generate an api client using NSwag and MSBuild? This would make Blazor really just "a client" for the API instead of having to restructure the API part.

**Comment by achmstein** [comment]
What about using gRPC as the API for the Blazor client?

**Comment by jasontaylordev** [comment]
@jernejk  and I did some work on this - https://github.com/jasontaylordev/CleanArchitecture/tree/blazor. It is a work in progress but the basics are in place. Including API client generation with NSwag and MSBuild!

Closing as I am not planning to progress further at this stage. If I build new clients it will most likely be React and/or Vue.
