### ISSUE TITLE
Mediator - Commands - Passing and validating relations

### ISSUE THREAD

**Issue by beefcake123** [jasontaylordev/CleanArchitecture#230]
Hello,

I hope this is the correct forum to ask, as this isn't really a feature request or bug. From analyzing the `CreateTodoItemCommand` I assumed it's good practice to never pass an related object to a Command, but rather add the Id to the `Request`.

But now I find myself writing the nearly identical code at the start of my Request handler, in the format off:
```
            var domainObject = await _context.MyDbSet.FirstOrDefaultAsync(x => x.Id == request.RelationId);
            if(domainObject == null)
            {
                throw new NotFoundException("DomainObject with id : "  + request.RelationId+ " not found.");
            }
```

- The easiest solution would be to move this logic to a 'Helper' class in my Application layer. 

- Via reflection & generics, I could probably make it into one Helper-method

- But I just feel like I'm missing something, and all this code perhaps isn't necessary?

A concrete example:

```
            var classList = await _context.ClassLists.FirstOrDefaultAsync(x => x.Id == request.ClassListId);
            if(classList == null)
            {
                throw new NotFoundException("Classlist with id : "  + request.ClassListId + " not found.");
            }
            var teacher = await _context.Teachers.FirstOrDefaultAsync(x => x.Id == request.TeacherId);
            if(teacher == null)
            {
                throw new NotFoundException("Teacher with id: " + request.TeacherId + " not found.");
            }

           obj j = new MyObject();
           j.Teacher = teacher;
           ClassList.Add(j);
            await this._context.SaveChangesAsync(cancellationToken);
```

**Comment by jasontaylordev** [comment]
The recommended approach is that each command or query represents a unique business use case. While the code may be similar, it is not a violation of DRY, in that the use cases are unique. This provides the advantage the use cases can be maintained independently without the chance of breaking changes, e.g. you change one use case and accidently break three others.

You could use [guard clauses](https://github.com/ardalis/GuardClauses) to simplify the above code:

```csharp
var classList = await _context.ClassLists.FirstOrDefaultAsync(x => x.Id == request.ClassListId);
Guard.Against.NotFound(classList, request.ClassListId);
    
var teacher = await _context.Teachers.FirstOrDefaultAsync(x => x.Id == request.TeacherId);
Guard.Against.NotFound(teacher, request.TeacherId);

var j = new MyObject();
j.Teacher = teacher;
classList.Add(j);

await this._context.SaveChangesAsync(cancellationToken);
```

However, if this specific logic is required to support many use cases you can refactor this logic into the domain:

```csharp
var classList = await _repository.GetById(request.ClassListId);
Guard.Against.NotFound(classList, request.ClassListId);

classList.AddTeacherById(request.TeacherId);

await _unitOfWork.SaveChangesAsync(cancellationToken);
```

For this simple example there is minimal improvement. However for a complex domain model, encapsulating domain logic in this way will result in less code and ensure that logical requirements are not duplicated.
