### ISSUE TITLE
[Question] Should we add generic response to the project?

### ISSUE THREAD

**Issue by iayti** [jasontaylordev/CleanArchitecture#233]
Hi there, 👋

If I just use the project for web api, should we add generic response according to clean architecture criteria? 

You can see the examples below as pseudo code. I just added it to give an idea.

I am waiting for your opinion.

Generic Response Class Example:

```csharp
public class ServiceResult<T>
{
     public T Data { get; set; }

     public bool Succeeded { get; set; }

     public ServiceError Error { get; set; } // Identifying the error message
}
```

Response Example:

```csharp

return ServiceResult.Succeeded<TodoListDto>(list);

return ServiceResult.Failed(ServiceError.NotFound);

````

**Comment by rafaelfgx** [comment]
Hi,

I really like the Result Pattern approach, I use it a lot in my projects:

```cs
public async Task<IResult> UpdateAsync(CustomerModel model)
{
    var validation = await new UpdateCustomerModelValidator().ValidationAsync(model);

    if (validation.Failed)
    {
        return Result.Fail(validation.Message);
    }

    var customer = _customerFactory.Create(model);

    await _customerRepository.UpdateAsync(customer.Id, customer);

    await _unitOfWork.SaveChangesAsync();

    return Result.Success();
}
```

I believe this way the execution flow is very easy to be understood and avoids side effects.

It is my opinion based on my experience and knowledge, there is no right or wrong in this case.

I would also like to congratulate you for sharing knowledge with the community! Go on!

**Comment by jasontaylordev** [comment]
You certainly can, you just need to decide if it is normal for the request to fail. If so, the failure would be handled and easily reported back using the result class. 

It would be great to add an example of this to the template, I'll add it to the list. 

In the meantime, Ardalis has created a nice implementation here; https://github.com/ardalis/Result.
