### ISSUE TITLE
[Question] Blazor Server, Mediator and Entity Framework Core Design Issue

### ISSUE THREAD

**Issue by scottkuhl** [jasontaylordev/CleanArchitecture#234]
We have run into an issue in our application that is crashing the site: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext.

Which lead me to this article: [ASP.NET Core Blazor Server with Entity Framework Core (EFCore)](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core).  The recommended approach is to create a DbContextFactory, which is then demonstrated like this:

```
    using var context = DbFactory.CreateDbContext();
    var contact = await context.Contacts.FirstAsync(c => c.Id == Wrapper.DeleteRequestId);
```

Using the clean architecture pattern the code would like more like this:

``` 
    var contact = await Mediator.Send(new GetContact());
```

The GetContactHandler's constructor would then receive the context through dependency injection.  I could change the GetContactHandler to receive an IDbContextFactory instead but I don't always want to new up a new context.  I think only the Blazor server interface should care about this problem and the deeper layer's should not be adjusted to accomodate it.

**What is the recommended way to handle this Blazor Server-Side concern with the Clean Architecture solution template?**

**Comment by MCCshreyas** [comment]
I don't think so having `IDbContextFactory` in the constructor, DI will provide a new context every single time. If the object is in the pool, then that will get served. And also, by default, the context gets registered as a scoped lifetime.

**Comment by jasontaylordev** [comment]
Closing this issue as it is stale and the template does not use Blazor.
