### ISSUE TITLE
[Question]Where should I install redis and what logic follow using redis on Clean Architecture on API

### ISSUE THREAD

**Issue by amilcar-dev** [jasontaylordev/CleanArchitecture#247]
I want to implement redis on an API using Clean Architecure. Can you help me
Thanks a lot

**Comment by MCCshreyas** [comment]
Redis for caching or save data purposes?

**Comment by amilcarvalho-dev** [comment]
> Redis for caching or save data purposes?

Its for caching. Thanks

**Comment by MCCshreyas** [comment]
You can take a look at my PR for implementation idea.
https://github.com/jasontaylordev/CleanArchitecture/pull/110

**Comment by amilcarvalho-dev** [comment]
> You can take a look at my PR for implementation idea.
> #110

Thanks a lot @MCCshreyas

**Comment by furkandeveloper** [comment]
Hi @amilcarvalho-dev .I developed library for cache operations. This library of about see for more information. [EasyCache](https://github.com/furkandeveloper/EasyCache) 

I have implemented this library for CleanArchitecture and opened PR.
You can use Redis, MemoryCache or Memcache by reviewing this PR.
[EasyCache PR](https://github.com/jasontaylordev/CleanArchitecture/pull/292)

**Comment by jasontaylordev** [comment]
Thanks all
