### ISSUE TITLE
IApplicationDbContext 

### ISSUE THREAD

**Issue by mfatihkc** [jasontaylordev/CleanArchitecture#248]
How can I use Database query on Application Layer?
the interface does not have the application context, please help me?
```

SqlParameter category = new SqlParameter("@CategoryName", "Test");
await context.Database.ExecuteSqlCommandAsync("NewCategory @CategoryName", category);
```

Thank you

**Comment by iayti** [comment]
I do not recommend using sql query in the application layer. If you want to use your ORM model, you have to do it in the Infrastructure layer. The current version uses the entity framework core. You can add [Dapper](https://github.com/StackExchange/Dapper), [RepoDB](https://github.com/mikependon/RepoDB) or your own ORM model.

**Comment by Sokoo92** [comment]
> I do not recommend using sql query in the application layer. If you want to use your ORM model, you have to do it in the Infrastructure layer. The current version uses the entity framework core. You can add [Dapper](https://github.com/StackExchange/Dapper), [RepoDB](https://github.com/mikependon/RepoDB) or your own ORM model.

Why not? As the per the template all queries and commands reside in the application layer, you inject the IApplicationDbContext through the constructor in your Command/QueryHandler?

**Comment by mfatihkc** [comment]
Yes I want to inject IApplicationDbContext, but ApplicationDbContext use interface on the infrastructure layer

![image](https://user-images.githubusercontent.com/11229204/96166898-46bf1080-0f27-11eb-8ecb-c2fe684b9377.png)
![image](https://user-images.githubusercontent.com/11229204/96166950-59394a00-0f27-11eb-8836-f967c0829254.png)
![image](https://user-images.githubusercontent.com/11229204/96167001-69e9c000-0f27-11eb-8d30-da64d769aa21.png)

**Comment by neman** [comment]
Because IApplicationDbContext is abstraction over database. It is using EF core for any database. If you are using specific queries in Application you have leaking of infrastructure.

**Comment by Sokoo92** [comment]
> Because IApplicationDbContext is abstraction over database. It is using EF core for any database. If you are using specific queries in Application you have leaking of infrastructure. 

So Jason Taylor is wrong for putting his queries in the application layer then?

**Comment by mfatihkc** [comment]
How can I call store procedure then?

**Comment by iayti** [comment]
> > Because IApplicationDbContext is abstraction over database. It is using EF core for any database. If you are using specific queries in Application you have leaking of infrastructure.
> 
> So Jason Taylor is wrong for putting his queries in the application layer then?

Application queries are not a custom sql query. We are using EF ccore in the application layer. If you want to use ADO.NET, you can use wherever you want but, creating custom ORM model in the Infrastructure Layer is a better solution.

**Comment by jasontaylordev** [comment]
The simplest approach would be to add a new method to IApplicationDbContext (Application layer) that is implemented by ApplicationDbContext (Infrastructure layer). The new method can call a execute a query or procedure and return the result. Using this approach your Application layer will remain independent of the database. 

There are many other approaches, but as others have advised, keep the raw SQL queries and stored procedure names out of the Application layer. The system should be independent of the database.
