### ISSUE TITLE
[Question] What is a good choice to execute a complex query by ef core?

### ISSUE THREAD

**Issue by trungcaot** [jasontaylordev/CleanArchitecture#249]
In ef core, we want to execute a complex query that is joined from many tables and then return a new object.
 
Currently, I'm going to define an object to mapping with domains and use dbContex.[Sepecific Db Set].FromSql("") to run it.

Ex: the following example for a simple query, we can join with Category table to get CategoryName or something like that.
`
var books = context.Books
        .FromSql("SELECT * FROM Books")
        .Select(b => new {
            BookId = b.BookId,
            Title = b.Title 
            }).ToList();
`

Can I use the above way to do it? or you know a new way to do it better, pls share it with me. Thanks.

**Comment by workcontrolgit** [comment]
For complex queries, consider stored procedures instead.  To see how to work with Stored Procedure in Entity Framework Core, visit https://www.entityframeworktutorial.net/efcore/working-with-stored-procedure-in-ef-core.aspx
