### ISSUE TITLE
Update the code so that dependencies in filters can be resolved

### ISSUE THREAD

**Issue by NagarjunaAddanki** [jasontaylordev/CleanArchitecture#250]
**Is your feature request related to a problem? Please describe.**

Currently dependencies in filters cannot be resolved because of the way they are added in the ConfigureServices class.

**Describe the solution you'd like**

Instead of using 
**options.Filters.Add(new ApiExceptionFilterAttribute()))**
Use
**options.Filters.Add< ApiExceptionFilterAttribute > ())**

So that any dependencies like ILogger can be injected into exception filters.

**Comment by jasontaylordev** [comment]
Thanks
