### ISSUE TITLE
[Question] Adding Secret, IdentityResources and new Scopes to Client

### ISSUE THREAD

**Issue by erkinyldz** [jasontaylordev/CleanArchitecture#252]
I have been digging around for a while but I could not find a way to;
- Add a secret or change to existing one.
- Add new IdentityResources 
- Add new AllowedScopes

Can anyone point me into right direction?

**Comment by workcontrolgit** [comment]
The Microsoft documentation "[Introduction to Identity on ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)"  refers to IdentityServer4 to provide robust access control to APIs.  The IdentityServer4 documentation has sample code to configure client, resource, scope via C# inline code, or specifying settings in appsettings.json.  A better way is to use the opensource project [Admin UI](https://github.com/skoruba/IdentityServer4.Admin).  With the admin ui, you can use the web interface to register clients, apiresources, manage scopes/claims, and the identity (user/roles).   I created a [series of tutorial](https://medium.com/scrum-and-coke/devkit-webapi-security-d7a45e34a5cd?source=friends_link&sk=d995ee034b01e79077b77925e5bae1b2) on this topic.   If the project has been generated using the CleanArchitecture template, some refactoring is needed to work with the IdentityServer4.   You can find an example code in the repo [here](https://github.com/workcontrolgit/Self-Order-System).
