### ISSUE TITLE
how to generate token

### ISSUE THREAD

**Issue by farshidtorkaman** [jasontaylordev/CleanArchitecture#254]
hi. which endpoint should I call for generating token.
I want an action that has username and password parameter.
I should create that or is there somewhere in project?

**Comment by workcontrolgit** [comment]
Assume your project runs on https://localhost:44312/

- Which endpoint should I call for generating token
The endpoint to generate token is https://localhost:44312/connect/token

For other well-known endpoints, go to https://localhost:44312/.well-known/openid-configuration

- I want an action that has username and password parameter.
For oAuth2 login, the endpoint is https://localhost:44312/connect/authorize

- I should create that or is there somewhere in project?
Check MS documentation [Migrate Authentication and Identity to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-3.1)

**Comment by farshidtorkaman** [comment]
thank you very much for your help

**Comment by rajasingh012** [comment]
- If I call https://localhost:44312/connect/token , it returns {"error": "invalid_request"}.Is there any thing I need to configure
- Also, If I call https://localhost:44312/connect/authorize, it redirected to error page, then comes to Index page, Is there any configuration missing. 

I am using sql server as database
