### ISSUE TITLE
Optimistic concurrency control example

### ISSUE THREAD

**Issue by NickLydon** [jasontaylordev/CleanArchitecture#255]
It would be nice to see an example implementing optimistic concurrency control (ideally at the aggregate root level). 
What I have trouble with is automatically retrying the process. Ideally I'd like to just:

1. Reload the entities
2. Re-validate. If it's no longer valid, return an error or throw a different exception
3. Try to save the changes. If there's a concurrent update, go to step 1. 

The difficulty comes from the context caching the values from the database, so in step 1. you need to re-create the context.
I thought this was a standard technique (used it successfully with mongo), but haven't yet found an example of anyone doing this with entity framework core.

**Comment by iayti** [comment]
If I don't get it wrong, we're talking about [the example here.](https://docs.microsoft.com/tr-tr/ef/core/saving/concurrency) The values to be changed are given in the example, but I find it better to send the error directly and retry the process with a retry policy. It would be very useful if we could add this solution globally to the context. I don't know if anyone did it before, but I didn't come across.

**Comment by NickLydon** [comment]
Yes that's the kind of thing I'm talking about. The easiest thing would be to create a new context on each retry, but normally it's resolved once per web request from the dependency injection container. I don't know how you'd ensure all your components are accessing the same context, unless you pass it explicitly as a method argument 😕

**Comment by jasontaylordev** [comment]
Apologies, this is not something I am looking to demonstrate as part of this template.
