### ISSUE TITLE
[Question] : What's the best way of implementing many to many relationship by using IEntityTypeConfiguration?

### ISSUE THREAD

**Issue by farhanchew** [jasontaylordev/CleanArchitecture#256]
Hi everyone, First of all, sorry if it's a silly question. I'm quite new here.

I have a situation to add Many-to-many relationship as per official documentation below: 
https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#many-to-many

Based on the above documentation, the configuration is done at the OnModelCreating method.
I was trying to get it done in the Entity Configuration but here's the error I got into: 
![image](https://user-images.githubusercontent.com/42090827/97802963-e566a380-1c81-11eb-83e4-13af6d9582f3.png)

Hope someone can assist this matter. Thanks in advance!

**Comment by Antister** [comment]
u need to add: .UsingEntity(j => j.ToTable("NameOfTable"))

**Comment by farhanchew** [comment]
> u need to add: .UsingEntity(j => j.ToTable("NameOfTable"))

I don't see any option .UsingEntity in the EntityTypeBuilder<T> builder.
I have created the bridge table and some additional properties.
However I managed to solved it by using the following method:
![image](https://user-images.githubusercontent.com/42090827/97807842-2d93bf00-1c9e-11eb-9841-6de7c8381543.png)
