### ISSUE TITLE
How to mock external services

### ISSUE THREAD

**Issue by Tbd19** [jasontaylordev/CleanArchitecture#258]
I have an external service that I do not want to test and would like to be mocked.

Using this architecture is there an example on how to handle this?

**Comment by amattias** [comment]
Since a dependency injection pattern is used, you can simply create an "fake"-implementation of the interface you define for your service that does the external integration and use it in your tests. 

There are also some mock-examples in the `Testing.cs` class in the `RunBeforeAnyTests()` method

**Comment by Tbd19** [comment]
In the Testing there is not really an example of what I want cause the "fake" there are only to return on all tests the same thing.

I need an example for instance for an interface that has the following signature:  <object> Method(<object> param1, <object> param2).

And I need that in some tests the Method to return a specific "object", in other tests the Method to return other "object" and even in some tests I need it to throw an exception.

Since the _scopeFactory is a static object how can I "fake" an interface to behave differently on tests?

**Comment by amattias** [comment]
Cant you make an specific test-implementation of the service that constructs the object you expect for each case depending on the input data?

**Comment by Tbd19** [comment]
But how to do this since in my test I only create the command object and use the mediator to send the command.

Are you saying that I have to create a similar method SendAsync in Testing.cs and in that method I should replace my interface?

So this architecture is not suitable for this case.

**Comment by amattias** [comment]
Since dependency injection is used you have full control.

Let's say you have an interface for your external service called IExternalService and an implementation called ExternalService that does the real communication.

If you then create something like FakeExternalService that does exactly what you want for the tests. Then you could make your tests use that implementation by doing something like the following in Testing.cs

```csharp
// Remove existing service registration for IExternalService
var externalServiceDescriptor = services.FirstOrDefault(d => d.ServiceType == typeof(IExternalService));

services.Remove(externalServiceDescriptor);

// Add service registration for IExternalService
services.AddSingleton<IExternalService, FakeExternalService>()
```

Then all of your code that takes an injected IExternService will use the FakeExternalService when running tests.

**Comment by Tbd19** [comment]
Oh, I have to modify the RunBeforeAnyTests but this means that my FakeExternalService is not test dependent but rather has to behave the same for all tests.

Also if the interface method has no parameters there is no way to tell it to behave differently. So multiple TestFixture have to be defined.

So my statement stands: "this architecture is not suitable for this case"

**Comment by jasontaylordev** [comment]
Hi @Tbd19 - the Application.IntegrationTests project really just contains subcutaneous tests. Perhaps I should rename the project to something else to avoid confusion. The idea is to configure the services to be as close to production as possible. The tests that run will all operate using the same services. These tests should be lightweight and test only the basics, not necessarily all cases.

So while it's certainly possible to configure a fake implementation for your external service, as you have mentioned it is not simple to configure alternative fakes for different testing scenarios. I'd suggest creating a separate test project when you want test with differently configured fakes.

Hope this helps.

**Comment by utkarsh24** [comment]
Can these scenarios be tested in Unit test projects, or you are suggesting an Integration Test project.?
