### ISSUE TITLE
How to use CleanArchitecture with MySQL Database

### ISSUE THREAD

**Issue by rmichaelbics** [jasontaylordev/CleanArchitecture#260]
I have been trying to use CleanArchitecture in my project with the MySQL database, but It keeps throwing error messages.

I would like to know, how easy is that to change the database from MSSQL to MySQL and do help to know the steps also.

As per my understanding, you have done the "Model First", and I want to have a "Database First" approach. 

Please help me in achieving this.

Looking forward to your great response. 

Thank you in advance.

**Comment by iayti** [comment]
If you want to change MSSQL to PostgreSQL or MySQL, You have to delete all Migrations (Infrastructure/Persistence/Migrations) and recreate. You also need to add dependency and packages. Depandency example for [PostgresSql](https://github.com/iayti/CleanArchitecture/blob/master/src/Common/Infrastructure/DependencyInjection.cs).

For DatabaseFirst approach, you can use [scaffolding mysql](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-scaffold-example.html). I have never tried scaffolding mysql. If you want to continue with the Model First approach after adding the existing database to the project with Database first, you will need to do a few tries 😃.

If you can make a successful implementation, can you share? 

Have a nice day.

**Comment by rmichaelbics** [comment]
> If you want to change MSSQL to PostgreSQL or MySQL, You have to delete all Migrations (Infrastructure/Persistence/Migrations) and recreate. You also need to add dependency and packages. Depandency example for [PostgresSql](https://github.com/iayti/CleanArchitecture/blob/master/src/Common/Infrastructure/DependencyInjection.cs).
> 
> For DatabaseFirst approach, you can use [scaffolding mysql](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core-scaffold-example.html). I have never tried scaffolding mysql. If you want to continue with the Model First approach after adding the existing database to the project with Database first, you will need to do a few tries 😃.
> 
> If you can make a successful implementation, can you share?
> 
> Have a nice day.

Thank you for your message. I will try it out and let you know

**Comment by Piotrekol** [comment]
Getting Mysql working with this template project is fairly straightforward.

Add `Pomelo.EntityFrameworkCore.MySql` & remove SqlServer in Infrastructure 
In DependencyInjection.cs in Infrastructure replace `UseSqlServer` with `UseMySql`
In Program.cs in WebUI replace `IsSqlServer` with `IsMySql`
After that, it's a matter of recreating migrations or running scaffold command using ef. Example for scaffolding with Pomelo can be found in their readme https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#scaffolding--reverse-engineering

**Comment by jasontaylordev** [comment]
Thanks all, closing.
