### ISSUE TITLE
New template release

### ISSUE THREAD

**Issue by AlaaL** [jasontaylordev/CleanArchitecture#262]
Hello and thank you for this great template, I am using it for a while now but today I wanted to create a new project so I decided to get a new version of the template because there is a lot of new changes.
I tried to update the template using `dotnet new -i template.name` but it didn't work and I thought it's a problem with NuGet cache.
But when i looked at template in NuGet website the latest update was from 6 months.
So i just want to request if we could make a new release every month for example, or am i missing something ? is there another way to get the latest version of template ?

**Comment by MCCshreyas** [comment]
If it's urgent, you can clone this repo, I have upgraded template to .NET 5.
https://github.com/MCCshreyas/CleanArchitecture/tree/net5

I have opened PR for this template as well, but it will take time to @jasontaylordev to get it merged!

Till that time you can use that repo.

**Comment by litan1106** [comment]
I use this template for all .net projects too.

**Comment by jasontaylordev** [comment]
Apologies, I've release a new version now.
