### ISSUE TITLE
Feature Request: Switch to Swashbuckle for better VS2019 support

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#263]
With the upcoming .net 5 and visual studio 2019 support and integration with Swashbuckle. I think Swashbuckle is better than NSwag.

https://www.davidhayden.me/blog/publish-asp-net-core-web-api-to-azure-api-management-services

**Comment by jasontaylordev** [comment]
Hi @litan1106. I thought about this too but ultimately decided to stick with NSwag. There are a few good reasons:

1. [NSwag ](https://github.com/RicoSuter/NSwag)already uses Swashbuckle for Open API generation
2. NSwag can display both [Swagger UI](https://swagger.io/tools/swagger-ui/) and [ReDoc](https://github.com/Redocly/redoc)
3. NSwag supports generation of many clients such as TypeScript clients, C# clients, and C# Web API controllers
4. NSwag can generate specifications at runtime and build time or from the command-line
5. NSwag can generate clients at build time or from the command-line
6. NSwag supports configuration editing using NSwagStudio

There's really a lot of good features in NSwag. 

It's cool that Open API has been added to ASP.NET Core 5 Web API projects, it provides a nice getting started experience. But there's not much more to it than that.
