### ISSUE TITLE
Docker support for Integration Tests

### ISSUE THREAD

**Issue by hassanrazakhalid** [jasontaylordev/CleanArchitecture#264]
Hi
I saw some tickets regarding Docker support for Presentation layer. I would like to know i can achieve same for integration tests. In my docker-compose say i'm using multiple dependent services that are required to completely test a Command. I'm not sure how Moq will be helpful here. I'm using RabbitMQ to communicate between services. Can someone please help how to add docker support for integration tests or is there another way around. Thanks

**Comment by kingjordan** [comment]
so far the docker set up for this app only has two services, the WebUI and the database for local development and only WebUI for production.  What other docker services would you be running and how how they be consumed by the app?

**Comment by hassanrazakhalid** [comment]
Other Docker containers like. All are separate containers.
1. MYSQL
2. Image to remove background
3. Container to convert mov to mp4
4. Container to make thumbnails
4. Container that does some video editing

All communication is done through RabbMQ. To fully test commands i need the above containers.

**Comment by jasontaylordev** [comment]
I've removed docked support as part of the repo to help narrow the focus, Clean Architecture with ASP.NET Core. If you want to get it I'm up and running, it should be quite straight forward, refer to .github/workflows/dotnetcore.yml as an example of how to setup a sqlserver container and connection string to run the tests as part of the pipeline.
