### ISSUE TITLE
Clean Architecture in Blazor Server EditForm Validation

### ISSUE THREAD

**Issue by mark-montinola** [jasontaylordev/CleanArchitecture#265]
I'm new to ASP.Net Core Development and I like the Clean Architecture design. But I have a problem in validating the EditForm of Blazor component using the Fluentvalidation. How to return the validation message to the EditForm?

**Comment by jasontaylordev** [comment]
Hi Mark - thanks for your question. I'm looking to release a new version of the template supporting Blazor soon. Until then, you might like to check out https://blog.stevensanderson.com/2019/09/04/blazor-fluentvalidation/. If that doesn't help, suggest create a sample repo and ask your question again on StackOverflow. Happy Coding! 😊
