### ISSUE TITLE
httpcontext is null in Integration Test

### ISSUE THREAD

**Issue by HanHtoonAung** [jasontaylordev/CleanArchitecture#266]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
I need to set record count in httpcontext when user has query, that is fine.

But I have a small issue with integration test, httpconext is null when integration test.

Please advise, 
Thanks in advance.

![image](https://user-images.githubusercontent.com/34746725/99945244-41b77180-2daf-11eb-956a-cdc18b1bbfa6.png)

![image](https://user-images.githubusercontent.com/34746725/99945309-5f84d680-2daf-11eb-9484-aedab0bc0f04.png)

**Comment by jasontaylordev** [comment]
Hi @HanHtoonAung. The tests in Application.IntegrationTests are not ASP.NET Core integration tests. Suggest that you create a new WebUI.IntegrationTests project and use the following approach: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0.

Happy Coding! 😊

**Comment by HanHtoonAung** [comment]
Hi @jasontaylordev,
Thanks for your advice.
