### ISSUE TITLE
how can I call from postman

### ISSUE THREAD

**Issue by satem02** [jasontaylordev/CleanArchitecture#269]
Hello,

How can i call token service or authorize service from postman ?

https://localhost:5001/connect/token
https://localhost:5001/connect/authorize
![image](https://user-images.githubusercontent.com/29017411/100137571-b5d04300-2e9d-11eb-987d-f58581ba8a8e.png)

**Comment by black-byte** [comment]
HI @satem02 

I guess the grant type you are looking for here is password

Just to double check please let us know what kind of grant types is your auth service supporting.
You can do that by calling:
https://localhost:5001/.well-known/openid-configuration

Additional info:
https://docs.identityserver.io/en/latest/topics/grant_types.html
https://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html#refclientcredentialsquickstart

**Comment by jasontaylordev** [comment]
Closing, this question is not specific to the template.
