### ISSUE TITLE
CleanArchitecture Blazor Template

### ISSUE THREAD

**Issue by BrettSandham** [jasontaylordev/CleanArchitecture#272]
Hi Jason

A version of this template using Blazor would be highly appreciated!

**Comment by MCCshreyas** [comment]
Check out this branch for reference -> https://github.com/jasontaylordev/CleanArchitecture/tree/blazor

**Comment by VeselinBPavlov** [comment]
Hello!
You can check my implementation of Clean Architecture with Blazor:
https://github.com/VeselinBPavlov/web-application-templates/tree/master/Generic%20Blazor%20Template

**Comment by ElderJames** [comment]
I would like to contribute a WebUI with  [Ant Design Blazor](https://github.com/ant-design-blazor/ant-design-blazor) if anyone likes it.

**Comment by jasontaylordev** [comment]
Closing stale issues.
