### ISSUE TITLE
What is best practice to unit test/ integration test with Twillio and SendGrid API in Clean unit testing?

### ISSUE THREAD

**Issue by anomepani** [jasontaylordev/CleanArchitecture#273]
What is the best practice to unit test/ integration test with Twillio and SendGrid API in Clean unit testing?

Is there a way to test code logic that depends on an external API like this?

Any Recommendation approach?

**Comment by jasontaylordev** [comment]
Hi @anomepani. Within the Application.IntegrationTests project, I've written subcutaneous tests. Ideally, we want these tests to exercise the production scenario as much as possible, and that means wiring up internal services including database, file system, and so on (anything we control). For external services such as messaging, I recommend creating very simple mocks - e.g. they don't need to do anything just not break your tests. Within Application.Integrations tests, you wouldn't test anything as specific as interaction with messaging services. Just happy paths - simple results.

When you want to write tests for behaviors that depend on these external serivces, again create a mock, but configure the mock to interact differently for the behavior you're trying to test. For example, if SendAsync should fail - configure the mock to do so. If it should succeed after a retry, configure that too - whatever you need to exercise the behavior you're trying to test.

I like to use Moq, but there are other tools out there. Happy coding! 😊

**Comment by anomepani** [comment]
Thanks for the detailed feedback.

If we have a stored procedure, is it a good idea to test with in-memory or SQLite or it's good to have an actual DB instance?

We are using CosmosDb in one and two projects how can we unit test or integration or what's the best way to test functionality without extra costing?

**Comment by GFoley83** [comment]
For anything more than trivial testing, I'd recommend avoiding using an in-memory db:. Good write up here:

https://jimmybogard.com/avoid-in-memory-databases-for-tests/
