### ISSUE TITLE
[BUG] Can't build project

### ISSUE THREAD

**Issue by bartek-890** [jasontaylordev/CleanArchitecture#274]
**Describe the bug**
Command ```dotnet build``` stops with error.
Environment 
```
PS C:\Git\test2\src\webui> node -v
v14.15.1
PS C:\Git\test2\src\webui> dotnet --list-sdks
>>
5.0.100 [C:\Program Files\dotnet\sdk]
```

**To Reproduce**
1. Init new template
2. cd src/webui'
3. open CMD - > run ```dotnet build```

**Expected behavior**
It should build project with no errors.

**Error**
```
  Domain -> C:\Git\test2\src\Domain\bin\Debug\net5.0\test2.Domain.dll
  Application -> C:\Git\test2\src\Application\bin\Debug\net5.0\test2.Application.dll
  Infrastructure -> C:\Git\test2\src\Infrastructure\bin\Debug\net5.0\test2.Infrastructure.dll
  WebUI -> C:\Git\test2\src\webui\bin\Debug\net5.0\test2.WebUI.dll
  WebUI -> C:\Git\test2\src\webui\bin\Debug\net5.0\test2.WebUI.Views.dll
  It was not possible to find any compatible framework version
  The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
    - The following frameworks were found:
        5.0.0 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

  You can resolve the problem by installing the specified framework and/or SDK.

  The specified framework can be found at:
    - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
C:\Git\test2\src\webui\WebUI.csproj(48,5): error MSB3073: Polecenie "dotnet "C:\Users\Bartek\.nuget\packages\nswag.msbuild\13.9.4\build\../tools/NetCore31/dotnet-nswag.dll" run /variables:Configuration=Debug" zostało zakończone przez kod -2147450730.
```

Maybe I missed something in environment setup.

**Comment by GFoley83** [comment]
`The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.`

`You can resolve the problem by installing the specified framework and/or SDK.`

Have you installed .NET Core 3.1?

**Comment by bartek-890** [comment]
Hey @GFoley83, thank you for response I installed the newest .NET as you see in first console log. It's in template specs. So It shouldn't be a problem.

**Comment by GFoley83** [comment]
The log shows you installed .NET 5 but not 3.1.

**Comment by bartek-890** [comment]
> The log shows you installed .NET 5 but not 3.1.

![image](https://user-images.githubusercontent.com/23739220/100842086-970f1500-3478-11eb-9a98-87d66e9561e3.png)

But in readme there is an information that I can use newest .NET 5 Core so it's probably bug.

**Comment by jasontaylordev** [comment]
Apologies, this was fixed I just hadn't published a new version to NuGet. Please install the latest version (1.1.4) and try again: 

```
dotnet new --install Clean.Architecture.Solution.Template
```

This problem is caused by a bug trying to run NSwag on .NET Core 3.1
