### ISSUE TITLE
replace the UI to a Blazor app

### ISSUE THREAD

**Issue by carlitosd19** [jasontaylordev/CleanArchitecture#276]
I was trying to replace the net core UI with a Blazor WASM with .Net 5  application but was a little tricky to me all the configuration in the Program.cs and Startup.cs , there is another template but in Blazor template that I can use??

**Comment by MCCshreyas** [comment]
Check out this branch for reference - https://github.com/jasontaylordev/CleanArchitecture/tree/blazor

**Comment by carlitosd19** [comment]
Thank you! It work
