### ISSUE TITLE
How to call store procedure

### ISSUE THREAD

**Issue by akbarbd** [jasontaylordev/CleanArchitecture#280]
This project is awesome. But I face a problem when call **store procedure.**
I am implement  **IApplicationDbContext** ,when use for call store procedure 
 then nothing found for call store procedure.

**Comment by EhsanHabib** [comment]
You should dapper instead, for calling stored procedures.

**Comment by iayti** [comment]
You can use store procedure in the project, if needed. Project is created by Db first approach. 
* Create an empty migration and add your "Create Procedure YourStoreProcedure ..."
* After the db update from migration, you can call the procedure _dbContext.FromSql("YourStoreProcedure")

For more information:  [Working with Store Procedure in Entity Framework Core](https://www.entityframeworktutorial.net/efcore/working-with-stored-procedure-in-ef-core.aspx)

**Comment by 009topersky** [comment]
Please check my solution here.

https://stackoverflow.com/questions/41341854/call-stored-procedures-with-entity-framework-6-code-first-approach-in-asp-net-mv/65879337#65879337

Thanks (Y)

**Comment by 009topersky** [comment]
**Step 1:**

Create your Stored Procedure script.

    IF OBJECT_ID ( 'usp_GetUserByCompany', 'P' ) IS NOT NULL   
        DROP PROCEDURE usp_GetUserByCompany; 
    
    GO
    CREATE PROCEDURE usp_GetUserByCompany
        @__ProfileId [uniqueidentifier],
        @__CompanyId [uniqueidentifier],
        @__Email VARCHAR (MAX),
    AS 
        SELECT *
        FROM [UserProfiles] AS [u]
        WHERE [u].[ProfileId] = @__ProfileId
            AND [u].[CompanyId] = @__CompanyId
            AND [u].[Email] = @__Email
    GO

**Step 2**

Create the Model for your Class

    public class UserProfile {
        public Guid Id { get;set; }
        public Guid CompanyId { get; set; }
        public Company Company { get;set; }
        public string Email { get;set; }
        ...
    }

**Step 3**

Go to your ApplicationDbContext class

    public class ApplicationDbContext {

        ...
        
        public virtual DbQuery<UserProfile> UserProfiles { get; set; }
    }

**Step 4**

Create a migration for your Stored Procedure

    dotnet ef migrations add Add_SP_GetUserProfileByCompany

**Step 5**

Inside the generated migration class implement the Stored Procedure script on **Step 1**

    public partial class Add_SP_GetUserProfileByCompany : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var usp_GetUserByCompany = @"
                IF OBJECT_ID ( 'usp_GetUserByCompany', 'P' ) IS NOT NULL   
                    DROP PROCEDURE usp_GetUserByCompany; 
                
                GO
                CREATE PROCEDURE usp_GetUserByCompany
                    @__ProfileId [uniqueidentifier],
                    @__CompanyId [uniqueidentifier],
                    @__Email VARCHAR (MAX),
                AS 
                    SELECT *
                    FROM [UserProfiles] AS [u]
                    WHERE [u].[ProfileId] = @__ProfileId
                        AND [u].[CompanyId] = @__CompanyId
                        AND [u].[Email] = @__Email
                GO
            ";

            migrationBuilder.Sql(usp_GetUserByCompany);
        }
        ...
    }

**Step 6**

In your code somewhere on the system or services etc.,

    public List<UserProfile> GetUserProfileByCompanySP(Guid ProfileId, Guid CompanyId, string Email)
    {
        var dbContext = new ApplicationDbContext;

        var parameters = new object[]
        {
            new SqlParameter() {ParameterName = "@__ProfileId", Direction = ParameterDirection.Input, SqlDbType = SqlDbType.UniqueIdentifier, Value = ProfileId},
            new SqlParameter() {ParameterName = "@__CompanyId", Direction = ParameterDirection.Input, SqlDbType = SqlDbType.UniqueIdentifier, Value = CompanyId},
            new SqlParameter() {ParameterName = "@__Email", Direction = ParameterDirection.Input, SqlDbType = SqlDbType.VarChar, Size = 64, Value = Email},
        };

        var output = dbContext.UserProfiles.FromSql("usp_GetUserByCompany @__ProfileId, @__CompanyId, @__Email", parameters).ToList();
        ...
    }

**Hope this solution will help!!
CHEERS !!!**

**Comment by jasontaylordev** [comment]
Great explanation, thanks.
