### ISSUE TITLE
dotnet new --install Clean.Architecture.Solution.Template Not working

### ISSUE THREAD

**Issue by aroymendez** [jasontaylordev/CleanArchitecture#282]
**Describe the bug**
When I execute dotnet new --install Clean.Architecture.Solution.Template
this doesn't install the template

**To Reproduce**
1. Go to 'my repo folder'
2. Typing dotnet new --install Clean.Architecture.Solution.Template
3. Typing mkdir Test
4. cd .\Test
5. Typing dotnet new ca-sln

**Expected behavior**
The template "Clean Architecture Solution" was created successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/64971331/102350272-0ad21700-3f7b-11eb-9dd2-e4d5c60e389f.png)

**Additional context**
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.518 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

**Comment by SunnyMakode** [comment]
> **Describe the bug**
> When I execute dotnet new --install Clean.Architecture.Solution.Template
> this doesn't install the template
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to 'my repo folder'
> 2. Typing dotnet new --install Clean.Architecture.Solution.Template
> 3. Typing mkdir Test
> 4. cd .\Test
> 5. Typing dotnet new ca-sln
> 
> **Expected behavior**
> The template "Clean Architecture Solution" was created successfully.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/64971331/102350272-0ad21700-3f7b-11eb-9dd2-e4d5c60e389f.png)
> 
> **Additional context**
> .NET SDK (reflecting any global.json):
> Version: 5.0.101
> Commit: d05174dc5a
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 10.0.19042
> OS Platform: Windows
> RID: win10-x64
> Base Path: C:\Program Files\dotnet\sdk\5.0.101\
> 
> Host (useful for support):
> Version: 5.0.1
> Commit: b02e13abab
> 
> .NET SDKs installed:
> 2.1.518 [C:\Program Files\dotnet\sdk]
> 3.1.402 [C:\Program Files\dotnet\sdk]
> 5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
> 5.0.101 [C:\Program Files\dotnet\sdk]

Use "Developer Powershell" in visual studio and it will work properly. I had an exact issue while running commands through CLI.

**Comment by aravindk777** [comment]
> Use "Developer Powershell" in visual studio and it will work properly. I had an exact issue while running commands through CLI.

Nope. This didnt work at all.
