### ISSUE TITLE
[Question] How would I build an admin panel with this solution?

### ISSUE THREAD

**Issue by nikibreg** [jasontaylordev/CleanArchitecture#283]
Let's say I need to build an admin panel, or something else that needs to have the same domain layer as my primary app, what do you think is the best way to do it?

Since persistence, including entity configurations are in the infrastructure layer, I probably need to use the same infrastructure and domain projects for both, the primary and admin apps. 
As for the other layers, should I create new UI and application projects or have the same application project and only create a new UI project?

**Comment by jasontaylordev** [comment]
The simplest approach would be to create the admin panel within the same front end app and use authorisation to secure access. I'd need to understand the benefits to separate it out further. 

In some cases, you might create a separate front end and backend for the admin app. This would allow you to have a separate and specific API to suit the needs of the admin app. The API would still depend on core. 

Something to think about, happy coding! 😀
