### ISSUE TITLE
[Question] Nullable Reference Types?

### ISSUE THREAD

**Issue by syky27** [jasontaylordev/CleanArchitecture#285]
Hi! 

First of all let me tell you thank you! This is most amazing template I ever came across, when you pair this with videos you YT, this is amazing stuff. I am new to .Net core, after 8 years of iOS development. So this is true gold mine for me.

Secondly, sorry for opening issue with a question but I think it is valid one for anyone searching in old closed issues one day.

For the question:

I am used to Nullable references from other languages, I understand why it is a opt-in feature in csharp.
I would like to ask if there is a reason why this template does not have nullable enabled? (I honestly know almost nothing about .NET, so dont take this question wrongly).

Thanks.

**Comment by jasontaylordev** [comment]
Sorry for not attending to this issue earlier, nullable has now been enabled.
