### ISSUE TITLE
[Question] Integration of Quartz Jobs (dynamic and static jobs)

### ISSUE THREAD

**Issue by hypervtechnics** [jasontaylordev/CleanArchitecture#286]
Hi people!

I want to integrate Quartz into my solution. I found an issue related to this: https://github.com/jasontaylordev/CleanArchitecture/issues/48#issuecomment-584066490 but implementing the proposed solution can be quite tedious. As we mainly need to duplicate the `IJob` and `ITrigger` from Quartz including their corresponding `Builder`s which is not kind of "elegant" I guess.

Here are my requirements:

- Usage of dependency injection container when running a job (scoped)
- Scheduling: Static (at startup) and dynamic (users can create entities which imply one (or multiple) scheduled job)
- Unscheduling of specific jobs (more specific: only the dynamic ones), so a "persistent"/fixed naming of jobs
- Trigger: Cron, timestamp and interval
- No hardcoded values/switch cases (like with error handling in api)

What I thought about:

1. Just use Quartz in the Application project. A change of the scheduling framework is very unlikely. Then the Job and Trigger creation is very easy.
2. Provide an abstraction only via multiple overloads (e.g. `schedule.Schedule<SomeJob>("myjob:1", TimeSpan.FromSeconds(30))` or `schedule.Schedule<SomeJob>("myjob:1", "* * * * *...")`)

Problems i encounter/think I will encounter:

1. Making the connection between my application Job instance and the Job interface of quartz. Is there a proxy or some reflection more suitable? Any other solution?

What do you think? What would you do?

**Comment by artjomzab** [comment]
Related https://github.com/jasontaylordev/CleanArchitecture/discussions/395#discussioncomment-1093752

**Comment by jasontaylordev** [comment]
Covered well in this discussion; https://github.com/jasontaylordev/CleanArchitecture/discussions/395
