### ISSUE TITLE
Login Controller

### ISSUE THREAD

**Issue by ahmedshah66** [jasontaylordev/CleanArchitecture#287]
i was wondering where is login controller in webapi project?
the login controller is missing there or how to import identitylogin service in webapi

**Comment by amedouardi** [comment]
you need to Scaffold Identity see https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-5.0&tabs=visual-studio

**Comment by iayti** [comment]
You can also check my repository. I added LoginController to webapi project.
[iayti/CleanArchitecture](https://github.com/iayti/CleanArchitecture)
have a nice coding 😊

**Comment by hexroot007** [comment]
@amedouardi in which layer ?

**Comment by amedouardi** [comment]
> 
> 
> @amedouardi in which layer ?

you can keep it as it is in  WebUi=>Areas=>Identity=>Pages=>Account.   unless you are ready to create your own controllers with the same logic used in *.chtml.cs (heavy task but can be done).

**Comment by bramburn** [comment]
> You can also check my repository. I added LoginController to webapi project. [iayti/CleanArchitecture](https://github.com/iayti/CleanArchitecture) have a nice coding 😊

your folder isn't the same as the main repo. did you start from scratch on that one?

**Comment by bramburn** [comment]
you could use this in the startup.cs

```cs
services.AddDefaultIdentity<ApplicationUser>(options =>
            {
                options.SignIn.RequireConfirmedAccount = true;
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
            }).AddRoles<IdentityRole>()
            .AddEntityFrameworkStores<ApplicationDbContext>();
        services.AddIdentityServer().AddApiAuthorization<ApplicationUser, ApplicationDbContext>();
        services.AddAuthentication().AddIdentityServerJwt();
```

**Comment by jasontaylordev** [comment]
I know this is very old, but just in case this helps someone else: there is no login controller. As mentioned above you should scaffold identity and view the code generated. This code will interact with Identity UserManager<ApplicationUser> within Razor pages. You can use this code as a very good example that can be the basis of a login controller that you build.
