### ISSUE TITLE
Example how to integration test logic on database error

### ISSUE THREAD

**Issue by molntamas** [jasontaylordev/CleanArchitecture#288]
**My Issue**
I would like to add a test how my application logic reacts when a database operation fails.
For instance if saving to the database fails, I would like to trigger some logic.

```
try
{
  _dbContext.SaveChangesAsync();
}
catch
{
  DoSomething();
}
```
I am not sure what is the best approach for this.

**Describe the solution you'd like**
I would like to have a concept in your CleanArchitecture setup how to test such scenario and an example.

**Describe alternatives you've considered**
As alternative I could add an extra interface to my classes instead of using the DB context which is not mocked.
But I was wondering if it is possible to avoid this boilerplate code.

**Comment by jasontaylordev** [comment]
Probably too late to help but regardless, the tests in Application.IntegrationTests are against a live and real SQL Server database.
You should be able to test the scenario you have in mind using that project.
