### ISSUE TITLE
[Question] How to use the domain events?

### ISSUE THREAD

**Issue by jessestr** [jasontaylordev/CleanArchitecture#289]
In the DomainEventService the domain event gets published, but how can I use it? To execute another command for example.
Do I use the EventHandler and then execute the command  I need over there?

I have a command which upserts a receipt, which is exposed via an API call. 
But I have separate bookkeeping logic which should create/update one or more receipts depending on some logic. 

Is the domain event the way to go? Or how does it work? As the ReceiptUpsertCommand contains some business logic which has to be executed for every receipt upserted. So I want to use that command to be sure the same flow always happens.

Thanks in advance!

Edit:
Nothing to do with my previous question. But do you have to make domain events for every entity/action? Or just for the ones you need to do something with?

**Comment by MCCshreyas** [comment]
Not for every entity or action. It depends upon the usecase!

**Comment by jasontaylordev** [comment]
The domain events system has been rebuilt, feel free to review.
To learn more about domain events check out https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.
Happy coding! 😀
