### ISSUE TITLE
Give your thoughts about horizontal scaling multi tenant application based on this template

### ISSUE THREAD

**Issue by rajasingh012** [jasontaylordev/CleanArchitecture#290]
I am working to design horizontal scaling multi tenant application, which uses separate database for each clients, and all the databases has same schema. Every request has header 'tenant-id', to denote the company information. In angular, I will use HttpInterceptor to add tenant-id and branch-id for each request.  

1. What are the changes needs to be done in authentication pipeline, to include company id and branch-id, and check with relevant databases
2. This template uses IPipelineBehavior for performance, unhandledexception, validation, what are the changes should be implemented for multi-tenant.
3. IApplicationDbContext class was injected to every command and query, shall we add new property tenant id. 
4. All the query/command must have tenant-id, branch-id. Shall I create new marker interface and create two properties, or do you have any other thoughts.
5. Is asp.net core identity, identityserver4 supports multi-tenant?

Is anyone encounter this problems, can you please explain how you solve it.

**Comment by weedkiller** [comment]
I agree 👍  it would be nice to see an _option_ in the template to use `Multitenancy `
Also Role Base Menu Management Sample for the practical world

**Comment by maulik-modi** [comment]
@rajasingh012 , Did you find solution to your requirements.

I think https://www.finbuckle.com/MultiTenant is the way to go.

**Comment by rajasingh012** [comment]
I'm working on solution based on https://abp.io/
