### ISSUE TITLE
[QUESTION] How can i set relation between IdentityDbContext and PersistenceDbContext

### ISSUE THREAD

**Issue by can-guven** [jasontaylordev/CleanArchitecture#291]
ApplicationUser is in Identity layer and different DbContext. My entities are in Domain. Domain has no dependent any layer.  How can i manage relation. For example my Task entity has userId. Thank you for answers.

**Comment by deceptiveSimplicity** [comment]
I would just save the UserId on the Task, without referential integrity (RI). With RI when deleting a user, all his Taks have to be deleted, maybe additional entities that depend on Tasks too - or at least the UserId have to be nulled.
If you still want to have a UserID-FK on your Task, try this:
`public class YourTaskConfiguration : IEntityTypeConfiguration<YourTask> { public void Configure(EntityTypeBuilder<YourTask> builder) { builder.HasOne<ApplicationUser>().WithMany().HasForeignKey(t => t.UserId); } }`
