### ISSUE TITLE
[Question] Re-use of Fluent Validation

### ISSUE THREAD

**Issue by scottkuhl** [jasontaylordev/CleanArchitecture#299]
I often find myself duplicating the rules between the commands and queries that could potentially be shared when the front-end is also written in C# like with ASP.NET or Blazor instead of Angular.

One option is to move the rules back to the **domain model**. Instead of receiving specific parameters in the command and sending out specific properties in the query, the domain model itself could be used.  But this seems to break with the lose coupling on the CQRS pattern.

Fluent Validation lets you share validation when both objects inherit from the same base.  So, another option would be a shared base **view model** between the commands and queries.  But this seems to increase coupling.

Fluent Validation also has the concept of **reusable property validators** that is meant for more generic custom rules but could be used to create things like a first name validator.  That's a lot of extra code there.

**How is this scenario best handled?**  Right now we are just duplicating the rules in the commands and queries.

**Comment by rafaelfgx** [comment]
You can do it this way below:

```
public abstract class UserCommand
{
    public string FirstName { get; set; }

    public string LastName { get; set; }
}

public sealed class AddUserCommand : UserCommand { }

public sealed class UpdateUserCommand : UserCommand
{
    public int Id { get; set; }
}

/// In this class are all common rules
public static class UserRules
{
    public static IRuleBuilderOptions<T, int> Id<T>(this IRuleBuilder<T, int> ruleBuilder) => ruleBuilder.NotEmpty();

    public static IRuleBuilderOptions<T, string> FirstName<T>(this IRuleBuilder<T, string> ruleBuilder) => ruleBuilder.NotEmpty().Length(3, 50);

    public static IRuleBuilderOptions<T, string> LastName<T>(this IRuleBuilder<T, string> ruleBuilder) => ruleBuilder.NotEmpty().Length(5, 200);
}

public sealed class AddUserCommandValidator : AbstractValidator<AddUserCommand>
{
    public AddUserCommandValidator()
    {
        RuleFor(x => x.FirstName).FirstName();
        RuleFor(x => x.LastName).LastName();
    }
}

public sealed class UpdateUserCommandValidator : AbstractValidator<UpdateUserCommand>
{
    public UpdateUserCommandValidator()
    {
        RuleFor(x => x.Id).Id();
        RuleFor(x => x.FirstName).FirstName();
        RuleFor(x => x.LastName).LastName();
    }
}
```

**Comment by scottkuhl** [comment]
@rafaelfgx That is an excellent way to share the rules.  Thanks.
