### ISSUE TITLE
ApplicationUser and nested properties

### ISSUE THREAD

**Issue by viros** [jasontaylordev/CleanArchitecture#30]
Wondering how to implement application logic that reference to ApplicationUser. F.e how to show only TodoLists that belongs to the current user. Where this logic should go?

How to customize ApplicationUser in right way. F.e if i have  Image entity in my domain, how i can associate this image with ApplicationUser( as i understand i can't use shadow properties as AppUser is not part of the domain)

**Comment by pauldbentley** [comment]
> Wondering how to implement application logic that reference to ApplicationUser. F.e how to show only TodoLists that belongs to the current user. Where this logic should go?

I would also be interested in this.  Would you add a `UserId` property to the `TodoList` entity?  But then I'm not clear where you would provide this value.  Would you inject a `ICurrentUserService` into `GetTodosQueryHandler` or would you add a `UserId` property to `GetTodosQuery` and set this in the controller?

**Comment by GFoley83** [comment]
> Would you inject a ICurrentUserService into GetTodosQueryHandler

This is exactly what you would do. 
If you're going to be querying on `CreatedBy` frequently then might be good to add an index on it too.

**Comment by jasontaylordev** [comment]
Thanks for your help @GFoley83! 😀
