### ISSUE TITLE
[Question] OData: Application or Presentation Layer?

### ISSUE THREAD

**Issue by marcoatribeiro** [jasontaylordev/CleanArchitecture#300]
Hi Jason,

I was wondering if you have any thoughts on incorporating [OData V4](https://docs.microsoft.com/pt-br/odata/) capabilities into the template?

If you would, would you use [Microsoft.AspNetCore.OData](https://www.nuget.org/packages/Microsoft.AspNetCore.OData/) package (and, thus, leave this "logic" in presentation layer), or else implement it in Application layer?

**Comment by jasontaylordev** [comment]
Apologies, this is not a tech I would like to incorporate at this stage.
