### ISSUE TITLE
WPF MVVM Pattern 

### ISSUE THREAD

**Issue by wahidrezgui** [jasontaylordev/CleanArchitecture#304]
Hy,
would you please help me to add new MVVM  project to the solution and get advantage  of the architecture i can't figure out how to add WPF project reference the **Infrastructure** layer and  use functionality provided by the infrastructure layer.

Thank you

**Comment by meJevin** [comment]
This would be awesome! +1 Up!!

@jasontaylordev what do you think about this?

**Comment by jasontaylordev** [comment]
Great suggestion, but not something I am going to tackle. I haven't built anything with WPF since 2013 so I am too rusty. 🤣

**Comment by wahidrezgui** [comment]
I tried to start a new projet based on what was done on the core layer and it looks like we have two main roads:
1 build a wpf app based on api´s (it will consume the api)
2 the wpf app will reference the infra layer and we have to write a new identity service and authorization mechanism

**Comment by jasontaylordev** [comment]
Closing, but first some suggestions:
The other approach would be to have the WPF app interact with the Application layer, calling commands and queries directly.
Of course, the dependencies would need to be wired up in WPF. So the WPF app would depend on Application and Infrastructure.
Using the MVVM pattern would be perfect, with the VM being dependent on IMediator to invoke relevant commands / queries.
