### ISSUE TITLE
dotnet new ca-sln does not contain up to date code

### ISSUE THREAD

**Issue by kingjordan** [jasontaylordev/CleanArchitecture#307]
Hello,

if you install the template via `dotnet new --install Clean.Architecture.Solution.Template` and run `dotnet new ca-sln` the project 
 does not include recent code chnages from the repository like docker files etc.

Cheers

**Comment by jasontaylordev** [comment]
Thanks, I'll get it sorted.

**Comment by jasontaylordev** [comment]
It's up to date now
