### ISSUE TITLE
[Question] FluentValidation against database but from the front end

### ISSUE THREAD

**Issue by Chris-Mingay** [jasontaylordev/CleanArchitecture#309]
I would like to be able to validate a command before I actually commit to running it. Instinctively I thought "Hey, just make a validator call from the front end"

So in the Blazor front end I would have something like...

```
SuperStuffCommand cmd = new SuperStuffCommand(){
   ...
};

SuperStuffCommandValidator v = new SuperStuffCommandValidator();
var response = v.Validate(cmd);
```
however the `SuperStuffCommandValidator` expects an `IApplicationDbContext` as part of its constructor. This isn't a problem when sending a command via Mediatr however I'm not sure how to "inject" said DbContext from the front end as I do not want my front end project to depend on the Infrastructure project.

Has anyone done anything similar? Am I maybe looking at this the wrong way?

I guess the alternative is for the `SuperStuffCommand` object to have a `public bool DryRun` property or similar which does validation but doesn't actually go through with it if DryRun == false. This relies on me including said property in each and every command though, I'm not sure if that's good?

Any thoughts?

Thank you!

**Comment by RHaughton** [comment]
I'm having the same issue as you, I also have some fluent validation who depends on the DbContext. 
Have you found any solution? 
I'm thinking about removing all DBContext validation from fluent validation Behaviour and check for those validation cases (already exists in DB for example) directly in the  Handler.

**Comment by Chris-Mingay** [comment]
Hi @RHaughton sorry no I've not revisited this yet. I've considered the same as you, but I dunno, it doesn't feel right to me, I'd like all validation to stay within the validator (if possible!).

**Comment by jasontaylordev** [comment]
I discussed a potential approach in this talk; https://youtu.be/lRYrhj9lwQk. Hope it helps.
