### ISSUE TITLE
[Question] How to define or add other clients in identity server?

### ISSUE THREAD

**Issue by MuneerHazawi** [jasontaylordev/CleanArchitecture#310]
Greetings, Iam trying to access API through the Android application - Ionic - and I do not know what is the appropriate way to define another independent Angular client to the identity server.
 I do not have sufficient experience with identity server, but when reading the documents I found that there are several methods to add clients when using the identity server independently, but when I used these methods with this clean architecture, it did not work.
I tried to add clients to memory:

`  services.AddIdentityServer()
.AddInMemoryClients(Config.GetClients())
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

 However, at the time of implementation, the program was collapsing with an error message: **'Client 'ionic_app' not found.'**
I also tried to add the customer through the options:

`  services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(option=>
                {
                    option.Clients.Add(Config.GetIonicClient());
                });`

The result was also another error: **Can't determine the type for the client 'ionic_app'**
Is there a way to add other clients to access API? Or is this method not compatible with this architectural design?
And if there is, is it possible to add this feature in the future? Not sure how to implement it on this design, sorry I'm still new to identity server.

**Comment by s-whaley** [comment]
One way an additional client can be added 
``
services.AddIdentityServer()
.AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
  {
      options.Clients.Add(new Client
      {
          ClientId = "CLIENT_ID",
          AllowedGrantTypes = { GrantType.ResourceOwnerPassword },
          ClientSecrets = { new Secret("secret".Sha256()) },
          AllowedScopes = { scopes },
      });
  })
``

**Comment by MuneerHazawi** [comment]
Thank you @s-whaley  i'll give it a try.

**Comment by fakhrulhilal** [comment]
> 
> 
> One way an additional client can be added
> `services.AddIdentityServer() .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options => { options.Clients.Add(new Client { ClientId = "CLIENT_ID", AllowedGrantTypes = { GrantType.ResourceOwnerPassword }, ClientSecrets = { new Secret("secret".Sha256()) }, AllowedScopes = { scopes }, }); })`

Any other way other than this. Let's say I want to get & store the client API through db. I tried [this way](https://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html) but no luck. I believe `PersistedGrantDbContext` migration is included in the template. So I need to add migration only for `ConfigurationDbContext`. 

But both ways have the same problem. They are not accessible through OIDC controller (.e. /_configuration/CLIENT_ID url). The log says that the client ID is not registered. But it works when used for generating access token.

**Comment by jasontaylordev** [comment]
Closing, as not specific to the template.
