### ISSUE TITLE
Separate API, UI and authentication

### ISSUE THREAD

**Issue by kjartanvalur** [jasontaylordev/CleanArchitecture#311]
Hi. Thank you for this awesome project.

I really like this pattern but in my experience, it´s a better  to separate UI project from API and also have a IdentityServer project for Authentication. It would be really helpful to have that approach as an option for this template.
By this approach, you could also more easily change out the authentication for Azure AD B2C or Auth0.

**Comment by isaacOjeda** [comment]
Hi! I think I did something similar of what you're asking in this [repo](https://github.com/isaacOjeda/DesignPatterns), take a look and tell me what you think👍🏼. The API and Angular projects are basically this template.

✌🏼

**Comment by kjartanvalur** [comment]
Thanks @isaacOjeda 
Have you considered upgrading to ASP.Net 5?

**Comment by jasontaylordev** [comment]
Great suggestions, but not looking to implement those here. As always I am looking for the simplest approach.
