### ISSUE TITLE
Customize default login / register templates of IS4

### ISSUE THREAD

**Issue by mychampionspool** [jasontaylordev/CleanArchitecture#316]
just looking for some feedback on what is the best way to "style/customize" the look of the Is4 login and register pages that are auto generated.

I don't want to create my own login pages when all I need is to change the look of the menu bar and primary color of the buttons etc. Is there a quick way to do this?

thanks

**Comment by s-whaley** [comment]
If I'm not mistaken, the Identity pages inherit the layout at "/Views/Shared/_Layout.cshtml" which references the wwwroot/css/site.css file. You should be able to edit the site.css and apply your customizations.

**Comment by jasontaylordev** [comment]
You can also check this out - https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-6.0&tabs=visual-studio
