### ISSUE TITLE
[Question] Explicit Data Loading Example

### ISSUE THREAD

**Issue by Rocinante89** [jasontaylordev/CleanArchitecture#317]
**Is your feature request related to a problem? Please describe.**
I need to load some relational data based on the value of a bool, (includeAccounts). In a previous project I was using EFCore explicit loading for this as in the example below. 

     var blog = context.Blogs
        .Single(b => b.BlogId == 1);

    context.Entry(blog)
        .Collection(b => b.Posts)
        .Load();

    context.Entry(blog)
        .Reference(b => b.Owner)
        .Load();`

I have noticed however that the IApplicationDbContext does not expose Entry, and my attempts to expose it myself haven't worked.

**Describe the solution you'd like**
An example of how to expose these would be great!

**Describe alternatives you've considered**
I can always fall back to eager loading

**Comment by PilotBob** [comment]
Is it possible to compose your query based on your booleans?

var query = context.Blogs;

if (includeAccounts) 
   query = query.Include(b => b.Acounts);
if (includePosts)
    query = query.Include(b => b.Posts);

query = query.Single(b => b.BlogId == 1);

**Comment by Rocinante89** [comment]
@PilotBob this is exactly the approach I went with in the end!
