### ISSUE TITLE
Could not load settings for..

### ISSUE THREAD

**Issue by furiozo** [jasontaylordev/CleanArchitecture#321]
Hi all,

I was setting up the clean architecture project and everything went well. 

Ran npm install.
Changed the db connection string accordingly.

But when running dotnet run, I experience the following error:

![image](https://user-images.githubusercontent.com/467017/110555483-57c22580-8145-11eb-806f-8dc81d6abe4e.png)

Any Ideas?

**Comment by RicardoValero95** [comment]
How did you fix this? I have the same problem.

**Comment by RicardoValero95** [comment]
Oh sorry. I was expecting the app on http://localhost:4200/ but it is on https://localhost:5001/

**Comment by FlaterF** [comment]
Looking for an answer to this to. Did not touch the clientapp until today, it's throwing this error for both my new pages and the existing fetch-data example page.

**Comment by LXOXOL** [comment]
I have been hacked! I had already reported issues to authorities and now this. Please remove me from your email lists etc. Sorry about the inconvenience! 

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 27, 2022 at 4:47 PM, ***@***.***> wrote:   


Looking for an answer to this to. Did not touch the clientapp until today, it's throwing this error for both my new pages and the existing fetch-data example page.
