### ISSUE TITLE
[Question] Authentification for WebAPI only.

### ISSUE THREAD

**Issue by RHaughton** [jasontaylordev/CleanArchitecture#323]
Hi Everyone,

I'm a bit lost with the authentication process.
I completely ditched the angular WebUI and I'm focusing on Web API. 
I plan to build a Blazor Website which will exclusively communicate to the backend using the Web API.

Could someone guide me on what strategy  should I use to achieve my goals?

Should I create and AuthenticationController with at least 'Register' and 'Login' endpoint?
The Login endpoint should return a Token?

This token would be attached to all 'Authorize' request? 
Should this token be a property of all my commands?

Let me know if you need more info.

Thanks for your help.

**Comment by iayti** [comment]
Hi,

You can check [my repo](https://github.com/iayti/CleanArchitecture) for Web Api Authorize implementation which very similar in this repo.

Have a nice coding 😊

**Comment by RHaughton** [comment]
Thanks @iayti,

I've just checked youor repo. I replicated it. But I still have the same error and I can't debug it.

When I use the Authorize Attribute and I dont give a Bearer Token, I get an 401 unauthorized. that's what I expect.
When I use a Bearer token I just created, I get an internal server error with message "Sequence contains no elements."

I strictly followed your solution :( do you have any ideas?

**Comment by iayti** [comment]
> Thanks @iayti,
> 
> I've just checked youor repo. I replicated it. But I still have the same error and I can't debug it.
> 
> When I use the Authorize Attribute and I dont give a Bearer Token, I get an 401 unauthorized. that's what I expect.
> When I use a Bearer token I just created, I get an internal server error with message "Sequence contains no elements."
> 
> I strictly followed your solution :( do you have any ideas?

Hi @RHaughton 

I'm not sure, but it may be because the import you added for Authorize Attribute is wrong. You should point out that we added it later, not the import package of the Default Authorize class. I can't be quite sure without seeing the error. I hope it works for you. 😊 

Have a nice coding.

**Comment by RHaughton** [comment]
Hi iayti,

Many thanks for your help. I finally figure it out. 
The logging behaviour was requesting the currentUserId. In my case username and email are the equal.
I had it mixed up and was looking the database id = request.id (which was an email).

Thanks for your help.

Another question: Would you recommend wrapping all response in your ServiceResult/ServiceError class?
If yes, what is the difference with the Result class provided in the template. Could'nt we just extend Result to Result<T> for data response?

**Comment by iayti** [comment]
> Hi iayti,
> 
> Many thanks for your help. I finally figure it out.
> The logging behaviour was requesting the currentUserId. In my case username and email are the equal.
> I had it mixed up and was looking the database id = request.id (which was an email).
> 
> Thanks for your help.
> 
> Another question: Would you recommend wrapping all response in your ServiceResult/ServiceError class?
> If yes, what is the difference with the Result class provided in the template. Could'nt we just extend Result to Result(of T) for data response?

If we come to the first question, it is actually a matter of preference. I prefer that the answers returned from the api are in a fixed format. You are right about the Result object, I only use it in IdentityService. An update is available on this. I would appreciate it if you could make such a change and send it. 😃

Have a nice coding.

**Comment by jasontaylordev** [comment]
Thanks all, closing.
