### ISSUE TITLE
[Question] Should domain events be fired before saving changes?

### ISSUE THREAD

**Issue by danielmackay** [jasontaylordev/CleanArchitecture#326]
The CA template fires the domain events after saving changes.  However, if any of the event handlers are supposed to modify related entities but fail, we then have a consistency problem.

Q: Should the domain events be fired BEFORE saving DB changes?

Microsoft recommends this approach so that any side affects occur within the same transaction: 
[Microsoft - Domain Events](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation#what-is-a-domain-event
)

**Comment by nhaberl** [comment]
What about handling the infrstaructure logic (like persisiting, cross cutting concerns, notifications) within the event handlers?
I am aware of the commands for processing responses but wouldn't it be easier to validate and forward this request to the domain model and add logic directly attached to it?
Like `taskListObject.CreateTask(...)` which raises events internally to handle all persistance stuff and it's guaranteed to handle this within 1 transaction (which gets decided by the application layer wehen it commits the event logic)

**Comment by mmbeyrem** [comment]
Firing events before commit , it's not a good idea and even you are not
solving your problem.
You need to wait until any command  triggered within this event to finish
in order to keep better consistency but you know this is not a good
approach either

**Comment by nhaberl** [comment]
But what if alle events are involved in the transaction context and if any logic fail in there, it's automatically rolled back. As the Microsoft article said ... if you seperate your events into "transactional" and integration (which dire maybe async) events I would not see any problem.
The command from the application layer commits his operation and the domain layer handles all events which are queued until any commit is called.

**Comment by danielmackay** [comment]
To be clear, I think we can agree that we are talking about "domain events" and not "integration events" here.  Integration events are to propagate changes within different subsystems that we may not have control over.  Domain events however are designed to propagate events with OUR domain that we do have control over.  Thus we want to ensure consistency within our domain, by enforcing that either all changes are made to the DB or none of them are.

Consider an example where changing a status of an entity, might add a log record to a DB.  This status might be changed in several places in the application, and thus we don't want to have the logging of this spread throughout our codebase.  Instead a domain event is perfect here, so that anytime this property is changed we can ensure this log is recorded.  

However, because the clean architecture template is committing to the DB BEFORE firing these events, it's possible they may fail and the status could get updated without the logs being added.  In that case we have an inconsistent DB.

Hopefully, that helps to illustrate the problem I see here.

**Comment by nhaberl** [comment]
Exactly my concerns ... that was why I started moving the persistance code in events and commit it globally after all events have fired - so all event handler rely on infrstructure code and have all infos available to process the event through eventdata

**Comment by nagasudhirpulla** [comment]
Hi, In my project, I have an Employee Department History table and a cache table for storing latest employee departments so that we can reduce DB hits.

In my DbContext's SaveChangesAsync function, I have first called base.SaveChangesAsync and then dispatched the events so that the event handlers know the latest db state.
For transactional guarantees, I have wrapped the base.SaveChanges and events dispatching inside a transaction.
This is the code
```csharp
            var events = ChangeTracker.Entries<IHasDomainEvent>()
                .Select(x => x.Entity.DomainEvents)
                .SelectMany(x => x)
                .Where(domainEvent => !domainEvent.IsPublished)
                .ToArray();

            if (this.Database.CurrentTransaction == null)
            {
                using IDbContextTransaction transaction = this.Database.BeginTransaction();
                try
                {
                    var result = await base.SaveChangesAsync(cancellationToken);
                    await DispatchEvents(events);
                    transaction.Commit();
                    return result;
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    Console.WriteLine($"rolling back changes occured while saving DB changes, {ex.Message}");
                    throw;
                }
            }
            else
            {
                var result = await base.SaveChangesAsync(cancellationToken);
                await DispatchEvents(events);
                return result;
            }
```


Am I doing it correct.
Please suggest if there are any mistakes or any scope for improvement.

Thanks
Nagasudhir

**Comment by jasontaylordev** [comment]
As per recommendations I have changed the implementation to dispatch domain events before saving changes:

```csharp
    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        await _mediator.DispatchDomainEvents(this);

        return await base.SaveChangesAsync(cancellationToken);
    }
```

This approach was inspired by [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Infrastructure/OrderingContext.cs), which included some useful comments:

```csharp
    public async Task<bool> SaveEntitiesAsync(CancellationToken cancellationToken = default(CancellationToken))
    {
        // Dispatch Domain Events collection. 
        // Choices:
        // A) Right BEFORE committing data (EF SaveChanges) into the DB will make a single transaction including  
        // side effects from the domain event handlers which are using the same DbContext with "InstancePerLifetimeScope" or "scoped" lifetime
        // B) Right AFTER committing data (EF SaveChanges) into the DB will make multiple transactions. 
        // You will need to handle eventual consistency and compensatory actions in case of failures in any of the Handlers. 
        await _mediator.DispatchDomainEventsAsync(this);

        // After executing this line all the changes (from the Command Handler and Domain Event Handlers) 
        // performed through the DbContext will be committed
        var result = await base.SaveChangesAsync(cancellationToken);

        return true;
    }
```

I've made the design as simple as possible, so the approach can be adjusted based on preference.

Thanks Daniel for the suggestion, hope all is going well for you. Happy Coding! 😀

**Comment by danielmackay** [comment]
@jasontaylordev - thanks for making this change and providing insight as to the different choices.

We have been using this solution template for 2 years now in production, and it's been working out great for us.  Thank you for all the hard work you've put into this. 😀

**Comment by roelofsmn** [comment]
@jasontaylordev I was looking into this with the eShop .NET example project as well, and stumbled upon this thread. I created an [issue](https://github.com/dotnet/eShop/issues/757) there about the explanation that is given in the `SaveEntitiesAsync` method. While I think the explanation in general is correct, I believe it might not be given how it is used in the eShop project with MediatR behaviors (specifically the `TransactionBehavior`. Do you have an idea about this?
