### ISSUE TITLE
How to implement soft-delete

### ISSUE THREAD

**Issue by robertsundstrom** [jasontaylordev/CleanArchitecture#328]
I just want to share how I ended up implementing soft-delete. I wanted to keep it simple.

Feedback is appreciated!

### ISoftDelete interface

Define the interface:

```c#
namespace Sales.Domain.Common
{
    public interface ISoftDelete
    {
        DateTime? Deleted { get; set; }

        string? DeletedBy { get; set; }
    }
}
```

Implement the interface:

```c#
public class Order : AuditableEntity, ISoftDelete 
{
    // Omitted
    
    public DateTime? Deleted { get; set; }

     public string? DeletedBy { get; set; }
}
```

### Modify DbContext

Add this to the ```SaveChangesAsync``` method in your DbContext:

```c#
                    case EntityState.Deleted:
                        if (entry.Entity is ISoftDelete softDelete)
                        {
                            softDelete.DeletedBy = _currentUserService.UserId;
                            softDelete.Deleted = _dateTime.Now;

                            entry.State = EntityState.Modified;
                        }
                        break;
```

### Entity Model Configuration

Configure Query Filter:

```
            builder.Entity<Order>().HasQueryFilter(e => e.Deleted == null);
```

**Comment by iayti** [comment]
Thanks for sharing @robertsundstrom 😊 

Have a nice coding.

**Comment by fakhrulhilal** [comment]
Perhaps this can be moved to wiki instead? Issue is mostly used for tracking item that need to be followed up. I'm afraid, people can't find this useful tutorial when this issue closed.

**Comment by jasontaylordev** [comment]
Thanks for sharing, I've enabled discussions so we can move it over to there
