### ISSUE TITLE
Only use API and problem remove SPA angular client to use separate client(s)

### ISSUE THREAD

**Issue by MichaelGarrido2** [jasontaylordev/CleanArchitecture#329]
Hi,
I attended the work shop in NDC London, which was great ! 
But I now want only to use the API part (and remove the Angular SPA client).
- Currently I also get errors on publish on the SPA which emphases my need to remove the SPA client.

I see in the WebUI project that there are targets for the SPA Angular parts but I haven't been able to figure out how to remove them (and not "f#%ck up the project file)

I've looked through the issues to see if there where anyone else wanting to do this and I found a couple of issues that discussed it, but only limited information on **how** to do it.
Any pointers on the steps necessary is very much appreciated .
Thanks
Michael

**Comment by MichaelGarrido2** [comment]
I think I got it right.
First I deleted the ClientAppFolder and it's contents
Then I modified the WebUI.csproj file item group
`<ItemGroup>
    
    <Content Remove="$(SpaRoot)**" />
    <None Remove="$(SpaRoot)**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>`

and the targets:
`<Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" ....
    ....<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>`

`<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">...
 ... </Target>`

**Comment by Sokoo92** [comment]
For next time, just add a new project to the solution, call it WebAPI and copy & paste Program.cs and Startup.cs over and the controllers folder. Then just fix the references throughout.

**Comment by MichaelGarrido2** [comment]
That's a better approach, thanks!

**Comment by abdoallah** [comment]
could you help me to figure out how you solved this problem

**Comment by abdoallah** [comment]
@MichaelGarrido2
