### ISSUE TITLE
[QUESTION] Is event sourcing applicable for this type of solution? 

### ISSUE THREAD

**Issue by karlbal** [jasontaylordev/CleanArchitecture#330]
I really like this solution template and used it for my personal project. I already implemented two separate solutions in one project, one for the main application and the other one is for messaging using SignalR and used DotNetCore.Cap (Rabbitmq) for event publishing for handling user profile changes. 

This is just out of curiosity though as we all know, microservice is trending these days. And I'm thinking of committing to this architecture. I understand that it's not really necessary to implement event sourcing for microservices, but I think it gives a lot of advantages especially with data availability. I'm still new to this kind of topic, so I really appreciate any inputs. 

Thank you very much!

**Comment by pcarvsilva** [comment]
I think you my have problems with Persisting into two different dbs, if you could solve that problem I think it would be ok
