### ISSUE TITLE
[Question] Can I send request using mediator in Application layer at other handler?

### ISSUE THREAD

**Issue by qwas368** [jasontaylordev/CleanArchitecture#331]
I am clean architecture beginner and use it to my project recently.
I implement CRUD handler in application layer. Can I reuse it  by mediator at other handler?
If not, how should I do ?

```csharp
public class CopyRecipeCommandHandler : IRequest<CopyRecipeCommand, UpdateResultVm>
{
	IMediator _mediator { get; }

	IDbContext _dbContext { get; }

	public CopyRecipeCommandHandler(
		IDbContext dbContext,
		IMediator mediator)
	{
		this._mediator = mediator;
		this._dbContext = dbContext;
	}

	public async Task<UpdateResultVm> Handle(CopyRecipeCommand request, CancellationToken cancellationToken)
	{
		var sourceRecipe = dbContext.Recipes.Where(c => c.Id == request.sourceId).First();

		var targetRecipe = dbContext.Recipes.Where(c => c.Id == request.targetId).First();

		Copy(sourceRecipe, targetRecipe);

		// my update function is very complex which has Validate, Cache to redis, SMS to subscriber and so on
		var result = await mediator.Send<UpdateRecipeQuery>(targetRecipe.Map<UpdateRecipeQuery>()); // <- Can I write this code ?

		return result;
	}

	private void Copy(Recipe source, Recipe target)
    {
		// some code
    }
}
```

**Comment by ajbovaird** [comment]
I'm not 100% sure if there's anything _wrong_ with it, but it can lead to a lot of confusion down the road.

Jimmy Bogard (author of MediatR) recommends you refactor the common code so you can avoid this -- he writes about it here https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/

**Comment by Sokoo92** [comment]
Yeah calling a mediator handler from another mediator handler is considered a anti-pattern. What you could do is leverage a repository class and have the common code in there. Then inject the repository class into the handlers :)

**Comment by RogerBarreto** [comment]
From a Clean Architecture perspective I would say that the responsibility to manage/orquestrate both calls to mediator needs to come from the consumer that originally send it.

Whoever send CopyRecipeCommand should get the targetRecipe as a response and send another Query Request and work with that.

**Comment by MCCshreyas** [comment]
It's not recommended to send another request from request handlers. The purpose of using `MeditR` is just to convert HTTP requests to our application-specific requests and send them into the application layer without letting the controller knows about it or any other presentation layer. 

Once you are in the application layer, you can call anything from database repositories for data, for sending mail using any service, scheduling a task, or anything. 

For example - 
Consider you are working with the management system that manages customer data. And you have a request like `UpdateCustomerData` and you are writing `UpdateCustomerDataRequestHandler` for it. Now first to update the customer, we need to get the details of that customer from the database. Now there are two ways to do so. 
1. Inject repository or `dbContext` in `UpdateCustomerDataRequestHandler` and query that customer using LINQ directly. 
2. Send another MeditR request from `UpdateCustomerDataRequestHandler` to `GetCustomerById` passing the Id, and get that customer details. 

The correct way is the first one! But I have seen people following the 2nd approach as well, which is totally incorrect.

We have `GetCustomerById` and its corresponding handler `GetCustomerByIdQueryHandler` query to handle incoming request which is coming from the "presentation layer" and "not from the application layer itself". 

I know some people may say that then logic gets duplicated to query customer in `UpdateCustomerDataRequestHandler` and `GetCustomerByIdQueryHandler` in both places. Ideally, it's not duplicated, both those requests are separate requests and separate use cases. And also one of the benefits is like let's say there is a new requirement to one of the queries, you can change them without affecting other implementations. But still, if one thinks that a chunk of code is getting duplicated in many request handlers, then you refactor those in static classes or methods, or normal utility classes and can call those from request handlers.

**Comment by mmbeyrem** [comment]
IHO request other commands or queries using mediator is useful when you cross you domain boundaries otherwise you have all design patterns that may help

**Comment by qwas368** [comment]
Thanks for all reply. I refactored using domain service layer.

**Comment by abdu292** [comment]
@qwas368 I understand you created a service interface & its implementation within "Application" layer. Is that correct? If no, could you help me understand what does a "Domain Service Layer" mean & how it is to be done?

I'm in a similar situation as you were & any response on this would be very much appreciated. Thanks a lot!

**Comment by mweel1** [comment]
Ran into the same problem.   I would have code being replicated in multiple command handlers and there was no real place to put that code to reuse it.    Many people from this group said I should have this logic in my domain entity layer.  I ended up not doing that because 9 out of 10 times my need was to update multiple domain entities and rely on infrastructure services.     So instead of updating domain entities sometimes in the entity itself, and then sometimes in an aggregate service I just decided to create an application service that handles services where multiple command handlers need to use it.  I've also kept my domain models anemic.  It's worked out well for me, but this isn't popular belief.

As far as the implementation is concerned, I added services in Application/Common.

**Comment by abdu292** [comment]
@mweel1 Thanks for the response. Looks like I'm in a similar situation as you were. I did the same as you mentioned. It appears to be working well.

Though interested to know other's comments. Especially from @qwas368  as to how he solved the issue.

Thanks again!

**Comment by hanigamini** [comment]
Hello @ShreyasJejurkar
Does the static method take up a lot of memory when a lot of data is exchanged?
What is the best solution to not occupy a lot of memory?

@mweel1 What is the sample code you used? Static method or utility class or service?

Thank you for your guidance
