### ISSUE TITLE
[Question] Where view entities should be located?

### ISSUE THREAD

**Issue by Cododoc** [jasontaylordev/CleanArchitecture#333]
In OnModelCreating method on my DbContext I have this code:

```modelBuilder.Entity<TodoItemView>().HasNoKey().ToView("vReadTodoItems");```

vReadTodoItems - it is SQL view to read some data, that i cant read by linq query.
TodoItemView - wrapper on default TodoItem, that has extra properties.

Is the right place to put my TodoItemView class in Domain layer to Views folder?

**Comment by MCCshreyas** [comment]
You can put those in the Application project instead of Domain. Because it's not a Domain entity as such.
