### ISSUE TITLE
Domain Driven Design Model

### ISSUE THREAD

**Issue by Pyrobolser** [jasontaylordev/CleanArchitecture#34]
Hello, after reading some comments on your latest Youtube videos I read a little bit more about DDD models. It looks like you have been trying to implement some parts with ValueObject for example but not the full thing with aggregate, etc.

What is your opinion on all of this?

I was reading more about it [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model).

**Comment by jasontaylordev** [comment]
Hey @Pyrobolser. I'm not going for a DDD approach as part of this template. I want this approach to be as simple as possible, a starting point for any enterprise app. If I see duplication across commands or queries I would push that logic into the domain. If the domain model was sufficiently complex, I might take a DDD approach right from the beginning. The template provides the flexibility to take either path.

**Comment by Pyrobolser** [comment]
Thank you for the details.
I was thinking about this because I have some Get methods that are either **GetThisForTheCurrentUser** or **GetThisByPrimaryKey** and the query behind this is going to be exactly the same but once I'll just get the primary key from the connected user model first.  
So you'd say to move the queries inside the model in that case?

Thank you for taking some time for us!

**Comment by jasontaylordev** [comment]
Hi again @Pyrobolser. You could move the queries inside the model and maybe reduce duplication of code between the two requests. However, in doing so you would also introduce the potential for breaking changes - in that changing the query to suit **GetThisForTheCurrentUser** could break **GetThisByPrimarykey**. So when the shared query is changed extra care must be taken.

Alternatively, you could keep the duplication and have two separate requests that can change independently of one another. I prefer this approach.

Happy Coding! 😀
