### ISSUE TITLE
[Question] Where to put external services and thier models

### ISSUE THREAD

**Issue by sk0gen** [jasontaylordev/CleanArchitecture#344]
Hello, I have a question regarding external services.
It seems to me that I can create separate projects as persistance.externalX etc. I am using Odata Connected services, which allows me to easily connect to rest api, but adds its models to the same project. How to create dependencies to use this API in the application layer.

Another question is what about connecting to the regular API. Where to create the models that I will consume from the remote API?

**Comment by MCCshreyas** [comment]
Following are the steps that you can follow. 
1. Create an interface for that in the Application project. 
2. Implement that interface in the infrastructure project and register it in dependency injection. (Take a look at how `IApplicationDbContext` and `ApplicationDbContext` are wired together in the existing template.) 
3. Then you can consume those in your request handlers just like any other dependency.
