### ISSUE TITLE
identity in Clean Architecture

### ISSUE THREAD

**Issue by asgharb** [jasontaylordev/CleanArchitecture#349]
hi.
I use Clean architecture and implement identity in presentation layer .
But according to the clean architecture, identity data should not be placed there. Where should Identity packages and folders be located in clean architecture asp core?

**Comment by kingjordan** [comment]
you can see that identity is part of infrastructure.  Look in that project for identity services etc...

**Comment by Bahri-Haythem** [comment]
I faced the same situation as @asgharb where I wanted to reference the ApplicationUser in webUI but according to the best practices infrastructure should only be referenced for DI. Should I create an interface IApplicationUser in the application layer and inject it or what?

**Comment by asgharb** [comment]
> you can see that identity is part of infrastructure. Look in that project for identity services etc...


Why is the ApplicationUser class in the Infrastructure project?

**Comment by MichaelHochriegl** [comment]
I too struggle with this. For learning-purpose I currently build a bug tracker (with Blazor as frontend) and want to use OpenIddict as an IDP. My domain has entities, that need the user (e.g. a project-team consists of many users, a issue/ticket has a user assigned, ...).

How should I best handle this?
