### ISSUE TITLE
[ WIKI ] Misleading Error "The entity type 'DomainEvent' requires a primary key to be defined" explained

### ISSUE THREAD

**Issue by kingjordan** [jasontaylordev/CleanArchitecture#350]
Hello,

I hope this helps someone else.

I get the following error:
_The entity type 'DomainEvent' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'._

This error happens anytime there is an error in the following places:

1.  OnModelCreating method in ApplicationDbContext.cs
2.  Config Method of any _name_Configuration.cs in persistence/configurations folder
3.  Entity class in domain project contains a navigation property/ object  not defined in your model builder / dbsets 

This error is misleading because it does not say what file is generating the error.  It can be any configuration file, entity object or on OnModelCreating() function.  I had to remove them one at a time to figure our where the error was.  This happened when starting up the project and adding lots of the initial entities at the start of the project with navigation properties.

I hope this help someone else

**Comment by kingjordan** [comment]
this error also appears when you inherit an IHasDomainEvent class but don't include the following in the entity configuration:

        public void Configure(EntityTypeBuilder<YourEntity> builder)
        {
            builder.Ignore(e => e.DomainEvents);
        }

**Comment by 1988gadocansey** [comment]
> this error also appears when you inherit an IHasDomainEvent class but don't include the following in the entity configuration:
> 
> ```
>     public void Configure(EntityTypeBuilder<YourEntity> builder)
>     {
>         builder.Ignore(e => e.DomainEvents);
>     }
> ```

this worked for me

**Comment by gabs247** [comment]
Thanks so much, this helped me a lot! I was wondering why it was throwing this error, when only the default ToDoItem had the DomainEvents in there at this stage... hehehe...
