### ISSUE TITLE
Authorized for MVC - Views

### ISSUE THREAD

**Issue by Tbd19** [jasontaylordev/CleanArchitecture#351]
We are using the ClearArhitecture template for an asp.net core web application using MVC. We got to the point where we need to implement Authorization and I got to the view authorization.

The action is something like this

public ActionResult XXX()
{
    return View();
}

now the action XXX needs to be restricted based on some roles.

What is the suggested thing to do in this case?

Create a command that just takes advantage of the authorized behaviour and returns nothing? use the authorized from the asp.net core using claims?

**Comment by PilotBob** [comment]
In my opinion, it depends. You could use asp.net authentication attributes to protect your endpoints and it would work. Assuming you don't have any other presentation layer that uses your application layer. 

What you might want to do is push the auth into your application layer...

Handled by the AuthorizationHandler behavior combined with the AuthorizeAttribute in the Application layer. That combined with an ExceptionFilter in the Web layer should get you where you want to go. But of course, there's more than one way to skin that cat. Sadly I don't see anything in the template that provides a sample for that stuff. 

Also, if you have auth requirements beyond roles/claims, you might want to create some custom validators. Stuff like, Does this user have a subscription type of stuff. Then you might want to look at this approach: https://levelup.gitconnected.com/handling-authorization-in-clean-architecture-with-asp-net-core-and-mediatr-6b91eeaa4d15

Anyway, just another guy trying to find my way to clean architecture. :)

**Comment by Tbd19** [comment]
I do not think you understood my question. I already have the authorized handler behavior and I am asking what should I do with the actions on the controller where I do not call any command or query (hence the authorization handler behavior is not called)

Do I create create a command/query for every action regardless if it returns something or not?
Or
Do I remove the authorization handler behavior and handle the authorization using the asp.net authentication and authorization attributes?

At this moment the requirement is to use only roles for authorization and I do not think that it will change.

**Comment by jasontaylordev** [comment]
Generally, I'd try to move the logic out of the controllers into new commands and queries.
If you can't do that - just use authorisation at the API layer only.
