### ISSUE TITLE
CountAsync() and ToListAsync() replacement to remove Entity Framework reference in Application project

### ISSUE THREAD

**Issue by bitbehz** [jasontaylordev/CleanArchitecture#362]
**Application** project is using **CountAsync()** and **ToListAsync()** extension methods which are part of EF.
What can be done to replace those methods and remove EF reference?
If another O/R mapper is used, referencing EF is not a good idea.

**Comment by jasontaylordev** [comment]
To remove the reference to EF you can implement the repository and unit of work patterns. This is a good starting point - https://docs.microsoft.com/en-us/aspnet/mvc/overview/older-versions/getting-started-with-ef-5-using-mvc-4/implementing-the-repository-and-unit-of-work-patterns-in-an-asp-net-mvc-application#implement-a-generic-repository-and-a-unit-of-work-class.
