### ISSUE TITLE
Support enumeration based on DDD

### ISSUE THREAD

**Issue by FaizulHussain** [jasontaylordev/CleanArchitecture#365]
This is good solution setup. I would also add enumeration class for enum types, and change the casing to camel case for client side code generation including Swagger UI examples

Otherwise great work, thanks for sharing

**Comment by jasontaylordev** [comment]
Thanks for your feedback. 

I agree, sometimes it's great to use enumeration classes instead of enum types, but sometimes, for simplicity, I'll just stick with regular enum types. 

Regarding camel vs. pascal case - you can configure that within *WebUI\nswag.json*.
