### ISSUE TITLE
Can I use MediatR.Send (send and receive requests) within Application Layer? How?

### ISSUE THREAD

**Issue by AliGhIO** [jasontaylordev/CleanArchitecture#368]
Hi,
### Use MediatR.Send (send and receive requests) within Application Layer
For example I have a query wich get cities of a country and also I have another query that get list of countries and list of cities of each country. I want to call `GetCitiesQuery` with **MediatR** inside of `GetCountriesQuery`.
How to do that?

**Comment by se-trofimov** [comment]
@AliGhIO It is not good idea. If you don't want repeat yourself try to write some service that contains GetCleints method and use this one in both mediator queries

**Comment by PedroVentura235** [comment]
@se-trofimov @AliGhIO  Hi, do you have any example or can explain how to implement the common service?

**Comment by se-trofimov** [comment]
@PedroVentura235  It is not difficult. 
Define IService and its implementation in Application Layer.

E.g. you have two Queries `GetCitiesQuery `  and `GetCountriesQuery`. Both have code like 

`var cities = _context.City.Where(x=>x.CountryId == id).ToListAsync();`

Create the Servise 

```
public class CitySelectorService  : ICitySelectorService
{
            public Task<List<City>> GetCitiesByCountryIdAsync (Guid countryId);
}
```

after that you can use this service inside your Handlers by injection

```

public class GetCitiesQueryHandler: IRequestHandler<GetCitiesQuery, List<City>>
{
     ICitySelectorService _citySelector;
     public GetCitiesQueryHandler(ICitySelectorService citySelector)
     {
          _citySelector = citySelector;
     }
     public Task< List<City>> Handle (GetCitiesQuery request, CancellationToken token)
     {
          return _citySelector.GetCitiesByCountryId(request.Id);
     }
}
```

**Comment by jasontaylordev** [comment]
Check out these resources:
1. https://lostechies.com/jimmybogard/2016/12/12/dealing-with-duplication-in-mediatr-handlers/
2. https://youtu.be/WfG_WSQo0Fw

**Comment by abdu292** [comment]
@se-trofimov Thanks for the answer. So both interface & implementation will be in a separate folder called "Services" within "Application" project?

I appreciate your time if you could respond. Thanks a alot.

(Sorry for asking on a closed ticket, but this ticket  gives more context for my question.)
