### ISSUE TITLE
[Question] How to perform operations for multiple domain from a single command

### ISSUE THREAD

**Issue by farhanchew** [jasontaylordev/CleanArchitecture#369]
Lets say I have the following domains
- CompanyRegistration
- Company 
- ApplicationUser
- Employee (**Note: has UserId**)

Upon completing CompleteCompanyRegistrationCommand, I want to create a Company, ApplicationUser and Employee(**ApplicationUser needs to be created first for the UserId**). 
My opinion, all of this should not be done in a single command as some of it will be taken out into different microservice.
How do I achieve the flow? using Domain Event?

**Comment by ODumpling** [comment]
Domain Events would be what you want to use.

Please also look at [Microsoft Domain Events](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation)

They use domain events to create other entities.

**Comment by farhanchew** [comment]
Thanks @ODumpling for the answer. I'm closing this thread. 👍
