### ISSUE TITLE
Installation instructions don't work on Mac

### ISSUE THREAD

**Issue by danrocks** [jasontaylordev/CleanArchitecture#37]
**Describe the bug**
Following the installation instructions when using a Mac does not result in installation of Nuget package.

**To Reproduce**
1. Go to Mac Terminal
2. Type "dotnet new -i Clean.Architecture.Solution.Template"
3. Press Return
```
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.0.1/System.Native.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

**Expected behavior**
Running installation on Mac should result in same behaviour as a PC and running the instruction should cause cs-sln template to be available to create a new VS solution with. 

If the template does not work on a Mac, this should be clear and explicit on the GitHub readme.md.

**Additional context**
I am not generally a Mac user but it was first to hand when I wanted to try out Clean Architecture after watching presentation at NDC Sydney.

**Comment by teamsmiley** [comment]
i test on my computer it works fine . 

can you try again? 
maybe you need install dotent core 3.1 sdk on your mac before you install 

i did this 

## dotnet core 
```bash
# latest
brew cask install dotnet-sdk
# oldversion
brew tap isen-ng/dotnet-sdk-versions
brew cask install dotnet-sdk-2.2.400
# check
dotnet --list-sdks
```

**Comment by danrocks** [comment]
Hi.

I'm pretty sure I got everything up to date but I'll try again with the script you sent. I'm away from computer s right now should manage on Thursday.

Thanks for getting back to me and happy new year.

Daniel

email: danieljohnkerr@hotmail.com mobile: 07921 469 720 skype: danieljohnkerr
________________________________

**Comment by danrocks** [comment]
Hi.

Based on your email, I removed the latest version of dotnet-sdk:


sudo rm -rf /usr/local/share/dotnet/sdk/3.1.100

sudo rm -rf /usr/local/share/dotnet/sdk/3.0.101


Then I was able to successfully run


dotnet new --install Clean.Architectu​re.Solution.Template

and

dotnet new ca-sln

Excellent.

The solution opened but immediately reported problems on the package manager (sorry I didn't record these). Essentially I had to re-install dotnet-sdk 3.1. I suppose this is all because projects application and domain target netstandard2.1 while WebUi and Infrastructure target netcoreapp3.1.

I also had to amend WebUi and Infrastructure project files to include <LangVersion>8.0</LangVersion>, otherwise there was an error regarding using declarations not being supported in c#7.3.

I can now navigate to https://localhost:5001/api/index.html?url=/api/specification.json, so any problems from here will be of my own making.

your script suggesting the template would install with dotnet-sdk-2.2.400 was the hint I needed. Thank you very much for that.

regards


Daniel

email: danieljohnkerr@hotmail.com mobile: 07921 469 720 skype: danieljohnkerr

________________________________

**Comment by jasontaylordev** [comment]
Hi all. Thanks for working through these issues. I've published a new post https://jasontaylor.dev/clean-architecture-getting-started. Let me know if you think any updates are required for Mac users.
