### ISSUE TITLE
Can you create a schedule jobs solution?

### ISSUE THREAD

**Issue by andrerocha** [jasontaylordev/CleanArchitecture#370]
I need create a schedule jobs. This is possible using the same structure?

Maybe use job worker or any other idea as quartz etc..

Anybody have any idea?

**Comment by neman** [comment]
Yes it is possible. I used background tasks, which executes commands from Application layer.

**Comment by litan1106** [comment]
I used Hangfire with Mediatr. it worked great.

**Comment by shobhitvaish** [comment]
> I used Hangfire with Mediatr. it worked great.

Mind sharing an example?

**Comment by MARKUSER** [comment]
1. I am looking for some help on the same. Using this project template i have started building the code. I have API project and at the same time i wanted to create .net core WorkerService (like windows application) to process CSV and EXCEL files. Any pointers to using this template with WorkerService will be of great help.
2. I would like to create some reusable logic between API and WorkerService so is it a good idea to create new libraries and call them from Application layer handlers ?

**Comment by MARKUSER** [comment]
> Yes it is possible. I used background tasks, which executes commands from Application layer.

can you help on my question above ?
