### ISSUE TITLE
Copy-paste issue in TodoItemCreatedEventHandler ^.^

### ISSUE THREAD

**Issue by 5317169** [jasontaylordev/CleanArchitecture#373]
**Describe the bug**
Seems like copy-paste issue when creating _TodoItemCreatedEventHandler.cs_ from _TodoItemCompletedEventHandler.cs_ because ILogger field have "wrong" type.

**Screenshots**
![copy-paste-issue](https://user-images.githubusercontent.com/12436047/122683557-9ec1bb80-d208-11eb-8751-6219b165d000.png)

**Comment by jasontaylordev** [comment]
Thanks, fixed.
