### ISSUE TITLE
Antipattern with shared DTO

### ISSUE THREAD

**Issue by BretMishler** [jasontaylordev/CleanArchitecture#383]
As I understand it from the documentation and YouTube video relating to this architecture, all ViewModels and DTOs for a given query or command should live within that query or commands directory -- meaning the VM/DTO should only ever be used by the one-and-only-one query/command that invokes it. This reinforces a practice so that developers modifying one DTO or VM for a given query/command won't break it for other queries/commands throughout the project.

`Application.TodoItems.Queries.GetTodoItemsWithPagination.GetTodoItemsWithPaginationQuery.cs`

creates, relies on, and returns the `TodoItemDto` within a different query. Specifically, a query within

`Application.TodoLists.Queries.GetTodos.TodoItemDto.cs`

Isn't this an antipattern to this architecture? A developer now is at risk of modifying a query/command's Dto and breaking it for a query/command elsewhere within the solution.

Thank you!

**Comment by jasontaylordev** [comment]
Thanks for pointing this out, it's fixed.
