### ISSUE TITLE
How to use IDesignTimeDbContextFactory

### ISSUE THREAD

**Issue by rmeshksar** [jasontaylordev/CleanArchitecture#388]
Hi, 
I would like to have a DesignTimeDbContextFactory similar to this:

https://github.com/jasontaylordev/NorthwindTraders/blob/master/Src/Persistence/NorthwindDbContextFactory.cs

How can I do this considering ApplicationDbContext has several dependencies injected in the constructor?

Thanks.

**Comment by jasontaylordev** [comment]
Hi, this is not something I am looking to implement in the template.
