### ISSUE TITLE
How to proceed in replace angular project

### ISSUE THREAD

**Issue by PedroVentura235** [jasontaylordev/CleanArchitecture#389]
Hi, how to proceed if i want to replace the current client app to , for example this one ( https://themeforest.net/item/apex-angular-4-bootstrap-admin-template/20774875 ) ? 
I want to mantain the api connection, the auto generated nswagg

**Comment by jasontaylordev** [comment]
Generally speaking, just replace the contents of ClientApp with a new Angular app. The TypeScript client will still be generated to the same path everytime you build the WebUI project. It will help to be familiar with the project template - learn more here; https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-5.0&tabs=visual-studio. Happy coding!
