### ISSUE TITLE
API versioning & swagger UI

### ISSUE THREAD

**Issue by LucaGabi** [jasontaylordev/CleanArchitecture#39]
**Is your feature request related to a problem? Please describe.**
Enable multiple API versions and the way to display those in the swagger UI.

**Comment by jasontaylordev** [comment]
Hi @LucaGabi. This is not a concept I am looking to cover as part of this repository. You should be able to find some use resources elsewhere, e.g. https://dejanstojanovic.net/aspnet/2018/november/setting-up-swagger-to-support-versioned-api-endpoints-in-aspnet-core/. Happy coding!
