### ISSUE TITLE
[Question] Migration doesn't work

### ISSUE THREAD

**Issue by ppp3** [jasontaylordev/CleanArchitecture#391]
Hello,
I have added three classes Book, Customer and Order to the Entities directory and added the these commands to ApplicationDbContext.cs:
public DbSet<Customer> Customers{ get; set; }
public DbSet<Book> Books { get; set; }
public DbSet<Order> Orders { get; set; }
 
add-migration SampleMigration -project src\Infrastructure -startupproject src\WebUI -outputdir Persistence\Migrations
Build started...
Build failed.
 
Migration not possible. Build failed. Can anybody give me some hints?

**Comment by EliuTimana** [comment]
> public DbSet Customers{ get; set; }
> public DbSet Books { get; set; }
> public DbSet Orders { get; set; }

```cs
public DbSet<Customer> Customers{ get; set; }
public DbSet<Book> Books { get; set; }
public DbSet<Order> Books { get; set; }
```

**Comment by jasontaylordev** [comment]
In addition, make sure you update **appsettings.json** to ensure that use in-memory database is disabled:

```json
"UseInMemoryDatabase": false,
```

I tend to use the .NET CLI for managing migrations. If you want to try, here is an example:

```bash
cd .\src\Infrastructure
dotnet ef migrations add SampleMigration -s ..\WebUI
```

You don't need to specify the output dir path if there is an existing migration.

Assume this will get you up and running, so closing the issue. Let me know if you run into further problems.

**Comment by ppp3** [comment]
What a silly mistake. Thank you.
