### ISSUE TITLE
Social Login and Password Reset

### ISSUE THREAD

**Issue by Pyrobolser** [jasontaylordev/CleanArchitecture#4]
**Issue**
I would like to really understand how to add some of the classic things explained in the Microsoft Documentation (like social login) but with the SPA application. I am going to try but myself but I would love to see your solution for this.

For example the solution [described here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-3.0&tabs=visual-studio)

Once again, I am going to try and implement this by myself. I would like users to be able to authenticate with an account, or Facebook/Google/Twitter, to be able to link those accounts together as their accounts and to have different roles in the application. I need to fill the gap between your implementation that I love for its simplicity to these features that are necessary for me.

Quick question, is there an easy way to extend this model to add some extra user data like date of birth, etc.?

Thanks again for all your work on this and Northwind Traders it is really appreciated.

**Comment by InvisibleProgrammer** [comment]
What about splitting this issue into two:
- Social Login
- Password Reset

**Comment by jasontaylordev** [comment]
Hi @Pyrobolser - sorry for the late reply - I have trouble keeping up.

> Quick question, is there an easy way to extend this model to add some extra user data like date of birth, etc.?

I am sure you've figured it out by now but for others - customising the model is straight-forward; check this resource - https://docs.microsoft.com/en-us/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-3.1#customize-the-model.

>I would like users to be able to authenticate with an account, or Facebook/Google/Twitter, to be able to link those accounts together as their accounts and to have different roles in the application.

Adding external identity providers should be straight-forward too - https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/?view=aspnetcore-3.1&tabs=visual-studio.

Happy Coding! 😀
