### ISSUE TITLE
Telegram Group or Discord Server

### ISSUE THREAD

**Issue by mohammedbabelly** [jasontaylordev/CleanArchitecture#413]
I think it would be very helpful for all of us if you can create a Telegram group or Discord server so all of us can discuss the template details.

**Comment by RazvanBd** [comment]
I think we can still use [discussions ](https://github.com/jasontaylordev/CleanArchitecture/discussions) page of the git repo.

**Comment by jasontaylordev** [comment]
Done - https://discord.gg/p9YtBjfgGe
