### ISSUE TITLE
Why does the Application layer depend on EF Core

### ISSUE THREAD

**Issue by swrocket** [jasontaylordev/CleanArchitecture#42]
I am new to CA and found this repo extremely helpful in learning so this is more of a question than a feature request.
I noticed that in the Application layer (project) you define a DBContext interface (IApplicationDbContext) which requires you to add EF Core dependency to the Application project.
It seems to me that EF Core is an infrastructure concern, so I'm wondering why you did it this way vs, say, defining a Repository or Service interface and have the implementation in the infrastructure project.

**Comment by larrygeo** [comment]
I had the same question about having dependency on EF core at the application level but EF is already an abstraction and implements the repository pattern (DbSet) ans UnitOfWork (DbContext) and the key point is that infrastructure depends on core (Application) and this change is huge.
So now changing the database it becomes much flexible and easier to achieve in general
If for some reasons you don't want to have a dependency on ORM you can still implement the repository pattern.

**Comment by sq735** [comment]
I have the another question about having dependency on external libraries, for example: MediatR and FluentValidation. Is it Ok?

**Comment by jasontaylordev** [comment]
In relation to Clean Architecture, we should aim to be independent of frameworks and database. In the usage of EF Core (an abstraction as @larrygeo has mentioned), I am not independent of a framework but still independent of the database. If I wanted to strictly adhere to these principles I would implement the repository / UoW patterns. The same goes for MediatR and FluentValidation.   However, if I head down that road, I feel that I would be overcomplicating the solution, for very little gain. I don't want to end up with a 150 project solution when 4 project solution meets my needs perfectly. If I have to move away from one of these frameworks in the future, I'll deal with the pain then.

Open for further discussion. Thoughts?
