### ISSUE TITLE
Microsoft.EntityFrameworkCore dependency in Application layer

### ISSUE THREAD

**Issue by vccampbell** [jasontaylordev/CleanArchitecture#439]
Hi. I was curious if we should have a dependency on the database ORM within the Application layer? Specifically we're referencing Microsoft.EntityFrameworkCore in Application > TodoLists > Queries > GetTodos > GetTodosQuery.cs. Seems like this should be abstracted away from the business logic, maybe opting for Repository pattern to inject specific functionality. 

`private readonly ITodoRepository todosRepository;`
`public GetTodosQueryHandler(ITodosRepository todosRepository)`
`{`
 ` this.todosRepository = todosRepository;`
`}`
`public async Task<TodosVm> Handle(GetTodosQuery request, CancellationToken cancellationToken)`
`{`
   `// ...`
`  Lists = await todosRepository.GetTodoListsAsync(cancellationToken);`
`}`

Appreciate any advice/guidance.

**Comment by ronnieholm** [comment]
That's quite deliberate. I believe Jason covers why in his talk.

That dependency is there because it's the database agnostic part of Entity Framework. The MS SQL server dependency is in Infrastructure.

Sure, you can abstract it away behind a repository, but then you have a repository wrapping a repository (`DbSet<T>` is a repository). It would result in boilerplate code that in most cases would serve no real purpose.

**Comment by vccampbell** [comment]
Hi @ronnieholm, thank you for the reply and it makes perfect sense. If my application had a mix of EF and Dapper, would the recommended implementation be to abstract the Dapper bits behind a repository? 

Thanks again.

**Comment by seoriy** [comment]
@karimkod 

> Uncle bob also made an exception by saying

I think he was talking about a bit other cases. I.e. if you use .NET Framework to write application, it's obvious, that you use BCL even to describe domain logic, so you may use System.Collections.Generic.List<> for domain logic, without treating it as a violation of The Dependency Rule. Same for IDisposable, LINQ, etc.
And right after that paragraph he saying:

> CONCLUSION
> When faced with a framework, try not to marry it right away. See if there aren’t
> ways to date it for a while before you take the plunge. **Keep the framework behind
> an architectural boundary if at all possible, for as long as possible**. Perhaps you can
> find a way to get the milk without buying the cow.

Also

> Jason said that's he is ok with coupling with EntityFramework since he used it for a very very long time.

It's only his personal choise. Someone else may want to use this template, but replacing EF Core with Dapper, for example...

**Comment by karimkod** [comment]
@seoriy Yes, the conclusion was for the chapter, the section above it was for setting the exception.

And yes, everything is relative. As I said before, you can change this template to match your own definition. 

And again, this is not an absolute solution/template everything is flexible, you can build on it, change it, make it perfect for your own decisions.
