### ISSUE TITLE
Why is CurrentUserService implemented in WebUI?

### ISSUE THREAD

**Issue by bbarry** [jasontaylordev/CleanArchitecture#44]
The fact that this application is using Identity with a JWT is hidden coupling within the Infrastructure project, so this project implicitly knows that it is a .net core web application already. 

I feel like there is a disconnect here: either the web specific infrastructure should be in the web project, or the current user service should be in the infrastructure project. 

Currently I am trying to support multiple databases based on incoming CORS request api keys (what I have is working); the general gist is:

in CleanArchitecture.Infrastructure.DependencyInjection:

            var appSettingsSection = Configuration.GetSection("AppSettings");
            services.Configure<AppSettings>(appSettingsSection);
            var appSettings = appSettingsSection.Get<AppSettings>();

            services.AddCors(options =>
            {
                options.AddDefaultPolicy(policy =>
                    policy
                        .WithOrigins(appSettings.Keys.Select(k => k.Value.Origin).Distinct().ToArray())
                        .AllowAnyHeader()
                        .AllowAnyMethod()
                        .AllowCredentials()
                        .WithExposedHeaders("authorization")
                );
            });

            services.AddDbContext<ApplicationDbContext>((serviceProvider, builder) => 
            {
                var connectionString = serviceProvider.GetRequiredService<IConnectionStringService>().ConnectionString;
                builder.UseSqlServer(connectionString,
                    b => b.MigrationsAssembly(typeof(ApplicationDbContext).Assembly.FullName));
            });

            // ...

and IConnectionStringService has an infrastructure implementation (calling some legacy code to return a connection string based on client id) which in turn depends on an IClientService implementation which the web application would provide as:

    public class ClientService : IClientService
    {
        public ClientAccessService(IHttpContextAccessor httpContextAccessor, IOptions<AppSettings> appSettings)
        {
            if (httpContextAccessor == null) throw new ArgumentNullException(nameof(httpContextAccessor));
            if (appSettings == null) throw new ArgumentNullException(nameof(appSettings));

            Client = GetClient(httpContextAccessor, appSettings);
        }

        public string? Client { get; }

        private string? GetClient(IHttpContextAccessor httpContextAccessor, IOptions<AppSettings> appSettings)
        {
            var context = httpContextAccessor.HttpContext;
            if (context == null) return null;
            var key = context.Request.Headers["x-api-key"];
            var origin = context.Request.Headers["origin"];
            if (!string.IsNullOrEmpty(key) && appSettings.Value.Keys.TryGetValue(key, out var value))
            {
                if (string.IsNullOrEmpty(value.Origin) || string.Equals(value.Origin, origin, StringComparison.OrdinalIgnoreCase))
                {
                    return value.Client;
                }
            }

            return null;
        }
    }

And so I am left with a conundrum, this implementation has basically the same requirements that ClientUserService has (a specific header must exist on the web request) and it provides a service the same way that the latter does (associated with a behavior on the mediatr pipeline), but it also depends on my configuration details, which I am putting in Infrastructure because that is where I am configuring CORS and authentication.

**Comment by grinay** [comment]
Because  CurrentUserService getting user's data from HttpContext which is part of the WebUI layer and it shouldn't leak to other layers with higher level. 
Of course there can b even more abstraction like InfrastructureWeb and then WebUI, but in my opinion it 's just redundant.
