### ISSUE TITLE
What is the docker compose override file for?

### ISSUE THREAD

**Issue by smartsense-as** [jasontaylordev/CleanArchitecture#447]
I am having trouble understanding whey the docker compose overrides file exists,

Why is this not just included in the main docker compose file?

Specifically why was it chosen to put the "clientapp" part inside of this override file?

Would appreciate any clarification anyone can give me, thanks in advance!

**Comment by javiergardella** [comment]
I have the same doubt.
I add an observation:
If you run the command specified in the clean architecture GitHub page "docker-compose -f 'docker-compose.yml' up --build" it will create two images. One related to WebUI and another related to SQL database.
But if you run the "Docker Compose" from Visual Studio it will add one more image, the related with the clientapp.
If you check the command that runs Visual Studio, you will note that considered the overrides file.

So... it is not the same. 

Please help!

**Comment by deceptiveSimplicity** [comment]
I think the docker-compose.override.yml is for local development.
- it exposes port 1433 of MS SQL Server container, so u can connect from ur host machine
- it starts an angular dev server, because the WebAPI will forward requests to it

**Comment by justin6302971** [comment]
from my understanding, I think it  just a way to isolate the canonical configuration with environment specific settings, for example you could have different settings and commands as below

``` bash
# the same effect as you run docker-compose up -d 
 docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d 

# choose the specific file and combine it with canonical file
 docker-compose -f docker-compose.yml -f docker-compose.environment.specific.yml up -d 
 ```
you can use` docker-compose config ` to check what's the exact docker-compose file content you're trying to run
 

correct me if I'm wrong

**Comment by jasontaylordev** [comment]
FYI I have removed support for docker as per #630
