### ISSUE TITLE
500 status code not showing full details in log file

### ISSUE THREAD

**Issue by suicodave** [jasontaylordev/CleanArchitecture#448]
**Describe the bug**
Hi all, I have just deployed my app to production. Usually, when I encounter 500 status codes after deploying for the 1st I just go to the logs folder and see the full details about such error. However, in this template that I am using now, the response of the webapi only throws 500 status and by checking the logs it doesn't show all the stack traces.

**Expected behavior**
It is expected to show full details for unknown errors.
![500](https://user-images.githubusercontent.com/28585323/133958340-9adc5474-9876-4bd7-97ff-cba745d2df89.jpg)

**Comment by ageisen2000** [comment]
I think you can tweak the "Logging" property in appsettings.Production.json to your needs. 

TBH I usually swap out the default logger implementation with nlog/elmah/serilog or something similar

**Comment by jasontaylordev** [comment]
Thanks for reporting this issue, it has now been fixed
