### ISSUE TITLE
Browser got console errors and cannot login when `dotnet run`. However, it works in visual studio?

### ISSUE THREAD

**Issue by nkw** [jasontaylordev/CleanArchitecture#45]
**Describe the bug**
I followed the steps, added the template and created a new project. And use `dotnet run`. Browser can open the page. However, it got the following error in the javascript console and login doesn't work.

zone-evergreen.js:1042 GET http://localhost:58600/_configuration/padmatch.WebUI 404 (Not Found)
(anonymous) @ zone-evergreen.js:1042
(anonymous) @ authorize.service.ts:177
(anonymous) @ authorize.interceptor.ts:10
ZoneAwarePromise @ zone-evergreen.js:876
push../src/api-authorization/authorize.service.ts.__awaiter @ authorize.interceptor.ts:10
ensureUserManagerInitialized @ authorize.service.ts:172
getUserFromStorage @ authorize.service.ts:194
getUser @ authorize.service.ts:54
isAuthenticated @ authorize.service.ts:48
ngOnInit @ login-menu.component.ts:18
checkAndUpdateDirectiveInline @ core.js:24489
checkAndUpdateNodeInline @ core.js:35151
checkAndUpdateNode @ core.js:35090
debugCheckAndUpdateNode @ core.js:36112
debugCheckDirectivesFn @ core.js:36055
eval @ NavMenuComponent.html:10
debugUpdateDirectives @ core.js:36043
checkAndUpdateView @ core.js:35055
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callWithDebugContext @ core.js:36395
debugCheckAndUpdateView @ core.js:35978
detectChanges @ core.js:23793
tick @ core.js:32067
_loadComponent @ core.js:32118
bootstrap @ core.js:32041
(anonymous) @ core.js:31663
_moduleDoBootstrap @ core.js:31659
(anonymous) @ core.js:31614
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30892
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:31644
./src/main.ts @ main.ts:19
__webpack_require__ @ bootstrap:78
0 @ main.ts:20
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 13 more frames
zone-evergreen.js:1042 GET http://localhost:58600/_configuration/padmatch.WebUI 404 (Not Found)
(anonymous) @ zone-evergreen.js:1042
(anonymous) @ authorize.service.ts:177
(anonymous) @ authorize.interceptor.ts:10
ZoneAwarePromise @ zone-evergreen.js:876
push../src/api-authorization/authorize.service.ts.__awaiter @ authorize.interceptor.ts:10
ensureUserManagerInitialized @ authorize.service.ts:172
getUserFromStorage @ authorize.service.ts:194
getUser @ authorize.service.ts:54
ngOnInit @ login-menu.component.ts:19
checkAndUpdateDirectiveInline @ core.js:24489
checkAndUpdateNodeInline @ core.js:35151
checkAndUpdateNode @ core.js:35090
debugCheckAndUpdateNode @ core.js:36112
debugCheckDirectivesFn @ core.js:36055
eval @ NavMenuComponent.html:10
debugUpdateDirectives @ core.js:36043
checkAndUpdateView @ core.js:35055
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callWithDebugContext @ core.js:36395
debugCheckAndUpdateView @ core.js:35978
detectChanges @ core.js:23793
tick @ core.js:32067
_loadComponent @ core.js:32118
bootstrap @ core.js:32041
(anonymous) @ core.js:31663
_moduleDoBootstrap @ core.js:31659
(anonymous) @ core.js:31614
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30892
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:31644
./src/main.ts @ main.ts:19
__webpack_require__ @ bootstrap:78
0 @ main.ts:20
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 12 more frames
core.js:7187 ERROR Error: Uncaught (in promise): Error: Could not load settings for 'padmatch.WebUI'
Error: Could not load settings for 'padmatch.WebUI'
    at AuthorizeService.<anonymous> (authorize.service.ts:179)
    at Generator.next (<anonymous>)
    at fulfilled (authorize.interceptor.ts:10)
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:30892)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30873)
    at resolvePromise (zone-evergreen.js:797)
    at zone-evergreen.js:707
    at fulfilled (authorize.interceptor.ts:10)
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:30892)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30873)
defaultErrorLogger @ core.js:7187
handleError @ core.js:7239
next @ core.js:31602
schedulerFn @ core.js:27834
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:27796
(anonymous) @ core.js:30931
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:30818
onHandleError @ core.js:30928
handleError @ zone-evergreen.js:363
runGuarded @ zone-evergreen.js:137
api.microtaskDrainDone @ zone-evergreen.js:663
drainMicroTaskQueue @ zone-evergreen.js:566
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
resolvePromise @ zone-evergreen.js:791
(anonymous) @ zone-evergreen.js:707
Promise.then (async)
(anonymous) @ zone-evergreen.js:1033
ZoneAwarePromise @ zone-evergreen.js:876
Ctor.then @ zone-evergreen.js:1032
resolvePromise @ zone-evergreen.js:758
(anonymous) @ zone-evergreen.js:707
(anonymous) @ authorize.interceptor.ts:10
ZoneAwarePromise @ zone-evergreen.js:876
step @ authorize.interceptor.ts:10
(anonymous) @ authorize.interceptor.ts:10
ZoneAwarePromise @ zone-evergreen.js:876
push../src/api-authorization/authorize.service.ts.__awaiter @ authorize.interceptor.ts:10
ensureUserManagerInitialized @ authorize.service.ts:172
getUserFromStorage @ authorize.service.ts:194
getUser @ authorize.service.ts:54
ngOnInit @ login-menu.component.ts:19
checkAndUpdateDirectiveInline @ core.js:24489
checkAndUpdateNodeInline @ core.js:35151
checkAndUpdateNode @ core.js:35090
debugCheckAndUpdateNode @ core.js:36112
debugCheckDirectivesFn @ core.js:36055
eval @ NavMenuComponent.html:10
debugUpdateDirectives @ core.js:36043
checkAndUpdateView @ core.js:35055
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callViewAction @ core.js:35421
execComponentViewsAction @ core.js:35349
checkAndUpdateView @ core.js:35062
callWithDebugContext @ core.js:36395
debugCheckAndUpdateView @ core.js:35978
detectChanges @ core.js:23793
tick @ core.js:32067
_loadComponent @ core.js:32118
bootstrap @ core.js:32041
(anonymous) @ core.js:31663
_moduleDoBootstrap @ core.js:31659
(anonymous) @ core.js:31614
invoke @ zone-evergreen.js:359
onInvoke @ core.js:30892
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:855
invokeTask @ zone-evergreen.js:391
onInvokeTask @ core.js:30873
invokeTask @ zone-evergreen.js:390
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
then @ zone-evergreen.js:955
bootstrapModule @ core.js:31644
./src/main.ts @ main.ts:19
__webpack_require__ @ bootstrap:78
0 @ main.ts:20
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 46 more frames
2core.js:7187 ERROR Error: Could not load settings for 'padmatch.WebUI'
    at AuthorizeService.<anonymous> (authorize.service.ts:179)
    at Generator.next (<anonymous>)
    at fulfilled (authorize.interceptor.ts:10)
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:30892)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30873)

**To Reproduce**
1. dotnet new --install Clean.Architecture.Solution.Template
2. Run dotnet new ca-sln to create a new project
3. cd src\WebUi
4. dotnet run
5. open the browser on http://localhost:xxxxx/ 

**Expected behavior**
The login page shows the boxes

**Screenshots**
![image](https://user-images.githubusercontent.com/888007/71777018-9c15cc80-2f68-11ea-8929-e0789fbd4f47.png)

**Additional context**
However, open the .sln file using visual studio 2019, there is no javascript console error and the login page works. (Both run as IIS Express or kestrel)

**Comment by jasontaylordev** [comment]
Sorry for your troubles @nkw. Please work through my latest blog post and see if that helps you get up and running; https://jasontaylor.dev/clean-architecture-getting-started/.

Otherwise, report back with your issue here and I'll help.
