### ISSUE TITLE
Multiple Microservices with API gateway

### ISSUE THREAD

**Issue by cpm205** [jasontaylordev/CleanArchitecture#46]
Hi Jason,

What's the best way to implement CleanArchitecture for multi-microservices with an API Gateway?
Do you have any suggestion?

Regards,
Derek Hu

**Comment by jasontaylordev** [comment]
Hi Derek. Thanks for your question. Apologies, however, I don't have time to invest in this right now since it is not a core concept I am trying to demonstrate as part of this repository.

Suggest that you take a look at https://github.com/dotnet-architecture/eShopOnContainers. Happy coding!
