### ISSUE TITLE
This is not exactly The Clean Architecture style

### ISSUE THREAD

**Issue by seoriy** [jasontaylordev/CleanArchitecture#464]
It might looks like Clean Architecture, but actually, it doesn't. The original principles are described here - https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html 
The main principle of The Clean Architecture - The Dependency Rule, is broken in Application project, because it has reference to  EF Core. Business layers must not depend on infrastructure layers, but commands use DbSet<> directly, to deal with data. It doesn't comply with The Clean Architecture principles.

> The **overriding rule that makes this architecture work** is The Dependency Rule. This rule says that source code dependencies can only point inwards. Nothing in an inner circle can know anything at all about something in an outer circle. In particular, the name of something declared in an outer circle must not be mentioned by the code in the an inner circle. That includes, functions, classes. variables, or any other named software entity.

Also, domain entities in this solution more looks like a persistent layer entities, rather than domain layer entities.
The purpose of domain layer is to have pure domain abstractions and logic which are independent from application specific. Project may be called "Domain" and has some POCO classes, but if these entities are used mostly as EF Core entities, this is not a domain layer, actually...

> They are the least likely to change when something external changes. For example, you would not expect these objects to be affected by a change to page navigation, or security. No operational change to any particular application should affect the entity layer.

It might looks like over-engineering to use separate entities levels for persistence and for domain layers, and all that mappings... Believe me, I'm pretty know, how annoying might be all these mappings! But there are reasons for that. This template solution is just relatively simple and didn't show all possible design issues which might appear in real-life applications... I.e., lets imagine, that we have two entities with many-to-many relation between them - Employee and Company. Yes, I know, this template is for .Net 5, but how about to apply this approach for .NET Core 3.1? In that case, we will need to have some intermediate joint entity to connect Employee with Company and vice versa, right? And queries to DB should use that entities to get related companies by employee and vice versa. But what about domain? do we really need this intermediate entity? The answer is NO, that entity is a persistence layer implementation details only, and it has no sense for domain logic. It useless for a domain logic and business logic. If you would have some other storage type with it's own ORM framework it might not needed in these entities, but it might use some other persistence-only entities. If you have a lot of many-to-many relations domain layer and business logic became harder to read and maintain in that case.

Other problem with Application layer, which uses DbSet<> directly, that it doesn't have unit tests for commands, only integration tests. It's is definitely better to check _business logic_ of a command with unit tests instead of integration tests... Because unit tests are used to check correctness of business logic of a unit, and integration tests are used to checks integration between modules, right?

Presentation layer uses abstractions (commands) from business layer. This is the same kind of design decision issues as for persistence layer.
What if we need to provide additional API, with different entities but using the same logic? In this case we can't just reuse existent command and we will need to choose one of approaches - create new commands and extend existent handlers to support these commands, or introduce additional Response/Request DTO layer and map them to commands. Again, this solution is not showing how to deal with these real-life cases. 

By separating entities by layers we are able to maintain layers completely separately. It make code much more flexible and testable, which is the main goal of The Clean Architecture. You may decide to use different UI layers simultaneously (i.e. REST API and message bus interface) for whatever reason, as well as use different persistence layer implementation without need to make changes to business logic. 

> Conforming to these simple rules is not hard, and will save you a lot of headaches going forward. By separating the software into layers, and conforming to The Dependency Rule, you will create a system that is intrinsically testable, with all the benefits that implies. When any of the external parts of the system become obsolete, like the database, or the web framework, you can replace those obsolete elements with a minimum of fuss.

This solution definitely should have more entity layers to became really an app in The Clean Architecture style.

### Conclusion
If this template is called "Clean Architecture", it should follow The Clean Architecture principles. Otherwise, it definitely better to  have some other name.

**Comment by karimkod** [comment]
@seoriy very good points. 
I have already tried to answer your inquiry about the dependency on the DbSet<T> in #439 
As for defining DAOs for the persistence layers, the Fluent API creates a pretty clear abstraction between the persistence layer and the domain layers. What's the difference between having an API, that specifies what to persist and how to persist it, and having a DAO that would exist for the same reasons? I personally don't see any. 

Yes, the presentation layer is using commands and triggering different use cases using those commands and queries which is a partial boundary (using Mediator) between the presentation layer and the application layer. 

> What if we need to provide additional API, with different entities but using the same logic

If you use different entities this would be a different use case i.e another horizontal slice in the app and should define its specific DTOs and use case (this is defined in the book under 'Decoupling use cases') 

That's at least what I know and got from the book. After all, This is architecture (Not a religion) and architecture is built on decisions. You can definitely clone this template and change it to match your own decision. 

Even, Uncle bob allowed some drifts from the original design of Clean Architecture, for instance, partial boundaries, and still called it Clean Architecture 💯

**Comment by karimkod** [comment]
@odairto Where is the context DB referenced, would you price the filename and line, please?

**Comment by odairto** [comment]
> @odairto I think you are in the wrong project, this is CleanArchitecture template, not Northwind template.

You are right! Sorry!
