### ISSUE TITLE
DB Migration using NET6 on MacOS failing

### ISSUE THREAD

**Issue by 1988gadocansey** [jasontaylordev/CleanArchitecture#485]
I clone the .NET6 repo and trying to do migration. the error below

Could not load type 'Microsoft.EntityFrameworkCore.Internal.DiagnosticsLogger`1' from assembly 'Microsoft.EntityFrameworkCore, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**Comment by mrwsoftware** [comment]
Try updating your EF.Tools in the WebUI Project to 6.0.0.

**Comment by jasontaylordev** [comment]
Please update to latest and try again, it should work now.

**Comment by 1988gadocansey** [comment]
Fixed. Thanks
