### ISSUE TITLE
Is it possible to use MySQL

### ISSUE THREAD

**Issue by Itaanikus** [jasontaylordev/CleanArchitecture#49]
Hi,

Thanks for the really great project/template! I'm not sure if this is the right place to ask, but is there a way to use MySQL as DB?
I have tried installing Pomelo.EntityFrameworkCore.MySql and shifting the "UseSqlServer" to "UseMySql", but it fails with migrations.

Best,
Itaakara 'Itaanikus'

**Comment by kmhigashioka** [comment]
Yup, you have to re-create the migrations. Just run `Add-Migration` script on `Persistence` project.

**Comment by Itaanikus** [comment]
By creating a new solution I did following:
* Install NuGet Pomelo.EntityFrameworkCore.MySql
* Edit "UseSqlServer" to "UseMySql" in MySqlTest.Infrastructure.Dependencyinjection
* Edit appsettings with right connectionstring

I get this following error when trying to add-migration:

An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Could not parse the JSON file.
Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

Am I supposed to do more steps?
I appreciate your help :)

Best,
Itaanikus

**Comment by Itaanikus** [comment]
I put one up here:
https://github.com/Itaanikus/MySqlTest

**Comment by jasontaylordev** [comment]
Thanks for your sample, @Itaanikus.
