### ISSUE TITLE
The type or namespace name 'Testing' could not be found

### ISSUE THREAD

**Issue by TweakStories** [jasontaylordev/CleanArchitecture#494]
**Describe the bug**
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Testing' could not be found (are you missing a using directive or an assembly reference?)	Application.IntegrationTests	C:\Users\roy_w\source\repos\TestCleanArchitecture\tests\Application.IntegrationTests\TodoItems\Commands\DeleteTodoItemTests.cs	8	Active

**To Reproduce**
1. Create new project with the template
2. Build it

**Screenshots**
![image](https://user-images.githubusercontent.com/36763887/142407431-d5f3ea69-da36-4697-b181-941a907b4d8d.png)

Did not made any changes to the project. Installed the new visual studio yesterday.

Fixed it by removing namespace from: public class Testing

**Comment by jasontaylordev** [comment]
This issue is not occurring for me, please try with the latest version.
