### ISSUE TITLE
Feature Request: Please add an E2E Test project

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#498]
Feature Request: 

Please add an E2E Test project in addition to the Unit Test and Integration Test.

**Comment by jasontaylordev** [comment]
Created a new branch; https://github.com/jasontaylordev/CleanArchitecture/tree/acceptance-tests. It includes a sample E2E test using Playwright .NET. This is my first time using Playwright, it seems great. Learn more here; https://playwright.dev/dotnet/docs/intro.

What do you think?

**Comment by jasontaylordev** [comment]
Upgraded to use [SpecFlow](https://specflow.org/) & [Playwright](https://playwright.dev/dotnet/docs/intro). 
Now includes tests for login success and failure.
