### ISSUE TITLE
Functional AdAccount?

### ISSUE THREAD

**Issue by Pyrobolser** [jasontaylordev/CleanArchitecture#5]
I see that you have **AdAccount** as a **ValueObject** but that it is not used anywhere else than in the tests. Would it be possible to have _Active Directory Login with Azure_ enabled for this application even if the _Classic Application Login_ is already enabled?

I suppose this is already in your plans since you have this class in there I just wanted to make sure. Once again, if I am able to come up to a clean solution myself I'll try to add to the project if that's interesting.

Thank you,

**Comment by jasontaylordev** [comment]
Hi @Pyrobolser. Sorry for taking so long to respond. The `AdAccount` was added as an example of a value object, but as you have stated, it wasn't used in any feature. I'm planning to add a new value object, such as `Colour` for `TodoList`, to provide an example that is actually used.

**Comment by syky27** [comment]
Hi @Pyrobolser  I am trying to do the same with minimal success, I was able to add Sign In With Microsoft functionality, but I am unable to get Azure AD working, I not sure what is wrong but I am definitely hitting limit of my .Net and Angular knowledge.

Had you any luck implementing Azure AD?

Thanks

**Comment by syky27** [comment]
@Pyrobolser DUDE! This is amazing, I spent all day going through every tutorial there is on docs.microsoft.com and I was not successful, I just copy pasted your code and it magically work 🎉.

My app now asks for an email, after getting logged in, I noticed that the demo app from Microsoft does not do that, do you know if there is a way to get that email which is at Azure AD automatically?

![Screenshot 2020-12-11 at 22 49 32](https://user-images.githubusercontent.com/2771802/101958199-26e45a00-3c03-11eb-8dae-03b3ecc097a3.png)

But anyways you saved me 🙏

**Comment by Pyrobolser** [comment]
Glad to see it's working for you. 🎉 
You should look into the Claims that are returned to you by Azure when authenticating.
One of them must be the Email of your user and you should be able to access it relatively easily now that you're authenticated.

Cheers!
