### ISSUE TITLE
jwt token creation

### ISSUE THREAD

**Issue by satem02** [jasontaylordev/CleanArchitecture#50]
**How to create jwt token**

Hi, feature request because I did not know.

1 - How do i proceed to generate jwt token.
2 - How do i add claims information.
can you help me.
thanks.

**Comment by Pyrobolser** [comment]
Hi, I found out that using IdentityServer with **_AddIdentityServerJwt()_** and the parameters in the _appsettings.json_ is actually doing a lot behind the scene and is making things a little bit complicated to override properly.  
If you find a better solution, please let me know as I am curious too, I think at one point I am going to follow the documentation of IdentityServer and implement it by myself instead so I understand better what is actually happening.
Right now in Infrastructure/DependencyInjection.cs I added this piece of code

```csharp
services.AddIdentityServer()
    .AddApiAuthorization<ApplicationUser, MyDbContext>()
    .AddProfileService<ProfileService>();

services.Configure<ApiAuthorizationOptions>(options =>
{
    options.IdentityResources.Add(new IdentityResource
{ 
    Name = "role",
    UserClaims = new List<string> { JwtClaimTypes.Role, ClaimTypes.Role } 
});
    options.Clients[0].AllowedScopes.Add("role");
});
```

With ProfileService.cs being
```csharp
public class ProfileService : IProfileService
{
	protected UserManager<ApplicationUser> _userManager;

	public ProfileService(UserManager<ApplicationUser> userManager)
	{
		_userManager = userManager;
	}

	public async Task GetProfileDataAsync(ProfileDataRequestContext context)
	{
		var user = await _userManager.GetUserAsync(context.Subject);

		if (context.Caller == "UserInfoEndpoint")
		{
			context.IssuedClaims.Add(new Claim(JwtClaimTypes.Name, user.UserName));
		}
		else
		{
			var roles = await _userManager.GetRolesAsync(user);

			foreach (var role in roles)
			{
				context.IssuedClaims.Add(new Claim(ClaimTypes.Role, role));
				context.IssuedClaims.Add(new Claim(JwtClaimTypes.Role, role));
			}
		}
		context.AddRequestedClaims(context.Subject.Claims);
	}

	public async Task IsActiveAsync(IsActiveContext context)
	{
		var user = await _userManager.GetUserAsync(context.Subject);

		context.IsActive = (user != null);
	}
}
```
For my example, I added the user role to the claims generated.

**Comment by TANIAX** [comment]
You just save me an infinite numbers of hours

**Comment by jasontaylordev** [comment]
Thanks for your solution, @Pyrobolser.
