### ISSUE TITLE
BIO_new_file:no such file when running the app on docker

### ISSUE THREAD

**Issue by olakara** [jasontaylordev/CleanArchitecture#515]
**Describe the bug**
When I execute the command "docker compose up" all services startup but, cleanarchitecture-webui-1 keep restarting. 

**To Reproduce**
1. I cloned the repo
2. Completed the docker requirements for certificates mentioned in README file
3. Ran the command `docker-compose -f 'docker-compose.yml' up --build`

**Expected behavior**
The application should run fine..

**Screenshots**
![image](https://user-images.githubusercontent.com/570905/144265998-59801b73-731d-4964-a681-0a7ae08062b1.png)

**Additional context**
Unhandled exception. Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
cleanarchitecture-webui-1      |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
cleanarchitecture-webui-1      |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
cleanarchitecture-webui-1      |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
cleanarchitecture-webui-1      |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert()
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
cleanarchitecture-webui-1      |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
cleanarchitecture-webui-1      |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
cleanarchitecture-webui-1      |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
cleanarchitecture-webui-1      |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
cleanarchitecture-webui-1      |    at CleanArchitecture.WebUI.Program.Main(String[] args) in /src/src/WebUI/Program.cs:line 43
cleanarchitecture-webui-1      |    at CleanArchitecture.WebUI.Program.<Main>(String[] args)

**Comment by ageisen2000** [comment]
This seems like you need to run that command to create a new self signed cert in your %appdata% folder. Check out the readme and try those steps if you haven't already

**Comment by jasontaylordev** [comment]
FYI I have removed support for docker as per #630
