### ISSUE TITLE
IMapFrom<T> crashes when a class extends froms multiple IMapFrom

### ISSUE THREAD

**Issue by syedqutub** [jasontaylordev/CleanArchitecture#518]
**Describe the bug**
if a class extends `IMapFrom<T>` multitple times, the `MappingProfile` class crashes on initiallization.

**To Reproduce**
1. Create a class that extends `IMapFrom<T>` more than once. let say `class A:IMapFrom<B>,IMapFrom<C>{}`
2. Use that class in an API and use `IMapper` as a dependancy. the API crashes when trying to resolve `IMapper`

I have working fix for this at
https://github.com/syedqutub/CleanArchitecture/tree/feature/multi-implement-fix
if you like i can make a PR for this

**Comment by syedqutub** [comment]
@neozhu yup i reproduced  the problem, but in my case the test failed even when i moved mapping registerations (CreateMap) in the `MappingProfile` class.

**Comment by janosorcsik** [comment]
Hi @neozhu and @syedqutub!

I have a similar solution for this multiple inheritances and duplicate registration problem.
Can you check if it works for you? #374

**Comment by jasontaylordev** [comment]
This is not currently supported, will consider adding support as per #374
