### ISSUE TITLE
DockerFile is referencing wrong image version

### ISSUE THREAD

**Issue by lucasrodrigues10** [jasontaylordev/CleanArchitecture#520]
**Describe the bug**
DockerFile is referencing image from dotnet core 5 instead of 6

**To Reproduce**
1. dotnet new --install Clean.Architecture.Solution.Template
2. dotnet new ca-sln
3. run `docker-compose -f 'docker-compose.yml' up --build`
4. see error

**Expected behavior**
Should not throw error

**Screenshots**
![version](https://user-images.githubusercontent.com/8684163/145717109-51d01fb1-7082-4be0-978e-33df7f417c75.png)

![error](https://user-images.githubusercontent.com/8684163/145716560-f13ffda2-24c1-4fe1-b09d-3304f7485104.png)

**Additional**
Seems it is correct in **main** branch
https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/WebUI/Dockerfile
However when I install and use the template locally it has the 5.0 version

**Comment by jasontaylordev** [comment]
FYI I have removed support for docker as per #630
