### ISSUE TITLE
Issue Scaffolding Identity

### ISSUE THREAD

**Issue by mrwsoftware** [jasontaylordev/CleanArchitecture#534]
**Describe the bug**
Using VS 2022 or Rider, I'm unable to scaffold identity for the project.  

(VS2022)
There was an error running the selected code generator. Package restore failed. Rolling back package changes for :WebUI.

**To Reproduce**
1. Clone Repo
2. Right click WebUI project
3. Add Scaffolding Item 
4. Select all and the IAppContext

**Expected behavior**
It should run through the scaffolding.

**Screenshots**
![image](https://user-images.githubusercontent.com/93381215/146935237-a52ae1fd-f531-4d64-b259-8518a9b41e74.png)

**Additional context**
Using rider seems to throw a different error, but does make it along further.

**Comment by jasontaylordev** [comment]
I've recently update the template, and this issue is no longer occurring.

**Comment by omidmoradzadeh** [comment]
I'm facing this error in vs 2022. how can I fix it?

Error Description is :
There was an error running the selected code generator. Package restore failed. Rolling back package changes for :WebUI.
