### ISSUE TITLE
Scaffolding entity

### ISSUE THREAD

**Issue by fasteddys** [jasontaylordev/CleanArchitecture#535]
Hello much or the repetitive work is exposing `entities `or `VeiwModels `scaffolding to tables or master details. 

It would accelerate development and adoption of this architecture if we could scaffold them with typewriter and get angular grid views.

Check [this link out](https://docs.aspnetzero.com/en/aspnet-core-angular/v7.0.0/Rapid-Application-Development)

https://github.com/colinin/abp-next-admin

https://github.com/EasyAbp/Abp.EntityUi

**Comment by neozhu** [comment]
Take a look at this https://github.com/neozhu/CleanArchitectureCodeGenerator
The project I developed was designed to reduce rework. You can modify the template to suit your needs

**Comment by fasteddys** [comment]
Hello can you please check if it works on VS 2022, I am having errors

**Comment by neozhu** [comment]
> Hello can you please check if it works on VS 2022, I am having errors

Perhaps you lack the necessary extensions to install vs 2022
