### ISSUE TITLE
Sockjs issues

### ISSUE THREAD

**Issue by mkrijtenberg** [jasontaylordev/CleanArchitecture#537]
So, I get a lot of sockjs issues when I run this project.

1) `Invalid Host/Origin header`

I have fixed this, by adding `"disableHostCheck": "true"` to the angular.json file (I know, it's bad practice, but haven't found a better way)
This results in less error, but there are still plenty :(

2) `Uncaught Error: Incompatible SockJS! Main site uses: "1.5.2", the iframe: "1.5.0"`

I have no idea how to prevent this message.

3) `WebSocket connection to 'wss://localhost:44312/sockjs-node/....' failed: WebSocket is closed before the connection is established.`

It fails to connect to a websocket and falls back to xhr requests, which fills up my network log.

Anyone knows how to fix these issues? Also, I'm not using docker, if that explains anything

**Comment by jasontaylordev** [comment]
These issues are fixed after upgrade to Angular 13.
