### ISSUE TITLE
Error while validating the service descriptor 'ServiceType:

### ISSUE THREAD

**Issue by agmohamed** [jasontaylordev/CleanArchitecture#541]
### Discussed in https://github.com/jasontaylordev/CleanArchitecture/discussions/540

I implement  JwtService  from IJwtService  at the Infrastructure layer
IJwtService declare at the Application layer

and
I implement  IdentityService  from IIdentityService   at the Infrastructure layer
IJwtService declare at the Application layer

I register both at infrastructure dependency injection like
```

services.AddTransient< IJwtService,JwtService>();
services.AddTransient<IIdentityService,IdentityService>();
```
Then I  implement LoginQueryHandler implement from : IRequestHandler<LoginViewModel, LoginDto>
within LoginQueryHandler() i inject IIdentityService and IJwtService

using mediator I send a request to LoginQuery Handler

        public async Task<LoginDto> Login([FromBody] LoginViewModel model)
        {
           
            return await Mediator.Send(model);
          }
This is LoginQueryHandler Class

```
```
public class LoginViewModel : IRequest<LoginDto>
{
    public string Email { get; set; }
    public string Password { get; set; }
    // public string? Token { get; set; }

    
}

public class LoginQueryHandler : IRequestHandler<LoginViewModel, LoginDto>
{
    
    private readonly IIdentityService _identityService;
    private readonly IJwtService _jwtService;
    public LoginQueryHandler(IIdentityService identityService,IJwtService jwtService)
    {
        _identityService=identityService;
        _jwtService=jwtService;
        
    }
    public async Task<LoginDto> Handle(LoginViewModel request, CancellationToken cancellationToken)
    {
        try
        {
            var user = await _identityService.FindByEmailAsync(request.Email);
           // codes....
            return new LoginDto();
        }
        catch (Exception ex)
        {
            throw ex;
        }
       
    }
    
}

but it throws the following error

```

```
System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: MediatR.IRequestHandler`2[Application.Login.Queries.LoginViewModel,Application.Login.Queries.LoginDto] Lifetime: Transient ImplementationType: Application.Login.Queries.LoginQueryHandler': Unable to resolve service for type 'TechneTravel.Infrastructure.Services.JwtService' while attempting to activate 'TechneTravel.Infrastructure.Identity.IdentityService'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'TechneTravel.Infrastructure.Services.JwtService' while attempting to activate 'TechneTravel.Infrastructure.Identity.IdentityService'.
```
```
</div>

**Comment by jasontaylordev** [comment]
Can I see you identity service? It looks like you're trying to inject JwtService.

**Comment by jasontaylordev** [comment]
Closing old issue, as this is probably already resolved.

**Comment by Samkaxe** [comment]
how did you solve it
