### ISSUE TITLE
Detailed documentation

### ISSUE THREAD

**Issue by vasiliv** [jasontaylordev/CleanArchitecture#566]
As you can see project is fairly large. Can you give a detailed documentation?

**Comment by demchenkov** [comment]
Jason posted in Readme good lecture about project and basic concepts  of Clean Architecture and this project. You can watch this lecture [here](https://www.youtube.com/watch?v=dK4Yb6-LxAk)

**Comment by bramburn** [comment]
@demchenkov yes its good but it doesn't go into a lot of detail needed to develop on.
I was wondering if @jasontaylordev could enable the wiki for the public to contribute to a documentation.

**Comment by jasontaylordev** [comment]
@bramburn of course, here you go - https://github.com/jasontaylordev/CleanArchitecture/wiki.
