### ISSUE TITLE
SaveChangesAsync() doesn't update LastModified(by) after the value object update

### ISSUE THREAD

**Issue by drazen64** [jasontaylordev/CleanArchitecture#581]
**LastModified(by) doesn't get updated after the value object update**
I have an auditable entity "Person" with the value object "Address". When the application changes only the address property of the person, SaveChangesAsync() doesn't update "LastModified" and "LastModifiedBy" fields. 
Changed address data is correctly saved to the database.
If any other field of the person entity is changed, those fields are correctly updated.
Entity and value object are correctly defined, migration created table as expected, all data manipulation operations work as expected.

Update command  handler looks like this:
```C#
   Person entity;
   /* fetch an entity and verify that it's not null*/
   /* update other fields */
   entity.Address = Address.From(request.Address);
   await _context.SaveChangesAsync(cancellationToken);
```

Problem is in `ApplicationDbContext` class, `SaveChangesAsync` function, in this line:
```c#
foreach (var entry in ChangeTracker.Entries<AuditableEntity>())
{ ... }
``` 
When the change is only in the value object of the auditable entity, this list contains a person object with the state "Unchanged". 

If you change this command to:
```c#
foreach (var entry in ChangeTracker.Entries<ValueObject>())
{ ... }
``` 

the list will show that the value object address is changed.

**Comment by jasontaylordev** [comment]
Thank you, this is now fixed.
