### ISSUE TITLE
Minimal Apis support

### ISSUE THREAD

**Issue by hassanrazakhalid** [jasontaylordev/CleanArchitecture#583]
**Is your feature request related to a problem? Please describe.**
This is not a problem. Dotnet6 has new way of implementing apis called minimal api. I was wondering if we can have support to select between controllers and minimal api. Also will it be worth moving from controllers to minimal apis because of simpler code and possibly better performance. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bramburn** [comment]
you could do it yourself, i think the reason for the non-minimal api is for the enterprise use of the app rather than a simple crud type build.

**Comment by jasontaylordev** [comment]
This is not something I am looking to implement (at this stage) in the template.
However, thanks for the suggestion.
