### ISSUE TITLE
Separate commands from its handlers

### ISSUE THREAD

**Issue by patrickreinan** [jasontaylordev/CleanArchitecture#59]
Hi Jason,

I watched your presentation about C.A. on Youtube. I think is cleaner if you separate command and command handlers in two classes. The command responsability is only to carry data (simple DTO) and command handler is responsible to process command.

**Comment by jasontaylordev** [comment]
I used to keep them in two separate classes as suggested, but I much prefer the combined approach. The reason to keep them together is that it improves discoverability of the handler. If they are separate, pressing F12 on the CreateCustomerCommand takes me to the command only. I have to use the solution explorer or keyboard wizardry to find the handler. If I put them both in the same file when I press F12 I see the command and the handler. It makes life a little easier for me and new developers who might not be familiar with this approach.

**Comment by patrickreinan** [comment]
Good! 

I like to separate it, but I agree with you. Makes sense.
