### ISSUE TITLE
Commands and Queries can be Value Objects

### ISSUE THREAD

**Issue by patrickreinan** [jasontaylordev/CleanArchitecture#60]
Commands and queries can be Value Objects.

**Comment by PureKrome** [comment]
@patrickreinan Maybe elaborate on your statement. Give some examples of how things can be better, etc.

**Comment by patrickreinan** [comment]
Hi @PureKrome ,

I think the code is more consistent if Commands and Query are created like a Value Object. This way, the object is immutable and holds the same data through the trip on stack.

**Comment by PureKrome** [comment]
I know what you're meaning ... I just thought it might be nice (via code) to express 'before' and 'after' examples.

Value objects seem to also shine when it comes to comparing also. So I was curious if that was a reason for wanting to make them, that?

**Comment by patrickreinan** [comment]
Hi @PureKrome, 

I understand your question. I agree with you about value object comparison. But the reason why I think use a value object is only to hold the object data during the trip on stack. So this way, I will be sure that the same data was input at the begin of request, is the same data that will be finish the request. So the application will allocate memory once (when the object is created). 

Let me know if I was clear ;)

**Comment by jasontaylordev** [comment]
I think implementing immutable types well in C# is quite hard to do. In this case, I've opted for the simplest approach - DTOs without any kind of restriction on read / write.

> Commands and queries can be Value Objects.

Agreed.

> I think the code is more consistent if Commands and Query are created like a Value Object. This way, the object is immutable and holds the same data through the trip on stack.

> But the reason why I think use a value object is only to hold the object data during the trip on stack. So this way, I will be sure that the same data was input at the begin of request, is the same data that will be finish the request. So the application will allocate memory once (when the object is created).

The commands and queries are just DTOs in this case. I want them to be as simple as possible and unrestricted in relation to assignment and construction. You can see in this solution, they are not changed as they pass through to the command or query handler. 

> Value objects seem to also shine when it comes to comparing also

Clearly a great use case, but not something that would come up with commands and queries. Each command or query represents a business use case, I don't compare the input of one use case to another.


Let me know your thoughts.

**Comment by patrickreinan** [comment]
Hi @jasontaylordev,

I understood your simple approach. Makes sense in your application because it so simple. I agree without you in this case. You thought KISS. ;)

I have a similar project in github, but I'm using V.O. instead DTO. The business rules is in Portuguese language, but you can check the code if you want.

I think is good use V.O. when the project is big and need more consistent.
