### ISSUE TITLE
'IWriterConfiguration' does not contain a definition for 'RegisterClassMap' 

### ISSUE THREAD

**Issue by asgharb** [jasontaylordev/CleanArchitecture#609]
hi
in class CsvFileBuilder i have this error

`  public byte[] BuildTodoItemsFile(IEnumerable<TodoItemRecord> records)
    {
        using var memoryStream = new MemoryStream();
        using (var streamWriter = new StreamWriter(memoryStream))
        {
            using var csvWriter = new CsvWriter(streamWriter, CultureInfo.InvariantCulture);

            csvWriter.Configuration.RegisterClassMap<TodoItemRecordMap>();
            csvWriter.WriteRecords(records);
        }

        return memoryStream.ToArray();
    }`

'IWriterConfiguration' does not contain a definition for 'RegisterClassMap' and no accessible extension method 'RegisterClassMap' accepting a first argument of type 'IWriterConfiguration' could be found (are you missing a using directive or an assembly reference?)

**Comment by asgharb** [comment]
hi
in class CsvFileBuilder i have this error

`'IWriterConfiguration' does not contain a definition for 'RegisterClassMap' and no accessible extension method 'RegisterClassMap' accepting a first argument of type 'IWriterConfiguration' could be found (are you missing a using directive or an assembly reference?)
`

**Comment by ghidello** [comment]
Hi @asgharb,
in recent versions of the CsvHelper library they moved the method from **Configuration** to **Context**: try updating your code to 
```c#
csvWriter.Context.RegisterClassMap<TodoItemRecordMap>();
```

**Comment by jasontaylordev** [comment]
Thanks, I'll make a not to get that updated.
