### ISSUE TITLE
Include Concurrency handling

### ISSUE THREAD

**Issue by AL-CHALABEE** [jasontaylordev/CleanArchitecture#619]
Concurrency handling is essential on the web, it is sad this great work does not cover it.

On a separate note, it would be nice to clarify why it is not recommended to use AutoMapper on the below code-alike 

e.g: UpdateTodoItemDetailCommand
....
entity.ListId = request.ListId;
entity.Priority = request.Priority;
entity.Note = request.Note;
....

**Comment by jasontaylordev** [comment]
> Concurrency handling is essential on the web, it is sad this great work does not cover it.

It's a good idea, but not something I'm looking to include right now - can't cover everything.

> On a separate note, it would be nice to clarify why it is not recommended to use AutoMapper on the below code-alike

I prefer to explicitly take control when updating entities, I want to see in code what fields are being updated.

Thanks
