### ISSUE TITLE
Why is the Infrastructure project referencing netcoreapp ?

### ISSUE THREAD

**Issue by PureKrome** [jasontaylordev/CleanArchitecture#62]
**Describe the bug**
I've noticed in the [Infrastructure.csproj](https://github.com/jasontaylordev/CleanArchitecture/blob/master/src/Infrastructure/Infrastructure.csproj#L4) file that it is targetting `netcoreapp3.1` yet the SDK is the normal one (not the web sdk).

Why is this?
I thought the `netcoreapp` should be the project which contains the HOST (e.g the WebUI / WebApi project).

I'm wondering if this is a bug and it should be targetting `netstandard20` instead.

**Comment by jasontaylordev** [comment]
Hi @PureKrome - thanks for the question. The Infrastructure project targets netcoreapp3.1 as Microsoft.AspNetCore.ApiAuthorization.IdentityServer depends on netcoreapp3.1.

**Comment by PureKrome** [comment]
Ahh kewl. gotcha. so if you're not planing on using IDSvr (but maybe using Auth0 for example) then this project could still target NS20. Kewl. gotcha.
