### ISSUE TITLE
AuthorizationBehaviour is not working

### ISSUE THREAD

**Issue by vdht** [jasontaylordev/CleanArchitecture#634]
When using the [Authorize] attribute in the controller, the AuthorizationBehaviour class (Application/Common/Behaviours/AuthorizationBehaviour .cs) doesn't get the authorizeAttributes. When I set a breakpoint on var authorizeAttributes = request.GetType().GetCustomAttributes<AuthorizeAttribute>(); the authorizeAttributes are always empty. Do I miss something?  Do I need to configure some DI? I used the clean architecture template to test it. There it also doesn't work.

**Comment by jasontaylordev** [comment]
Hi! Both the GetTodosQuery and PurgeTodoListsCommand are decorated with the AuthorizeAttribute.
Looking at the associated tests, within Application.IntegrationTests, everything seems to be working normally.
Please check them out if you would like some working examples.

Could it be that you are using the wrong AuthorizeAttibute? See https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Application/Common/Security/AuthorizeAttribute.cs.

**Comment by vdht** [comment]
Hi, thanks for your reply. Indeed I was using the wrong AuthorizeAttibute. I've changed it to Application/Common/Security/AuthorizeAttribute.cs and now it is working!

**Comment by jasontaylordev** [comment]
Awesome, glad it is working. Happy coding! 😀

**Comment by jins4291** [comment]
Hi, I am facing same issue. But my [AuthorizeAttribute.cs] is same. Could you please help?

**Comment by awsdevelopvn** [comment]
@jins4291 Please make sure you put the Authorize attribute on the command/query, NOT on the controller.
