### ISSUE TITLE
readme.md issue link is folder dependent

### ISSUE THREAD

**Issue by 1ronclad** [jasontaylordev/CleanArchitecture#64]
**Describe the bug**
The name of the folder where solution template is installed is substituted into an issue link in readme.md

**To Reproduce**
1. Create folder named, for example 'New Folder'
2. run dotnet new ca-sln
3. Open readme.md and check issue link in support section
4. See folder name as part of the link

**Expected behavior**
Issue link is hardcoded

**Comment by jasontaylordev** [comment]
Thanks for reporting this issue. I've dropped readme from the template. It's excluded when the package is built.
