### ISSUE TITLE
Cannot get Id of saved entity in domain event handler

### ISSUE THREAD

**Issue by achmstein** [jasontaylordev/CleanArchitecture#644]
**Describe the bug**
I'm trying to handle a domain event but I don't get the Id of saved entity. I do think that this happen because we dispatch event before saving changes.

```
 public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        await _mediator.DispatchDomainEvents(this);

        return await base.SaveChangesAsync(cancellationToken);
    }
```

**Comment by jasontaylordev** [comment]
I recently changed the events to dispatch before saving changes. I discussed the drivers for this change here:

https://github.com/jasontaylordev/CleanArchitecture/issues/326#issuecomment-1134529033

As you have mentioned above, it can be useful to dispatch events after saving changes. One example is that it will be easier to access the identity of newly created entities.

It will be difficult to implement a solution to suit all cases, so at best we can try to implement a solution that suits most cases.

Do you think it would be better to dispatch events before or after save changes?
