### ISSUE TITLE
Solution won't run on Linux

### ISSUE THREAD

**Issue by JwanKhalaf** [jasontaylordev/CleanArchitecture#645]
**Describe the bug**
A newly created solution from the template does not run on Linux.

In the browser, you see:

![image](https://user-images.githubusercontent.com/42877376/172127597-1241ebd7-9bc1-4302-83f7-9a0e562e1043.png)

And in Rider's terminal (the IDE), you see:

![image](https://user-images.githubusercontent.com/42877376/172127487-dd2ceb00-6c6b-441b-95b5-565167128f30.png)

**To Reproduce**
1. Follow install instructions
2. Create a new solution from the template
3. Run the solution

**Expected behavior**
I expect to see the Angular application running.

**Additional context**
I am running Arch Linux. I have:

```
~ ❯ dotnet --list-sdks    
6.0.200 [/home/j/.dotnet/sdk]
6.0.300 [/home/j/.dotnet/sdk]
~ ❯ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.2 [/home/j/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [/home/j/.dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.2 [/home/j/.dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [/home/j/.dotnet/shared/Microsoft.NETCore.App]
~ ❯ node --version
No version is set for command node
Consider adding one of the following versions in your config file at 
nodejs 18.2.0
```

Those two node messages above the node version are coming from [asdf](http://asdf-vm.com/)

**Comment by jasontaylordev** [comment]
I am currently running [Node.js LTS](https://nodejs.org/en/):

```bash
node --version
```

For me, the above command outputs **v16.15.1**. I have not tested with other versions. I suggest installing LTS and getting it working with that version before trying the current version.

To troubleshoot, I recommend you try to build and run the Angular front end separately. To do so, navigate to **/src/WebUI/ClientApp** and run the following commands.

First, restore the required npm packages:

```bash
npm install
```

Next, install the [Angular CLI](https://angular.io/cli) globally:

```bash
npm install --location global @angular/cli
```

Next, build the app using the Angular CLI:
```bash
ng build
```

Finally, run the app:

```bash
npm run start
```

If you encounter and issues running the above commands, stop and troubleshoot before continuing to the next command.

Good luck, let me know how you got on. 😀

**Comment by JwanKhalaf** [comment]
Thanks @jasontaylordev, I think it might have been something related to my setup.

I uninstalled `asdf` and went with `nvm` as I was having some other problems with `asdf` on Arch.

However, I was still seeing the same issue when trying to run the application via JetBrains Rider.

I then tried running the application via the Terminal, using `dotnet run --project src/WebUI` and it works! :tada: 

![image](https://user-images.githubusercontent.com/42877376/172338881-14d4a85b-5087-4508-afb4-2f04c137576e.png)

Thank you very much :heart:

**Comment by jasontaylordev** [comment]
You're welcome. Looking at the screenshot above you might want to [follow this guide](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-https-certificate-on-linux)  to trust the development certificate. Happy Coding! 😀
