### ISSUE TITLE
This architecture along with IdentityServer4

### ISSUE THREAD

**Issue by Warrolen** [jasontaylordev/CleanArchitecture#65]
Hello, people!

I watched [this video](https://www.youtube.com/watch?v=5OUQZAvxZuA) and I'm trying to understand how does IdentityServer4 work along with this architecture.

Could you please note things/explain me how to do it properly? By the way, I'm using ASP.NET Core 3.1 and Angular 8 and I want to implement the jwt authorization.

I have the following project structure:

```
ProjectName.Api - Web API
ProjectName.Application
ProjectName.Domain
ProjectName.Infrastructure
ProjectName.Web - Angular
```

As far as I understand, I will need an additional project called `ProjectName.Auth` which is basically the IdentityServer4 authorization app.

What's misleading me the most is all those different NuGet Packages used in the different videos and serving one purpose and all these Fluent Interface Builder method calls.

**Comment by sularz-maciej** [comment]
Yes, I would like to know an answer to the above question too.

Any insight would be much appreciated.

I'm currently building an e-commerce site as Microservices, however I want to keep the customers separate from the Admin Dashboard users aka employees. I Have implemented the CQRS pattern and am using native .Net Core Identity at the moment. I will potentially be considering basing the customers identity microservice on IdentityServer4 so am very keen to know more on the subject, and perhaps even switch to it for the admin panel too...

**Comment by jasontaylordev** [comment]
The solution is using the SPA with Angular and .NET Core project template. It was created using `dotnet new angular --auth Individual`. This approach scaffolds an application that utilises ASP.NET Core Identity and IdentityServer. You can learn more about this approach here; https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1.

**Comment by jasontaylordev** [comment]
Closing, but feel free to provide feedback at any point.

**Comment by litan1106** [comment]
I went with the ProjectName.Auth (IdentityServerv4 4.0.0) architecture because the dotnet new angular --auth Individual still uses IdentityServerv4 3.0.0
