### ISSUE TITLE
Update README to include node.js tools

### ISSUE THREAD

**Issue by nfgallimore** [jasontaylordev/CleanArchitecture#653]
Could you update the README.md to include instructions to navigate to the ClientApp folder and install

`npm install --save-dev run-script-os`

before running the app, as it did not work on my system as I did not have these.

**Comment by jasontaylordev** [comment]
It's not required, the solution is designed to run this automatically on build of WebUI. Review the [WebUI.csproj](https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/WebUI/WebUI.csproj) file, starting at line 48. This means that if you build the solution or WebUI project, or if you run the WebUI project (without skipping build), and the node_modules folder does not exist, and node is installed, then `npm install` will run.

Of course, things can go wrong - maybe you ran into some other issue. I would encourage you to try:

```bash
dotnet new --install Clean.Architecture.Solution.Template
dotnet new ca-sln --output CaSlnTest
cd .\CaSlnTest\src\WebUI\
dotnet run
```

This will launch the back end, open your browser at https://localhost:5001.
The front end will be automatically started, and you should see the site load normally.
