### ISSUE TITLE
Can't Build Solution due to NSwag Error when using .Net6

### ISSUE THREAD

**Issue by tarekmostafa-saitama** [jasontaylordev/CleanArchitecture#668]
Build Error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\tarek\.nuget\packages\nswag.msbuild\13.15.10\build\../tools/Net60/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code -1

More Error Message Details:
1>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.InvalidOperationException: NSwag requires the assembly CleanArchitecture.WebUI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null to have either an BuildWebHost or CreateWebHostBuilder/CreateHostBuilder method. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/hosting?tabs=aspnetcore2x for suggestions on ways to refactor your startup type.
1>   at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 87
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName)

**Comment by mehrdad-tat** [comment]
I'm encountering an error when trying to run the NSwag tool on a .NET 6 project. The error message is:

`MSB3073 The command "dotnet "C:\Users\*****\.nuget\packages\nswag.msbuild\13.9.4\build\../tools/Net50/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code -2147450730.`

I have checked that the nswag.json configuration file is properly set up, and all required dependencies are installed. I have also tried running the dotnet command manually in the command prompt, but it did not provide any more specific error messages.

I would appreciate any suggestions or solutions to help resolve this issue.
