### ISSUE TITLE
Is It Possible to add Repository & UnitOfWork on the Application or Infrastructure Layer?

### ISSUE THREAD

**Issue by ToperCarlos** [jasontaylordev/CleanArchitecture#67]
**Is your feature request related to a problem? Please describe.**
I'm always asking if I could implement the Repository / UnitOfWork on Application or Infrastructure Layer so that some of the queries that are reusable.

I also wanted to use those Repo on Command & Query part just for the reusability.

Let say for instance:

I Have Doctor's Appointments Data and i wanted to create a filter per status (confirmed) then i wanted to add another filter per speciality of the doctor and so on.

**Comment by JasonFoglia** [comment]
Infrastructure would be my best assessment.

**Comment by GFoley83** [comment]
Interfaces in Application, implementation in Infrastructure.
 
UoW is not needed with this solution; each command is essentially a UoW. `DbSet` is already a repository so adding an extra repository layer abstraction is also redundant IMO. 
A service layer for recurring business logic can certainly be useful but I'd only add a repository layer if you're sure that the shared code will _never_ need to change for any of its usages. It's ok to have some duplication on your Db queries w/ CQRS.

**Comment by manishrawat4u** [comment]
> Interfaces in Application, implementation in Infrastructure.
> 
> UoW is not needed with this solution; each command is essentially a UoW. `DbSet` is already a repository so adding an extra repository layer abstraction is also redundant IMO.
> A service layer for recurring business logic can certainly be useful but I'd only add a repository layer if you're sure that the shared code will _never_ need to change for any of its usages. It's ok to have some duplication on your Db queries w/ CQRS.

And where should we place the services ( recurrence business logic)

**Comment by GFoley83** [comment]
"Services" can exist in all the layers. Though for Application and Infrastructure, the interfaces belong in the Application layer for both, by design.

Business logic belongs in the Domain layer 
e.g `OrderProcessor`, `AddBankAccount`, `UpdateFlightPlan`. The Domain layer is where you model how the different entities that make up your Domain interact with each other. 

https://lostechies.com/jimmybogard/2008/08/21/services-in-domain-driven-design/

**Comment by jasontaylordev** [comment]
Thanks @GFoley83! 😀
