### ISSUE TITLE
[Bug] Seed data for adding default user is not updating database

### ISSUE THREAD

**Issue by GFoley83** [jasontaylordev/CleanArchitecture#68]
**Describe the bug**
Title says it all. `ApplicationDbContextSeed` is running but the default user is not getting added to the Db. I can register new users fine; it's just the seed data that's the issue.

**To Reproduce**
1. Check out a fresh copy of `master`.
2. Delete existing `CleanArchitectureDb` if present.
3. Run application from VS.
4. Verify that `dbo.AspNetUsers` is empty.

**Expected behavior**
`dbo.AspNetUsers` should contain "jason@clean-architecture" user.

**Additional context**
The seed logic is the same as eShopOnWeb. I've tested that solution too and it seeds the users fine. My guess is some config has been missed in start-up.

**Comment by s-whaley** [comment]
If I'm not mistaken, the password used for seeding the user does not meet the default password requirements.

**Comment by GFoley83** [comment]
You were right  @s-whaley. That was the issue. Awful behavior to have that silently fail instead of throwing a useful exception. Added a PR to address.
