### ISSUE TITLE
Convert to an extension method instead of a static helper method

### ISSUE THREAD

**Issue by william-liebenberg** [jasontaylordev/CleanArchitecture#680]
cc @matt-goldman 

**Hi Jason** 👋 

I noticed a static helper method `CreateAsync` for `PaginatedList`:
https://github.com/jasontaylordev/CleanArchitecture/blob/dcdb8524534c8a99f56ab82f395669c91969bef5/src/Application/Common/Models/PaginatedList.cs#L24

I think it makes sense to convert it to an extension method which would result in some cleaner usage code like this:
```cs
var page = await query.ToPaginatedListAsync(pageNumber, pageSize);
```

What do you think?

**Comment by jasontaylordev** [comment]
Thanks Will, sounds good to me - feel free to raise a PR. 👍

**Comment by lwestfall** [comment]
Just chiming in to support this, but with the request that CreateAsync stays (maybe with my suggested change per #695 😉 ) and the extension method call CreateAsync to prevent breaking changes (maybe not super important for a template project, though)

**Comment by jasontaylordev** [comment]
Closing, if this change is required, just raise a PR.
