### ISSUE TITLE
Break out application and the core aspects of application to support multiple web layers

### ISSUE THREAD

**Issue by mweel1** [jasontaylordev/CleanArchitecture#683]
When you have multiple web applications in a project its not clean when you share the application reference.  Current User Service loses its context definition if you have different claims from a token, etc. and so do other dependencies to the web layer that might be specific (notification to a SignalR hub, etc).

It would be good if the core aspects of the Application folder were their own project then you could reference that in multiple application projects to support multiple web layer

I find myself stacking current user services and not implementing certain parts for different web projects.

Has anyone else run into this?

**Comment by danielmackay** [comment]
@mweel1 - For a multi-web project / multi-application project what you proposed sounds like the way to go.  However, I would say that this scenario would not be common for the majority of the users of the template, and thus would be overkill to add to the template itself.

For your situation I would suggest you make the exact changes that you've proposed locally with your solution.
