### ISSUE TITLE
More complicated model relations in database (many-to-many link)

### ISSUE THREAD

**Issue by AiratShaimuhamitov** [jasontaylordev/CleanArchitecture#69]
Hello, it's rather a question than a report. I've just started implementing a project with this template and come across the problem with many-to-many relation of my database models. So the problem is: I have two models that have to be linked to each other with a many-to-many link, such link requires a third table/model and I put this model to Domain layer. It works fine but doesn't look like an elegant solution to me, since it is not a business model, but database related thing and the good place where I should put it - persistence layer.
I prefer to use DbContext interface in the Application layer but it seems for the more complicated cases (like I described higher) it doesn't work for 100%. I understand that I have to use that approach that will solve my problems, for example, using Repository pattern, but is there any beautiful way to do this using DbContext?

**Comment by GFoley83** [comment]
This is a Db design issue, which has nothing to do with this solution. Questions like this belong on StackOverflow.

Opinions vary but adding a model for your junction table is fine:
https://lostechies.com/jimmybogard/2014/03/12/avoid-many-to-many-mappings-in-orms/

Good luck.
