### ISSUE TITLE
Migration doesn't work

### ISSUE THREAD

**Issue by GianlucaLocri** [jasontaylordev/CleanArchitecture#694]
**Describe the bug**
I've just created a new solution using the latest template.
I've followed the instructions to create a new migration but the process fails wit this error:
_"Your startup project 'clean.WebUI' doesn't reference Microsoft.EntityFrameworkCore.Design."_

**To Reproduce**
Follow exactly the instructions on the repo page under Database Migrations section.
(I'm using VS2022)

**Expected behavior**
A successful operation out of the box.

**More info**
The problem goes away if I install the offending packet **on the WebUI project**,
but I think this is not a clean workaround.
If instead this is the right way to do it, I suggest you to include a note on the docs.

**Comment by lwestfall** [comment]
I agree that this needs to be addressed in the docs, but did you see my reply to your discussion here? https://github.com/jasontaylordev/CleanArchitecture/discussions/690#discussioncomment-3465426

**Comment by GianlucaLocri** [comment]
While we wait for official feedback I'll give it a try!

**Comment by GianlucaLocri** [comment]
I've also tried to import the above packages as suggested by abdelfatahhamed but I get the same result...

**Comment by jasontaylordev** [comment]
With the above fix, you should no longer encounter this issue.
