### ISSUE TITLE
PaginatedList<T>.CreateAsync violates CA1000

### ISSUE THREAD

**Issue by lwestfall** [jasontaylordev/CleanArchitecture#695]
**Describe the bug**
PaginatedList.CreateAsync<T> violates [CA1000](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1000)

In my project I fixed this by making an abstract, non-generic PaginatedList that PaginatedList<T> inherits, and then made CreateAsync a generic method in the abstract class.

This could easily be combined with #680 to add an extension method - however I'd propose that CreateAsync remain to prevent breaking changes, and let the extension method wrap it (maybe this is already the intended direction)

This is my implementation (sans extension method which would be nice) - I don't believe this introduces any breaking changes:

```cs
namespace Application.Common.Models;

using Microsoft.EntityFrameworkCore;

public abstract class PaginatedList
{
    public PaginatedList(int count, int pageNumber, int pageSize)
    {
        this.PageNumber = pageNumber;
        this.TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        this.TotalCount = count;
    }

    public int PageNumber { get; }
    public int TotalPages { get; }
    public int TotalCount { get; }

    public bool HasPreviousPage => this.PageNumber > 1;

    public bool HasNextPage => this.PageNumber < this.TotalPages;

    public static async Task<PaginatedList<T>> CreateAsync<T>(IQueryable<T> source, int pageNumber, int pageSize)
    {
        var count = await source.CountAsync();
        var items = await source.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync();

        return new PaginatedList<T>(items, count, pageNumber, pageSize);
    }
}

public class PaginatedList<T> : PaginatedList
{
    public List<T> Items { get; }

    public PaginatedList(
        List<T> items,
        int count,
        int pageNumber,
        int pageSize) : base(count, pageNumber, pageSize) => this.Items = items;
}
```

**Comment by jasontaylordev** [comment]
Looks good, for the time being, I'll leave it as is to focus on bigger changes. But please feel free to raise PR if you are keen. Thank you.
