### ISSUE TITLE
Cannot build WebUI. Compile error

### ISSUE THREAD

**Issue by workingacc123** [jasontaylordev/CleanArchitecture#697]
**Describe the bug**
Build fails. There is a problem with Nswag package. Currently i am on 13.16.0 NSwag version.

**To Reproduce**
1.  Change the useinmemorydatabase variable to false in WebUI/appsettings.json  => "UseInMemoryDatabase": false.
![image](https://user-images.githubusercontent.com/67863437/188885763-573afc5e-d0fc-43f9-8a34-92bc673f8fee.png)

3. Change the Default connection string to proper one(the connection string is trustworthy and there isn't a problem with it).
4. Build the project

**Expected behavior**
The code to work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/67863437/188884692-6c18736c-5af4-414b-9930-b064cca61fe3.png)

**Comment by jasontaylordev** [comment]
I can't identity the issue based on the description provided. I tried the following:

```bash
dotnet new ca-sln
dotnet build
```

The solution creates and builds successfully. NSwag runs without error.

Update **WebUI/appsettings.json** as follows:

```diff
{
-  "UseInMemoryDatabase": false,
+  "UseInMemoryDatabase": true,
   "ConnectionStrings": {
      "DefaultConnection": "Server=(localdb)\\mssqllocaldb;Database=CaSlnTest01Db;Trusted_Connection=True;MultipleActiveResultSets=true;"
    },
```

The default connection string is using LocalDb, so I left that alone.

```bash
dotnet build
```

The solution builds again without error, and the output indicates database interaction. NSwag runs normally.

Try checking Output for more information.

**Comment by YARG** [comment]
I have the same issue.  

Setting the "UseInMemoryDatabase" to false allows the build to complete but if you provide your own connection string and set the "UseInMemoryDatabase" to false (as we want to use the DB from the connection string) the build will fail as outlined by @workingacc123

**Comment by YARG** [comment]
OK I got it working.  I commented out:

` <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
    </Target>`

which let me then build and run the project, it then failed on the migration step due to an invalid connection string, so I fixed that and I was able to run ran the project fine (created the tables in Azure).  I then uncommented the above and I was still able to build and run the project.  So for me it was simply down to an invalid connection to the SQL Azure DB "my bad".  I hope it helps.

**Comment by hrrysnplusplus** [comment]
> OK I got it working. I commented out:
> 
> ` <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' "> <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" /> </Target>`
> 
> which let me then build and run the project, it then failed on the migration step.
> 
> My connection string (Azure SQL) was wrong and I also had to add "Microsoft.Data.SqlClient" due to the error:
> 
> `[Invalid value for key 'authentication'](https://stackoverflow.com/questions/59654712/invalid-value-for-key-authentication)`
> 
> I was then able to run the project fine (created the tables in Azure). I then uncommented the above and I was still able to build and run the project still. So for me it was simply down to an invalid connection to the SQL Azure DB "my bad" and the addition of "Microsoft.Data.SqlClient". I hope it helps.


My Build worked without Nswag being commented out. You may have to update nswag package

**Comment by jasontaylordev** [comment]
Hopefully, with recent changes to the way NSwag runs in the template, these kinds of issues will be easier to detect.

**Comment by Sam4n** [comment]
it happens only in Develop builds. you can use 
dotnet build  sample.csproj -c Release 
instead
