### ISSUE TITLE
Docker / containerization support

### ISSUE THREAD

**Issue by yehudamakarov** [jasontaylordev/CleanArchitecture#70]
I believe Northwind Traders had a dockerfile.
Either way, it seems fitting that such a template is able to be built in a container right away. 

I'm happy to help / contribute as I'm about to figure out the best way to accomplish this for a project I need to begin.

Just need some pointers to contribute productively. 

Related to 
#66

**Comment by kingjordan** [comment]
I am also interested in this ! 👍

**Comment by jasontaylordev** [comment]
Hey @brendan-ssw, can you please help with this one?

**Comment by xontab** [comment]
Created a PR (https://github.com/jasontaylordev/CleanArchitecture/pull/171) that adds Docker support

**Comment by yehudamakarov** [comment]
Oh hey nice! Let’s see!

**Comment by jasontaylordev** [comment]
I'll keep this open until the pull request goes through. I am wondering why I haven't pushed it though already. Apologies, I'll take a look tonight. @yehudamakarov - take a look if you have some spare time and let me know what  you think

**Comment by yehudamakarov** [comment]
I wanted to try and never did. Appreciation for you guys making it happen. 

I will check it out and give it a whirl if I can pull the right code and run it. 

Keep it up @jasontaylordev if I have any feedback I'll try to deliver it. 😀

**Comment by kingjordan** [comment]
i made a final comment on the PR for this, I think it is ready to be pulled in with a couple adjustments.

**Comment by jasontaylordev** [comment]
Thanks all, PR has been merged.

**Comment by yehudamakarov** [comment]
#171 has been merged, for whoever missed it above.
