### ISSUE TITLE
IMapFrom<T> does not work with abstract base classes

### ISSUE THREAD

**Issue by damikun** [jasontaylordev/CleanArchitecture#705]
**Is your feature request related to a problem? Please describe.**
In case i use abstract base class and some shared map is defined in this base the Activator cannot create instance to access mapping..

Ofcourse we cannot create instance of abstract class...
```
var instance = Activator.CreateInstance(type);
```
https://github.com/jasontaylordev/CleanArchitecture/blob/08c0d6a36bd27c20efc6fd8fb70148f7be97f6c6/src/Application/Common/Mappings/MappingProfile.cs#L27

**Describe the solution you'd like**
A:  Reflexion workeround to instance delegate...
B: Moving from instance Map definition to static method definition that does not need instance...

Mapping does not use `this` so down example works for me... Im adding check if it is abstract with aditional logic... Im not creating instance...
```
if (type.IsAbstract)
{
  // new code
  var method = type.GetMethod(mappingMethodName);
  var func = (Action<Profile>)Delegate.CreateDelegate(typeof(Action<Profile>), null, method);
  func(this);
}
 else
{
   // old code
   var instance = Activator.CreateInstance(type);
 ...
```

**Comment by jasontaylordev** [comment]
Hey @damikun, what do you think of #871?

**Comment by jasontaylordev** [comment]
I'll close this issue since `IMapFrom` and the related functionality is no longer in use.
