### ISSUE TITLE
Request for Angular Alternative

### ISSUE THREAD

**Issue by KTarun003** [jasontaylordev/CleanArchitecture#710]
I would like to have an option to choose between major SPA's like React, Vue etc.

**Comment by damikun** [comment]
I agree that decoupling FE and BE is good idea... Currently app is serverd as static from API project which has also advantages with CORS etc... 

Decoupling can be done by moving Angular from API to custom FE folder and create custom registration for serving static files...  ( UseAngularFre(...), UseReactFe(..)... ) 

What you will lost, is ability to start frontend with backend... Or it will require some codding to map sources paths...

**Comment by KTarun003** [comment]
If we are serving static files , can we build our FE to a folder and serve that folder?. If we can , can we do it while development too?

**Comment by damikun** [comment]
> If we are serving static files , can we build our FE to a folder and serve that folder?. If we can , can we do it while development too?

Ofcourse you can.. dotnet has some templeates for react: 'dotnet new react' or something similar.. snd you can integrate clean architecture to that templeate..

**Comment by jasontaylordev** [comment]
Thanks for the suggestion. I am considering adding options for Web API only, Angular (existing), and React (new). I need to try it out first, I might not have the capacity to maintain so many options.

**Comment by nickgallimoresoftware** [comment]
@jasontaylordev I'm converting it to an API only right now. I would appreciate that feature. I'm working with React Native clients.

**Comment by Van-Dame** [comment]
In my case, I chose a different FE (Svelte) and replaced Microsoft.AspNetCore.SpaProxy with [AspNetCore.SpaYarp](https://github.com/berhir/AspNetCore.SpaYarp). Lets me decide whether to serve the FE as a part of API or as a separate launch with minimal changes/config.

**Comment by JohanHeyvaert** [comment]
> In my case, I chose a different FE (Svelte) and replaced Microsoft.AspNetCore.SpaProxy with [AspNetCore.SpaYarp](https://github.com/berhir/AspNetCore.SpaYarp). Lets me decide whether to serve the FE as a part of API or as a separate launch with minimal changes/config.

Any chance to publish an example of your solution? We consider migrating to Svelte 😄.  Traditional frameworks like Angular and React seem to be slowly losing ground.

**Comment by pflajszer** [comment]
VS 2022 allows creation of the below:
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/45766938/207797759-93827383-3b8e-4197-89d3-492ad2cfe959.png">


... and respective tutorials to get those running with a separate API project:

https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/45766938/207797932-c53ea66b-6523-492f-ad89-7df8e729e2b0.png">

**Comment by jasontaylordev** [comment]
I've added support for React in #872

**Comment by jasontaylordev** [comment]
Support for API only covered by #786
