### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by pareshjoshi** [jasontaylordev/CleanArchitecture#72]
Angular 9 is officially released on 7 Feb 2020. Version 9 moves all applications to use the Ivy compiler and runtime by default. It has been updated to work with TypeScript 3.6 and 3.7.

It would be good to have this template updated to target Angular 9.

**Comment by GFoley83** [comment]
Probably wouldn't take much work if you feel like opening a PR for the changes?

**Comment by MCCshreyas** [comment]
Does Jason mereges those PR?

**Comment by jasontaylordev** [comment]
The solution has now been updated to Angular 9.
