### ISSUE TITLE
An abandoned folder TestProject1 is created on  dotnet new ca-sln

### ISSUE THREAD

**Issue by Anarios** [jasontaylordev/CleanArchitecture#724]
**Describe the bug**
After I ran  dotnet new ca-sln - an folder with a couple of empty files (TestProject1, UnitTest1.cs, etc) was created alongside with "normal" solution. 

This folder is invisible in solution and visible only in file explorer.

I think that it's useless\forgotten

**To Reproduce**
1.  run dotnet new ca-sln
2. observe a useless folder inside the project

**Expected behavior**
Folder shouldn't be created

**Screenshots**
![image](https://user-images.githubusercontent.com/3018711/198745893-da4caf24-c80b-4e4b-979f-41d52b5b77c7.png)

**Comment by jasontaylordev** [comment]
Thanks, this issue has been resolved.
