### ISSUE TITLE
NSwag Fix : When project updated to .net 7.0, NSwag execution was removed from WebUI.csproj

### ISSUE THREAD

**Issue by hrrysnplusplus** [jasontaylordev/CleanArchitecture#725]
**Describe the bug**
Nswag not detecting changes to api. Nswag not generating client side code

The Fix:

Add this to the WebUi.csproj file

    <PropertyGroup>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    </PropertyGroup>

    <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
    </Target>

**Comment by pulla2908** [comment]
@hrrysnplusplus this code is removed from WebUI.csproj since it was updated to .NET 7. How is client side code generated instead?

**Comment by hrrysnplusplus** [comment]
> @hrrysnplusplus this code is removed from WebUI.csproj since it was updated to .NET 7. How is client side code generated instead?

Yea, the code was removed since .net 7, it seemed to have issues with EF migrations. My workaround is to remove NSwag from webui.csproj every time I updated the DB. Then I added NSwag back once the migration and updates to the DB is finished. 

Client side api is generated when you add NSwag back to the csproj file and run the build.
