### ISSUE TITLE
"Dotnet new install" is now "Dotnet new --install"

### ISSUE THREAD

**Issue by TomKirby** [jasontaylordev/CleanArchitecture#729]
**Describe the bug**
The current installation instructions of running the command `dotnet new install Clean.Architecture.Solution.Template` no longer works with the latest version of the dotnet SDK (I am running 6.0.402) and should be replaced with instructions to run `dotnet new --install Clean.Architecture.Solution.Template` instead.

**To Reproduce**
Steps to reproduce the behaviour:
1) running `dotnet new install Clean.Architecture.Solution.Template` from the CLI causes an error to be produced.

**Proposed Solution**
Update Readme.md documentation to instruct the user to install by running `dotnet new --install Clean.Architecture.Solution.Template`

**Comment by damikun** [comment]
Starting with .NET SDK 7.0.100 Preview 2, the dotnet new syntax has changed:

The --list, --search, --install, and --uninstall options became list, search, install and uninstall subcommands.
The --update-apply option became the update subcommand.
to use --update-check, use the update subcommand with the --check option.

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install
