### ISSUE TITLE
How to secure API resources without user login (Authorize attribute).

### ISSUE THREAD

**Issue by ahmedtanveer** [jasontaylordev/CleanArchitecture#738]
### Discussed in https://github.com/jasontaylordev/CleanArchitecture/discussions/733

<div type='discussions-op-text'>

<sup>Originally posted by **ahmedtanveer** November  8, 2022</sup>
Hi,

Since APIs are published, anyone can submit a request WeatherForecastController and get the data.

How WeatherForecastController can be secured that only Angular client app can access (without user name & password).

Is using access tokens with [angular-auth-oidc-client](https://github.com/damienbod/angular-auth-oidc-client) is the way to secure API resources. 

https://localhost:5001/api/WeatherForecast

Really appreciate help in this regards. Thanks in advance.</div>

**Comment by ahmedtanveer** [comment]
Hi @jasontaylordev, really appreciate your feedback on my query.
Thanks.

**Comment by jasontaylordev** [comment]
Closing as this issue is not specific to the template.
