### ISSUE TITLE
IApplicationDbContext and EF Core 7.0 Bulk updates

### ISSUE THREAD

**Issue by gokujax** [jasontaylordev/CleanArchitecture#743]
I cannot access ExecuteUpdateAsync or ExecuteDeleteAsync after injecting IApplicationDbContext

await _context.TodoItems.Where(e => !e.Done).ExecuteDeleteAsync(cancellationToken);

Error : IQueryable<TodoItem> does not contain a definition for ExecuteDeleteAsync

**Comment by kibernetik542** [comment]
You need to install Microsoft.EntityFrameworkCore.SqlServer to Application layer, as Infrastructure is using Application that is reason methods not visible as it belongs to this nuget package.

P.S. If you are using Postgre or another db, it is in appropriate nuget package for this.

**Comment by gokujax** [comment]
Thanks @kibernetik542
