### ISSUE TITLE
Looking for more details on the Login / Register pages

### ISSUE THREAD

**Issue by ageisen2000** [jasontaylordev/CleanArchitecture#760]
Can you link some documentation that explains more about how those razor pages work for registering / logging into the app? Is this all handled by IdentityServer or am I missing something? I see that the `_LoginPartial.cshtml` file has `<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login"`

But I can't find where this asp-area is coming from. Is it from a nuget package or something?

**Comment by ageisen2000** [comment]
Well, I googled it a bit harder and found this. I'm guessing you're using this? 

https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-7.0&tabs=visual-studio

**Comment by kingjordan** [comment]
identity server 4 handles the authentication
see the docs here
https://identityserver4.readthedocs.io/en/latest/

**Comment by ageisen2000** [comment]
@kingjordan I was mostly referring to the UI for registering a user and the login page. 

I don't think that's identity server that is providing those razor pages, but I could be wrong.

**Comment by kingjordan** [comment]
Hello,

identity server when set up like it is in this project does indeed provide those pages, you get redirected to the front end client app after IS4 authenticates the user, the front end app catches this verification with user token etc in the angular app
take a look at the code in authorize.service.ts.  I was looking to do the same thing as you, to restyle the login page and I realized that its provided by IS4

**Comment by ageisen2000** [comment]
Awesome 👍 I'll look into this more. 

Thank you! I haven't used identity server since identity server 3 and didn't know this was a thing.

**Comment by jasontaylordev** [comment]
The template is configured to use ASP.NET Core Identity for authenticating and storing users combined with IdentityServer for OpenID Connect. Learn all about it here; https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-7.0.

The Identity pages are provided by ASP.NET Core Identity. If you want to customise the pages, or just see how they work, you can scaffold them into your project using this guide; https://learn.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-7.0&tabs=visual-studio.

Hope this helps, happy coding. 😀
