### ISSUE TITLE
IdentityServer4

### ISSUE THREAD

**Issue by iammukeshm** [jasontaylordev/CleanArchitecture#77]
I notice that IS4 is integrated into this solution. But how is it setup / how is it configured? Is it co-hosted along with the API ? Can i find some documentation or explanation of configuring client and api resource properties.

What would happen if i Remove the ClientAPP Folder? will the API be able to still generate access tokens that i can send to another presentation layer? Kindly let me know in detail. Thanks in Advance

**Comment by jasontaylordev** [comment]
Hi @iammukeshm. This is part of the template is based on the ASP.NET Core Angular SPA template. Here are some resources that you might find helpful:

1. [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio)
2. [Authentication and authorization for SPAs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1)
3. [IdentityServer4 Docs](https://identityserver4.readthedocs.io/en/latest/)

Happy Coding! 😀
