### ISSUE TITLE
When deploying the solution to a website root folder, everything works as expected. However when deploying to a non root folder i.e. as a web application on IIS, all api calls goes to the website root i.e. /api instead of /webapp/api which causes all api calls to fail.

### ISSUE THREAD

**Issue by ayhamallan** [jasontaylordev/CleanArchitecture#770]
When deploying the solution to a website root folder, everything works as expected. However when deploying to a non root folder i.e. as a web application on IIS, all api calls goes to the website root i.e. /api instead of /webapp/api which causes all api calls to fail.

How do I solve this, please?

P.S. I have set the angular base-ref to the /webapp/ and added a web.config redirecting all request to /webapp/ as described as a solution many places to this issue. However the api calls still do not work.

_Originally posted by @ayhamallan in https://github.com/jasontaylordev/CleanArchitecture/discussions/769_

**Comment by Feoni4** [comment]
Try to set the base path during IApplicationBuilder setup:
`app.UsePathBase(mountPathBase)`

**Comment by adameboy** [comment]
HI @ayhamallan  Can you solve it, i have the same problem :(

**Comment by jasontaylordev** [comment]
Closing as not specific to the template.
