### ISSUE TITLE
specification.json file should be updated automatically

### ISSUE THREAD

**Issue by OzanCKN** [jasontaylordev/CleanArchitecture#772]
**Describe the bug**
The specification.json file should be updated automatically when I add a new controller, but it is not updated now.

**To Reproduce**
1. Add new controller 
2. Add new get or post endpoint
3. Start debugging.
4. Go to swagger api screen and you will see nothing updated.

**Expected behavior**
Automatic addition of newly added endpoints and controllers to the file.

**Comment by Feoni4** [comment]
Hello @OzanCKN ,

You can easily add this feature using nswag capabilities:

Just add a [post-build](https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild) event to the WebUI.csproj 
`

    <PropertyGroup>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    </PropertyGroup>

    <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
        <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
    </Target>`

**Comment by jasontaylordev** [comment]
This was removed accidentally, all fixed on `main` now.
