### ISSUE TITLE
API only template version

### ISSUE THREAD

**Issue by danielmackay** [jasontaylordev/CleanArchitecture#776]
**As a** software developer **I would like to** be able to create an API only version of the template **so that** I can use the template to quickly spin up an API only project with minimal manual changes

**Acceptance Criteria**
1. When creating a new project from the template add the ability to pass in a new flag to indicate API only
2. When the flag is specified, none of the Angular code should be present in the template

**Notes**
- To do this cleanly Angular may need to be separated from the API

**Comment by jasontaylordev** [comment]
Covered by #786
