### ISSUE TITLE
Query Item Template

### ISSUE THREAD

**Issue by danielmackay** [jasontaylordev/CleanArchitecture#777]
**As a ** software developer **I would like to** have access to a query item template **so that** I can quickly create new queries as I build software

**Acceptance Criteria**
1. Include a new CLI item template that allows me to create a query
2. Using the template should create a new query similar to the OOTB queries
3. The template should allow a name to be passed which will be used to rename all appropriate code artifacts

**Comment by jasontaylordev** [comment]
Implemented in #881 💥
