### ISSUE TITLE
Command Item Template

### ISSUE THREAD

**Issue by danielmackay** [jasontaylordev/CleanArchitecture#778]
**As a ** software developer **I would like to** have access to a command item template **so that** I can quickly create new commands as I build software

**Acceptance Criteria**
1. Include a new CLI item template that allows me to create a command
2. Using the template should create a new command similar to the OOTB commands
3. The template should allow a name to be passed which will be used to rename all appropriate code artifacts

**Comment by jasontaylordev** [comment]
Implemented in #881 💥
