### ISSUE TITLE
swagger trouble

### ISSUE THREAD

**Issue by coskunsahin** [jasontaylordev/CleanArchitecture#781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
sawgger list unable to update
it doesn't show when we add new api

**Comment by josuave** [comment]
Check the NSwag MSBuild process out. This project uses a static openapi document. @jasontaylordev has referenced this process in one or more of his videos on the "Clean Architecture" videos, see 32:10 in on https://youtu.be/lRYrhj9lwQk
