### ISSUE TITLE
WebUI - Angular - ErrorValidation

### ISSUE THREAD

**Issue by tech-gian** [jasontaylordev/CleanArchitecture#788]
https://github.com/jasontaylordev/CleanArchitecture/blob/10ac3077707e79aaeac60a93d8863bcb109054fc/src/WebUI/ClientApp/src/app/todo/todo.component.ts#L78

As I was looking into the code and "playing" around with all its aspects, I found this little bug. As I was going to create a new List with bad title (example: More than 200 characters), the controller returned me the correct error but it didn't display in the screen. I corrected the problem to my local solution as:

`const errors = JSON.parse(error.response).errors;`

Is it something worth mentioning/changing it in a PR or have you tracked it down?

**Comment by jasontaylordev** [comment]
Thanks for raising this issue. By design, it was supposed to be impossible to make this kind of error. But I forgot to add max length attributes to the various input elements. If you like, please raise a PR so that the input max lengths correspond to the max lengths on the server.
