### ISSUE TITLE
Separate Projects for angular & .net core

### ISSUE THREAD

**Issue by fawadtayyab123** [jasontaylordev/CleanArchitecture#79]
I want to have separate projects for both of angular and .net core.  I tried to separate the solution but I'm stuck at a point. But I want to use clean architecture with given features. kindly guide me in separating angular project or add option in your project.So that we can use in both ways either single solution or separate solutions.Thanks a lot

**Comment by yehudamakarov** [comment]
Just a thought, in the web ui project, you can take the angular code out and leave the controller.

**Comment by fawadtayyab123** [comment]
@yehudamakarov  I'd tried that but application stopped working.

**Comment by yehudamakarov** [comment]
Can you please elaborate? We’re there errors? We’re you able to reach the swagger index?

**Comment by GFoley83** [comment]
Given you've already got an Angular project, I'd suggest you copy the auth services, guards etc. from the `ClientApp` in this solution, into your own. Or copy the logic from your app, into the `ClientApp`.

The logic is already there, it's up to you to figure out how to wire it up. 

These kind of issues are software design problems and not issues or bugs specifically related to this project; which is what Github issues are for. Questions like this really belong on StackOverflow.

**Comment by fawadtayyab123** [comment]
Okay Thanks
