### ISSUE TITLE
Publish to Azure App Service Does Not Work - npm run build -- --prod" exited with code 1

### ISSUE THREAD

**Issue by grikard** [jasontaylordev/CleanArchitecture#80]
**Describe the bug**
The clean architecture template works just fin in Visual Studio 2019. The WebUI will render successfully, as a template and customizations. 

However, every attempt to publish to Azure App services fail. Is there a deployment guide and any reference materials. 

 

**To Reproduce**
1. Go to 'Visual Studio 2019 Publish'
2. Click on 'Select or create app services (any option for windows or linux apps services the same issue' (same on multiple PC - one with a fresh new OS and VS deployment running Node LTS)
3. Wait for build and npm processes with Azure as usual. 
4. Error: The command "npm run build -- --prod" exited with code 1. 

**Expected behavior**
Successful deployment to Azure App Service

**Screenshots**

**Additional context**

**Comment by grikard** [comment]
Multiple attempts. 

1. Install new Clean Architecture pull.
2. Execute WebUI Build and it renders without errors on PC. ASPNetCore.SPA 3.1.0 (have not upgraded in this project to 3.1.2)

After verification application runs on PC. 
3. Execute Publish. 
4. Create new Azure publish profile with new app services, app plan

Failed to deploy successfully 

HTTP Error 500.30 - ANCM In-Process Start Failure
Common solutions to this issue:
The application failed to start
The application started but then stopped
The application started but threw an exception during startup
Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process' stdout messages
Attach a debugger to the application process and inspect
For more information visit: https://go.microsoft.com/fwlink/?LinkID=2028265

**Comment by grikard** [comment]
Interesting - has anyone published Clean Architecture to production at all? I would have thought many folks would have been all over this post. I am working with Microsoft Azure team. Will publish what I find. I suggest Readme include production deployment instructions.

**Comment by swilkodev** [comment]
I ended up running into the same HTTP error 500.30.

To resolve the issue, I first added the setting ASPNETCORE_DETAILEDERRORS = 1 to the web app then refreshed and got the full stack trace of the error. The issue I had was to do with a missing signing certificate used by Identity Server.

This article https://stackoverflow.com/questions/57012001/invalidoperationexception-key-type-not-specified-microsoft-aspnetcore-apiautho discusses the issue and provides links to other articles to guide you on the steps to resolve the issue. Summarising, you need to:-

1. Generate a self signed cert
2. Upload the cert under the Web App - TLS/SSL Settings
3. Add the signing key details under the IdentityServer setting in appsettings.json

"Key": {
    "Type": "Store",
    "StoreName": "My",
    "StoreLocation": "CurrentUser",
    "Name": "CN=<Replace with your subject name>"
  }

I did not change any code. After I did the above, the application works fine.

**Comment by jasontaylordev** [comment]
Thanks all for your work describing the issue, I'll write some documentation for others.
@AdamStephensen - this will be useful for your efforts.

**Comment by grikard** [comment]
It turns out IdentityServer is not supported by Microsoft. So including it in the Clean Architecture template makes no sense. Adding certificate key signing details in code is also NOT A BEST PRACTICE and MUST be avoided since it would not pass security design reviews. My apologies I did not catch this earlier. The Microsoft Azure Team caught it. 

I was really excited about adopting the Clean Architecture template because I agree with the underlining principles of the architecture. However, I am going to have to postpone for now. 

We can't add bad practices to good architecture and expect not to pay a price in the life of the application. Perhaps revisit the Infrastructure layer and look to include reusable components that are supported by the cloud service providers.

**Comment by jasontaylordev** [comment]
This project 100% follows the guidance produced by Microsoft within the document [Authentication and authorization for SPAs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1). The Web UI project incorporates ASP.NET Core Identity for authenticating and storing users combined with IdentityServer for implementing Open ID Connect.

> It turns out IdentityServer is not supported by Microsoft. So including it in the Clean Architecture template makes no sense. 

This approach is supported by Microsoft (they designed the approach and built the templates to match). IdentityServer in-memory is used with this project - see [Microsoft.AspNetCore.ApiAuthorization.IdentityServer](https://www.nuget.org/packages/Microsoft.AspNetCore.ApiAuthorization.IdentityServer/3.1.2). This is part of the ASP.NET Core codebase. Perhaps this has been confused with full-blown IdentityServer4?

> Adding certificate key signing details in code is also NOT A BEST PRACTICE and MUST be avoided since it would not pass security design reviews. My apologies I did not catch this earlier. The Microsoft Azure Team caught it.

Agreed - that is why there are no production certificate key signing details in code. This project follows Microsoft's guidance - [Deploy to production](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production).

> Perhaps revisit the Infrastructure layer and look to include reusable components that are supported by the cloud service providers.

Suggestions welcome.


Gary, I'm sorry this didn't work for you. But thanks for taking the time to raise your concerns. Based on what you have described above I haven't identified any issues or bad practices. If you have something specific to point out (code reference would help), I'll be sure to review and advise. I have some friends on the Azure Team - so I'll even do a sanity check with them.

In the meantime, happy coding. 😀

**Comment by grikard** [comment]
I do love Clean Architecture and its principles and all the great work you have done to surface this as a foundation for application design.  When the Azure Support team told me they do not support IdentityServer it caught me by surprise. I started to wonder if there were other parts of the template not supported. Based on your notes, there is more to the story. It will take me some time to investigate.

My core recommendation stands. The template should be able to publish to Azure as-is. Perhaps we can focus on Angular 9 and deployable? I would like to see this architecture approach to be a foundation for best practices accepted by a much wider international technical community.

Kind regards and wishing everyone a safe and healthy passage through this SARS_COV_2 crisis.

**Comment by jasontaylordev** [comment]
> My core recommendation stands. The template should be able to publish to Azure as-is. Perhaps we can focus on Angular 9 and deployable?

Just a heads up that Angular 9 is already in place, did that yesterday.

**Comment by jasontaylordev** [comment]
You can in fact deploy "as-is" - there are of course many approaches, here is one:

1. **Create a new CI pipeline.** This is for an ASP.NET Core application targeting .NET Core so pick a suitable template to restore, build,  test, and publish the solution. You can simplify to test and publish if you prefer. Configure as normal. no additional tasks required.

2. **Create a new Azure App Service and SQL database.** The selected App Service Plan needs to support SSL. There are no special requirements for the database. Note that the DefaultConnection connection string is automatically added to your App Service configuration.

3. **Add an SSL to the App Service.** If you're not sure how to do this, review this guide: https://benjii.me/2017/06/creating-self-signed-certificate-identity-server-azure/. Be sure to update **appsettings.Production.json**, specifically **IdentityServer:Key:Name**. Also, see; https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1#deploy-to-production. This is where most people get stuck.

4. **Create a new CD pipeline.** This will release the ASP.NET Core application to the new App Service. Just select the Azure App Service Deployment template. Configure as normal, no additional tasks required. Be default, migrations are applied automatically when the app runs (after a release).

That's it! There is nothing that requires special handling and this approach follows Microsoft guidance. If the template wasn't using IdentityServer, you could skip step 3. This approach also applies to apps built out-of-the-box using the commands such as:

```
dotnet new angular --auth Individual
dotnet new react --auth Individual
```

These official ASP.NET Core templates create SPA with Angular or React including ASP.NET Core Identity and IdentityServer. You can learn more here; https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio.

If anyone needs help getting their DevOps pipeline up and running let me know. This is what I do and I am happy to help; https://www.ssw.com.au/ssw/Consulting/Mentoring.aspx.

Happy Coding! 😀

**Comment by jasontaylordev** [comment]
Closing, but feel free to provide feedback at any point.
