### ISSUE TITLE
Non-nullable property '...' is uninitialized. Consider declaring the property as nullable.

### ISSUE THREAD

**Issue by mrmoein** [jasontaylordev/CleanArchitecture#800]
Hi, how can I resolve these warnings?

- Non-nullable property '...' is uninitialized. Consider declaring the property as nullable.
- Auto-property accessor '...set' is never used

i use **Rider** editor and dotnet 6

![Screenshot 2023-02-18 035009](https://user-images.githubusercontent.com/48438999/219820577-80c60ddb-874f-4b79-bfc1-2140034b3e4a.png)
![Screenshot 2023-02-18 035135](https://user-images.githubusercontent.com/48438999/219820580-e5b13b40-11a1-45ee-93b3-c26cf2b081f0.png)

**i dont want to add `= null;` to end of property or use constructor, because it make `set;` color gray**

![Screenshot 2023-02-18 040247](https://user-images.githubusercontent.com/48438999/219821470-96f4e078-84b6-47c5-8104-70222d7e485b.png)
</div>

**Comment by jasontaylordev** [comment]
Suggest using the second example. Remove `= null~;` and change `set;` to `init;`. Of course, it will depend on how you want to interact with the object. Better to ask these questions on StackOverflow, as it is not related specifically to this template.
