### ISSUE TITLE
Automapper between entity and dto cast is not working

### ISSUE THREAD

**Issue by 1988gadocansey** [jasontaylordev/CleanArchitecture#815]
Per the automapper configuration used in this project,

Lists = await _context.TodoLists
                .AsNoTracking()
                .ProjectTo<TodoListDto>(_mapper.ConfigurationProvider)
                .OrderBy(t => t.Title)
                .ToListAsync(cancellationToken)

It uses projection, however

 i find it difficult to do  a simple map between the two without using projection

  var data = await _context.ReligionModels.OrderBy(b => b.Id)
            .FirstOrDefaultAsync(cancellationToken);

        var selectBoxItem = _mapper.Map<ReligionDto>(data);
        return selectBoxItem;

It throws an error.

**Comment by Lanz86** [comment]
In order to support on your issue could you send your  ReligionDto class implementation and the exception stack trace.

**Comment by Lanz86** [comment]
> Per the automapper configuration used in this project,
> 
> Lists = await _context.TodoLists .AsNoTracking() .ProjectTo(_mapper.ConfigurationProvider) .OrderBy(t => t.Title) .ToListAsync(cancellationToken)
> 
> It uses projection, however
> 
> i find it difficult to do a simple map between the two without using projection
> 
> var data = await _context.ReligionModels.OrderBy(b => b.Id) .FirstOrDefaultAsync(cancellationToken);
> 
> ```
>     var selectBoxItem = _mapper.Map<ReligionDto>(data);
>     return selectBoxItem;
> ```
> 
> It throws an error.

@1988gadocansey in order to support you on your issue could you send your ReligionDto class implementation and the exception stack trace.

**Comment by 1988gadocansey** [comment]
public record ReligionDto
{
    public int? Id { set; get; }
    public string? Name { set; get; }

}

public interface IMapFrom<T>
{
    void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType());
}

public static class MappingExtensions
{
    public static Task<PaginatedList<TDestination>> PaginatedListAsync<TDestination>(this IQueryable<TDestination> queryable, int pageNumber, int pageSize) where TDestination : class
        => PaginatedList<TDestination>.CreateAsync(queryable.AsNoTracking(), pageNumber, pageSize);

    public static Task<List<TDestination>> ProjectToListAsync<TDestination>(this IQueryable queryable, IConfigurationProvider configuration) where TDestination : class
        => queryable.ProjectTo<TDestination>(configuration).AsNoTracking().ToListAsync();

    /// <summary>
    /// Sets mapping from source property to destination property. Convenient extension method. 
    /// </summary>
    public static IMappingExpression<TSource, TDestination> MapProperty<TSource, TDestination, TProperty>(
        this IMappingExpression<TSource, TDestination> map,
        Expression<Func<TSource, TProperty>> sourceMember,
        Expression<Func<TDestination, object>> targetMember)
    {
        map.ForMember(targetMember, opt => opt.MapFrom(sourceMember));

        return map;
    }
    public static async Task<TDest> ProjectToObjAsync<TDest>(this IQueryable source, IMapper mapper, TDest obj, CancellationToken cancellationToken = default)
    {
        var loadedObj = await source.ProjectTo<TDest>(mapper.ConfigurationProvider).FirstOrDefaultAsync(cancellationToken);

        if (loadedObj != null)
        {
            mapper.Map(loadedObj, obj);
        }

        return obj;
    }


public class MappingProfile : Profile
{
    public MappingProfile()
    {
        ApplyMappingsFromAssembly(Assembly.GetExecutingAssembly());


    }

    private void ApplyMappingsFromAssembly(Assembly assembly)
    {
        var mapFromType = typeof(IMapFrom<>);

        var mappingMethodName = nameof(IMapFrom<object>.Mapping);

        bool HasInterface(Type t) => t.IsGenericType && t.GetGenericTypeDefinition() == mapFromType;

        var types = assembly.GetExportedTypes().Where(t => t.GetInterfaces().Any(HasInterface)).ToList();

        var argumentTypes = new Type[] { typeof(Profile) };

        foreach (var type in types)
        {
            var instance = Activator.CreateInstance(type);

            var methodInfo = type.GetMethod(mappingMethodName);

            if (methodInfo != null)
            {
                methodInfo.Invoke(instance, new object[] { this });
            }
            else
            {
                var interfaces = type.GetInterfaces().Where(HasInterface).ToList();

                if (interfaces.Count > 0)
                {
                    foreach (var @interface in interfaces)
                    {
                        var interfaceMethodInfo = @interface.GetMethod(mappingMethodName, argumentTypes);

                        interfaceMethodInfo?.Invoke(instance, new object[] { this });
                    }
                }
            }
        }
    }

}

var data = await _context.ReligionModels.OrderBy(b => b.Id) .FirstOrDefaultAsync(cancellationToken);
    var selectBoxItem = _mapper.Map<ReligionDto>(data);
    return selectBoxItem;
 

Error message: Invalid mapper configuration

**Comment by Lanz86** [comment]
@1988gadocansey could you send your ReligionModel  class.

**Comment by 1988gadocansey** [comment]
> @1988gadocansey could you send your ReligionModel class.

using System.ComponentModel.DataAnnotations;

namespace OnlineApplicationSystem.Domain.Entities;


public record ReligionModel
{
    [Key]
    public int Id { set; get; }
    public string? Name { set; get; }

}

**Comment by Lanz86** [comment]
Try to change ReligionDto to

```csharp
public record ReligionDto : `IMapFrom<ReligionModel>`
{
  public int? Id { set; get; }
  public string? Name { set; get; }
}
```

**Comment by 1988gadocansey** [comment]
@Lanz86 I changed the ReligionDto to your implementation however,  encounter a runtime error from Automapper which i guess is the version. I'm running dotnet 7.0.0 so I'm moving to 7.0.3. Finally i've  changed
//services.AddAutoMapper(Assembly.GetExecutingAssembly()); to
        services.AddAutoMapper(cfg => cfg.Internal().MethodMappingEnabled = false, typeof(MappingProfile).Assembly);

Everything worked perfectly.  Thanks.

**Comment by jasontaylordev** [comment]
Thanks team. ❤️
