### ISSUE TITLE
Audit Trail with Audit.EntityFramework (Audit.Net)

### ISSUE THREAD

**Issue by kjartanvalur** [jasontaylordev/CleanArchitecture#820]
I need to be able to create an audit trail so that every change is logged.

Audit.EntityFramework (Audit.Net) Would fit perfectly

I´ve also considered Audit.NET.AzureStorageTables for storing the audit logs with the cheap Azure Storage Table because this log can grow large.

It would be nice if you could choose to add an audit trail feature to the project.

**Additional context**
https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md
https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.AzureStorageTables

**Comment by jasontaylordev** [comment]
I think this is a great option, I'll be sure to star the project so I remember it for next time. I won't add it to the template in the interest of keeping it as simple as possible. Thanks for the suggestion.
