### ISSUE TITLE
Switched from controller to Minimal Api with FastEndpoint

### ISSUE THREAD

**Issue by Lanz86** [jasontaylordev/CleanArchitecture#822]
Switched from controller to Minimal Api with FastEndpoint

I developed on my branch the Minimal Api with FastEndpoint.
If that makes sense or can be useful to others 
@jasontaylordev can is possible create on the main repository a branch where can I do PR? 

My branch is https://github.com/Lanz86/CleanArchitecture/tree/UseMinimalApiFastEndpoint

**Comment by davidpipes** [comment]
Should consider adding endpoint summaries to this as well. Better for documentation reasons. 

https://fast-endpoints.com/docs/swagger-support#swagger-documentation

**Comment by jasontaylordev** [comment]
Hi @Lanz86, thanks for the suggestion. I'm going to switch over to ASP.NET Core Minimal API as per #720.
