### ISSUE TITLE
How to access navigation properties in integration tests?

### ISSUE THREAD

**Issue by artworkad** [jasontaylordev/CleanArchitecture#835]
I would like to test navigational properties like so:

```
var address = await FindAsync<Address>("...");

address.Should().NotBeNull();
address.Country.Id.Should().Be("FR");
```

However I am getting this error:

> System.ObjectDisposedException : Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.

There does not seem to be an easy way to test this. It would be much easier to use the context inside each test, as that would give us maximum flexibility. Not sure if this is possible. An alternative solution would be to pass the include statement as a parameter into FindAsync.

**Comment by jasontaylordev** [comment]
Hello @artworkad. You can extend the `Testing` class with helper methods to suit your requirements. For example:

```csharp
    public static async Task<IEnumerable<TEntity>> ToListAsync<TEntity>(Expression<Func<TEntity, bool>> predicate, params string[] navigationPropertyPaths)
        where TEntity : BaseEntity
    {
        using var scope = _scopeFactory.CreateScope();

        var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        var query = context.Set<TEntity>().AsQueryable();

        foreach(var path in navigationPropertyPaths)
        {
            query.Include(path);
        }

        return await query.Where(predicate).ToListAsync();
    }
```

You might find the following resources helpful in figuring out the right approach:

- https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/tree/master/ContosoUniversity.IntegrationTests
- https://deviq.com/design-patterns/specification-pattern#generic-ef-repository-with-specification

Happy coding! 😀
