### ISSUE TITLE
Allow `IMapFrom` to work with classes that don't implement a default constructor

### ISSUE THREAD

**Issue by JerrettDavis** [jasontaylordev/CleanArchitecture#836]
**Describe the bug**
If you attempt to use the `IMapFrom<TSource>`  interface on classes or records that do not have a default constructor, the built-in `MappingProfile` will throw an exception when it tries to create an instance here:

https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/Application/Common/Mappings/MappingProfile.cs#L27

**To Reproduce**
1. Create a class or record without a default constructor
```csharp
public class TestClass
{
    public int Id { get; set; } 
    public string Name { get; set; }
}

public record TestClassDto (int Id, string Name) : IMapFrom<TestClass>>;
```
3. Use automapper to map `TestClass` to `TestclassDto`
```csharp
var testClass = new TestClass { Id = 1, Name = "Foo" };
var result = _mapper.Map<TestClassDto>(testClass); // <- Will error here today
```

**Expected behavior**
The expectation is that `AutoMapper`'s existing constructor mapping would be used.

--------------------------------------

In my use cases, I've replaced the `var instance = Activator.CreateInstance(type);` line with `var instance = System.Runtime.Serialization.FormatterServices.GetUninitializedObject(type);`. 

While `GetUnitializaedObject` should be used with EXTREME caution, it appears to be a perfect fit here.

**Comment by jasontaylordev** [comment]
Hey @JerrettDavis, what do you think of #871?

**Comment by JerrettDavis** [comment]
> Hey @JerrettDavis, what do you think of #871?

This new approach feels much more in-line with AutoMapper's suggest usage guidelines! I like it.
