### ISSUE TITLE
Implement ```IMapTo``` functionality

### ISSUE THREAD

**Issue by tsafadi** [jasontaylordev/CleanArchitecture#848]
The ```IMapFrom``` function is useful to map an entity to the required query result. It would be nice to have the same functionality for commands. As of right now, the properties of the command have to be mapped manually to the entity. This is very tedious and error prone, especially for entities that have a lot of properties.

**Comment by pflajszer** [comment]
there are couple of things here.
If you really want to use AutoMapper to map DTOs to Entities, you could just amend the default definition of `IMapFrom<T>` by adding a `ReverseMap()` to the end like:

```csharp
public interface IMapFrom<T>
{
    void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType()).ReverseMap();
}
```

However... I did hear that's not a good practice and lack of that reverse mapping is intentional. You can have a look at this in-depth video [here](https://youtu.be/AFcOyF_TWAg?t=904)

The link should take you to the timestamp with the following transcript:

> Auto mapper uh just for mapping out the domain entities to the DTOs now one thing I can just mention on this is that
> we never when it comes to Technologies like Automapper you do not want to map
> your order your inbound details onto your entities okay this the way that this is set up and the way that the
> pattern is created inside of this architecture using these patterns is that the automapper will really only
> allow you to map domain entities into dtos but not vice versa and that's very
> intentional we have seen teams that will go and use Automapper to in fact Auto
> map their DTOs onto their entities but in a lot of senses that can be incredibly dangerous and it can in a
> sense also cause a lot of bugs it's also uh it's it's very risky if you've ever
> had a bit of an experience with Automapper uh where you tried which dealing with collections so we really do
> not recommend taking Automapper even though you can to take Automapper and allow it to map inbound details onto the
> entities because it is extremely risky and can cause all kinds of bugs in your system collections are just one example

**Comment by mdawood1991** [comment]
I went a step further and now have 3 different interfaces

```
public interface IMapFrom<T>
{
    void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType());
}

public interface IMapFromAndTo<T>
{
    void Mapping(Profile profile) => profile.CreateMap(typeof(T), GetType()).ReverseMap();
}

public interface IMapTo<T>
{
    void Mapping(Profile profile) => profile.CreateMap(GetType(), typeof(T));
}
```

This gives me the flexibility to control if I want to Map both `From and To`, or just `To/From`.
e.g for Read Only DTOs, I do `IMapFrom<MyEntity>`
for Create/Update DTOs, I do `IMapTo<MyEntity>`
Then some DTOs I use for read + update Then are `IMapFromAndTo`

Then Update the `MappingProfile` as:

```
public class MappingProfile : Profile
{
    public MappingProfile()
    {
        ApplyMappingsFromAssembly(Assembly.GetExecutingAssembly());
    }

    private void ApplyMappingsFromAssembly(Assembly assembly)
    {
        var mapFromType = typeof(IMapFrom<>);
        var mapFromAndToType = typeof(IMapFromAndTo<>);
        var mapToType = typeof(IMapTo<>);
        
        var mappingMethodName = nameof(IMapFrom<object>.Mapping);

        bool HasInterface(Type t) => t.IsGenericType && (t.GetGenericTypeDefinition() == mapFromType 
            || t.GetGenericTypeDefinition() == mapFromAndToType 
            || t.GetGenericTypeDefinition() == mapToType);
        
        var types = assembly.GetExportedTypes().Where(t => t.GetInterfaces().Any(HasInterface)).ToList();
        
        var argumentTypes = new Type[] { typeof(Profile) };

        foreach (var type in types)
        {
            var instance = Activator.CreateInstance(type);
            
            var methodInfo = type.GetMethod(mappingMethodName);

            if (methodInfo != null)
            {
                methodInfo.Invoke(instance, new object[] { this });
            }
            else
            {
                var interfaces = type.GetInterfaces().Where(HasInterface).ToList();

                if (interfaces.Count > 0)
                {
                    foreach (var @interface in interfaces)
                    {
                        var interfaceMethodInfo = @interface.GetMethod(mappingMethodName, argumentTypes);

                        interfaceMethodInfo?.Invoke(instance, new object[] { this });
                    }
                }
            }
        }
    }
}
```

**Comment by jasontaylordev** [comment]
Hey all, what do you think of #871?

**Comment by tsafadi** [comment]
@jasontaylordev that looks pretty cool! I think that would be a lot easier to maintain.

**Comment by acesteb** [comment]
@mdawood1991 with the refactor in #871  , I'd assume the MapTo and MapFromAndTo logic would simply be added to the nested class?  On a side note, I do agree with the notes from @pflajszer . Mapping DTO's to entities is risky business 😁

**Comment by tsafadi** [comment]
Why would you say it’s risky business @acesteb?

**Comment by jasontaylordev** [comment]
> I'd assume the MapTo and MapFromAndTo logic would simply be added to the nested class

Correct, although you don't have to use a nested class - your call

**Comment by jasontaylordev** [comment]
> Why would you say it’s risky business @acesteb?

When writing back to the entities I prefer to be very explicit about what properties will be set. Sometimes mistakes can be made when doing this automatically, e.g. unintentionally updating a field. Further recommendations from the [AutoMapper Usage Guidelines](https://jimmybogard.com/automapper-usage-guidelines/): 

**X AVOID** [ReverseMap](https://docs.automapper.org/en/stable/Reverse-Mapping-and-Unflattening.html) in cases except when mapping only top-level, non-flattened properties

Reverse mapping can get very complicated very quickly, and unless it's very simple, you can have business logic showing up in mapping configuration.

**Comment by jasontaylordev** [comment]
Thanks for the feedback, everyone. I'll close this off for now since `IMapFrom` and related functionality is no longer in use, please feel free to raise another issue if there is anything else.
