### ISSUE TITLE
Consider adding a unit test for checking the model state of ef core

### ISSUE THREAD

**Issue by hypervtechnics** [jasontaylordev/CleanArchitecture#85]
**Is your feature request related to a problem? Please describe.**
Sometimes developers forget to scaffold a migration.

**Describe the solution you'd like**
Include this unit test by default: https://stackoverflow.com/a/60686198/

**Comment by jasontaylordev** [comment]
Thanks, @hypervtechnics, a great suggestion. I've added this to the product roadmap; https://github.com/jasontaylordev/CleanArchitecture/projects/1#card-35471088.

I'm not sure when I will get to it, but I will let you know when it is done. Happy Coding! 😀
