### ISSUE TITLE
Errors I get when I am builiding WebUI

### ISSUE THREAD

**Issue by SyedMuhammadYasir** [jasontaylordev/CleanArchitecture#855]
### Discussed in https://github.com/jasontaylordev/CleanArchitecture/discussions/851

<div type='discussions-op-text'>

<sup>Originally posted by **SyedMuhammadYasir** May 31, 2023</sup>
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2403	(TS) Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.	C:\My Drive\ThinkSimpleSolution\CleanArchitecture\src\WebUI\ClientApp\tsconfig.json	C:\My Drive\ThinkSimpleSolution\CleanArchitecture\src\WebUI\ClientApp\node_modules\@types\node\globals.d.ts	72	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2307	(TS) Cannot find module '@nguniversal/module-map-ngfactory-loader' or its corresponding type declarations.	C:\My Drive\ThinkSimpleSolution\CleanArchitecture\src\WebUI\ClientApp\tsconfig.json	C:\My Drive\ThinkSimpleSolution\CleanArchitecture\src\WebUI\ClientApp\src\app\app.server.module.ts	3	Active
</div>

**Comment by pflajszer** [comment]
what version of `node` and `npm` are you using?

**Comment by jasontaylordev** [comment]
This is not specific to the template, but I'll offer some basic suggestions. Try the following;

1. Ensure you are running LTS version of node and npm; [https://nodejs.org/en](https://nodejs.org/en)
2. Within **WebUI/ClientApp** delete the **node_modules** folder
3. Within **WebUI/ClientApp**, run `npm install` from the command line
4. Within **WebUI** run `dotnet build` & `dotnet run` from the command line

Hopefully, that helps, if not try and see if you get the same error with a new project by running `dotnet new angular --auth individual` from the command line.

Good luck. ❤️
