### ISSUE TITLE
Screens are getting crashed

### ISSUE THREAD

**Issue by SyedMuhammadYasir** [jasontaylordev/CleanArchitecture#856]
I have started with latest code and when running project everything works fine except when I go to screen 'Todo' Or 'Login' Or 'Register'
I am getting this error

InvalidOperationException: The default Identity UI layout requires a partial view '_LoginPartial' usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration we have looked at it in the following locations: /Areas/Identity/Pages/Account/_LoginPartial.cshtml /Areas/Identity/Pages/_LoginPartial.cshtml /Areas/Identity/Pages/Shared/_LoginPartial.cshtml /Areas/Identity/Views/Shared/_LoginPartial.cshtml /Pages/Shared/_LoginPartial.cshtml /Views/Shared/_LoginPartial.cshtml.

**Comment by jasontaylordev** [comment]
Hi. Did you create the project using a clone of the repo or by installing the template, e.g. `dotnet new install Clean.Architecture.Solution.Template` and `dotnet new ca-sln`?

**Comment by jasontaylordev** [comment]
Closing this issue as I am assuming it has been resolved or is no longer relevant. Feel free to reopen if needed.
