### ISSUE TITLE
Angular Version Upgrade 

### ISSUE THREAD

**Issue by hatimgheewala-GIG** [jasontaylordev/CleanArchitecture#857]
I'm not an expert in this area, but I'm curious about why are we still using Angular 14, And if we have plans to upgrade to Angular 15 which is their LTS. The reason being many of the npm packages are not supported and deprecated for angular 14.

**Comment by jasontaylordev** [comment]
The Angular upgrade is overdue, I just have limited capacity to do it. Should get to it soon.

**Comment by jasontaylordev** [comment]
Updated in #860
