### ISSUE TITLE
Dotnet Run throws error with Dotnet 8.0

### ISSUE THREAD

**Issue by 1988gadocansey** [jasontaylordev/CleanArchitecture#866]
Dotnet 8.0.100-preview.2.23157.25
OS: MacOS

/Users/gadocansey/CleanArchitecture/src/WebUI/WebUI.csproj(73,9): error : NSwag command line tool for .NET Core Net70, toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0));Visit http://NSwag.org for more information.;NSwag bin directory: /Users/gadocansey/.nuget/packages/nswag.msbuild/13.19.0/tools/Net70;Executing file '/Users/gadocansey/CleanArchitecture/src/WebUI/config.nswag' with variables 'Configuration=Debug'...;Launcher directory: /Users/gadocansey/.nuget/packages/nswag.msbuild/13.19.0/tools/Net70;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.;---> System.IO.InvalidDataException: Failed to load configuration from file '/Users/gadocansey/CleanArchitecture/src/WebUI/appsettings.json'.;---> System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonReaderHelper' threw an exception.;---> System.TypeLoadException: Could not load type 'System.Buffers.SearchValues' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.;--- End of inner exception stack trace ---;at System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(ReadOnlySpan`1 text);at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options);at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options);at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input);at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream);at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload);--- End of inner exception stack trace ---;at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload);at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source);at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source);at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource);at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ApplyDefaultAppConfiguration(HostBuilderContext hostingContext, IConfigurationBuilder appConfigBuilder, String[] args);at Microsoft.Extensions.Hosting.HostApplicationBuilder..ctor(HostApplicationBuilderSettings settings);at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults);at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args);at Program.<Main>$(String[] args) in /Users/gadocansey/CleanArchitecture/src/WebUI/Program.cs:line 3;at Program.<Main>(String[] args);at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor);at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr);--- End of stack trace from previous location ---;at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost() in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 271;at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args) in /_/src/NSwag.Commands/HostFactoryResolver.cs:line 75;at NSwag.Commands.ServiceProviderResolver.GetServiceProviderWithHostFactoryResolver(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 146;at NSwag.Commands.ServiceProviderResolver.GetServiceProvider(Assembly assembly) in /_/src/NSwag.Commands/HostApplication.cs:line 70;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 27;at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor);at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr);--- End of inner exception stack trace ---;at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr);at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture);at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132;System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 231;at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275;at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81;at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85;at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 48;at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input);at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input);at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61

**Comment by jasontaylordev** [comment]
The issue is related to the NSwag MSBuild task that occurs after a successful build of WebUI. The task is contained within [WebUI.csproj](https://github.com/jasontaylordev/CleanArchitecture/blob/main/src/WebUI/WebUI.csproj) as follows:

```
    <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' And '$(SkipNSwag)' != 'True' ">
        <Exec ConsoleToMSBuild="true" ContinueOnError="true" WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net70) run /variables:Configuration=$(Configuration)">
            <Output TaskParameter="ExitCode" PropertyName="NSwagExitCode" />
            <Output TaskParameter="ConsoleOutput" PropertyName="NSwagOutput" />
        </Exec>
        
        <Message Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' == '0'" Importance="low" />
        <Error Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' != '0'" />
    </Target>
```

If you run `dotnet build` from the command line you will see the same error. If you then set the environment variable `export SkipNSwag=True` and run `dotnet build` again it should build successfully.

Assuming that NSwag is the problem you then need to check that you have the right .NET SDKs installed. The template requires .NET 8 Preview 5 whereas NSwag is still running on .NET 7. So just run `dotnet --list-sdks` and ensure you have both installed.

This might not resolve the issue, but at least we will have covered the bases. Let me know how you go.

**Comment by 1988gadocansey** [comment]
After upgrading to  8.0.100-preview.5.23303.2 the WebUI compiled
successfully.

Thanks.
