### ISSUE TITLE
.net template 7.0.2 doesn't seem to contain .net 8 and the global.json seems to be old

### ISSUE THREAD

**Issue by jochem4207** [jasontaylordev/CleanArchitecture#867]
**Describe the bug**
When I run ` dotnet new install Clean.Architecture.Solution.Template` it will install version 7.0.2, this doesn't seem to contain .net 8 and the global.json file contains `"version": "7.0.100"`

**To Reproduce**
1. Run: dotnet new install Clean.Architecture.Solution.Template
2. Run dotnet new ca-sln --output YourProjectName
3. Open Global.json and see the old version
4. Open the weather-forecast.ts and see older code then now on the main branch

**Expected behavior**
.net 8 version and updated template

To use the .net 8 version I expect I've to clone the repo instead of using the template?

<img width="436" alt="image" src="https://github.com/jasontaylordev/CleanArchitecture/assets/4976335/a21987d0-6be8-4553-a1a7-4cfa3ab638c1">

**Comment by jasontaylordev** [comment]
You need to install it using the following command:
```
dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.5
```

I've also updated the README to include these instructions.
