### ISSUE TITLE
How should i use ApplicationUser in the Domain?

### ISSUE THREAD

**Issue by DaniaalNadir** [jasontaylordev/CleanArchitecture#87]
I have an Entity in the Domain Layer which needs the ApplicationUser in it. I could just put `public string UserId {get; set;}` but it doesn't seem right. How should i do this. The problem is that it prevents me from doing a `.Include(x => x.User)` on the entity which would be useful.

**Comment by GFoley83** [comment]
This question has been asked and answered many times. See below:

https://github.com/jasontaylordev/CleanArchitecture/issues/58#issuecomment-584055887
https://github.com/jasontaylordev/CleanArchitecture/issues/71
https://github.com/jasontaylordev/CleanArchitecture/issues/30

**Comment by DaniaalNadir** [comment]
@GFoley83  Yeah i saw as soon as i posted the question. I tried to delete the issue but couldn't. Sorry about that and thanks for the links.

**Comment by GFoley83** [comment]
Just close off the issue when you can @DaniaalNadir. Cheers.
