### ISSUE TITLE
Add TestStartup for integration test

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#88]
**Is your feature request related to a problem? Please describe.**
Test Service Providers in the Infrastructure/DependencyInjection

**Describe the solution you'd like**
Add TestStartup for integration test
Remove Test Service Providers from the Infrastructure/DependencyInjection for tests

**Comment by jasontaylordev** [comment]
This is a great suggestion. I am looking to rewrite the tests shortly using a different approach. I'll be removing conditional test logic within Infrastructure/DependencyInjection and also adding subcutaneous tests targeting the Application layer.

As this will be covered in that work, I am closing this issue. Happy Coding! 😀
