### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by hypervtechnics** [jasontaylordev/CleanArchitecture#9]
**Is your feature request related to a problem? Please describe.**
The pipeline behaviour regarding the authorize attribute is always trying to resolve the user. Maybe this should be more dynamic regarding the `AllowAnonymous `or the not existing `Authorize` attributes.

**Describe the solution you'd like**
Respect the filters set to the route.

**Describe alternatives you've considered**
Replacing `FirstAsync` with `FirstOrDefaultAsync` and `user.UserName` with `user?.UserName`.

**Additional context**
*-*

**Comment by Pyrobolser** [comment]
I think this issue is because of the **RequestLogger** trying to find a user for every request, even anonymous one. If you don't have a current user, you should log this request as anonymous or log something else like the client ip for example.

**Comment by hypervtechnics** [comment]
I just removed logging of user name for now. But will think about that one. Thank you

**Comment by hypervtechnics** [comment]
There are two calls to `GetUserNameAsync`. If the underlying storage is a database for example this would involve two requests to the database per request. Is it possible to mitigate this one? E.g. loading the user only once or during construction of ICurrentUserService.

**Comment by jasontaylordev** [comment]
Sorry for the delay on this issue. It has been resolved now.
