### ISSUE TITLE
Separate Angular client project

### ISSUE THREAD

**Issue by chelabitarik** [jasontaylordev/CleanArchitecture#90]
Hi everyone,
I came a cross this amazing template so thank you guys for the awesome work . I just wanna make a simple request if thats possible ... Please separate the Angular client from the .net core server.
Thank you so much

**Comment by jasontaylordev** [comment]
Thanks @chelabitarik, appreciate your kind words. Separating Angular / .NET Core is not something I am looking to support/demonstrate in this solution. However, you might like to review the suggestions within #79.

Happy Coding! 😀
