### ISSUE TITLE
Wrong URL being used when launching WebAPI in browser

### ISSUE THREAD

**Issue by acesteb** [jasontaylordev/CleanArchitecture#912]
**Describe the bug**
When running the WebAPI, the browser is launching with `https://localhost:5001/https:localhost:5001/api` instead of `https://localhost:5001/api`

**To Reproduce**
1. Create a Web API-only solution:
2. Run WebAPI project
3. Browser being launched with incorrect URL

**Expected behavior**
When running WebAPI, should launch browser with `https://localhost:5001/api` URL

**Additional context**
In launchSettings, launch URL should be `launchUrl": "https://localhost:5001/api`, instead of `launchUrl": "https:localhost:5001/api`. i.e missing forward slash.

**Comment by jasontaylordev** [comment]
Thanks for creating this issue, the bug has been fixed. 😀
