### ISSUE TITLE
Pagination by Date

### ISSUE THREAD

**Issue by tzdevelopteam** [jasontaylordev/CleanArchitecture#916]
I believe there is a significant need to get values with pagination based on dates.
My suggestion is to include an option that allows returning a list through pagination based on either the creation date or the modified date.

**Comment by jasontaylordev** [comment]
Please can you describe the feature in greater detail? Do you want to filter based on creation or modified date, and then paginate the results? If so, you can accomplish it this way:

```csharp
        return await _context.TodoItems
            .Where(i => i.ListId == request.ListId && i.Created.Date == DateTime.Now.Date)
            .OrderBy(i => i.Title)
            .ProjectTo<TodoItemBriefDto>(_mapper.ConfigurationProvider)
            .PaginatedListAsync(request.PageNumber, request.PageSize);
```

The above query returns a paginated list of items belonging to a specific list (`i.ListId == request.ListId`) and created today (`i.Created.Date == DateTime.Now.Date`).

**Comment by tzdevelopteam** [comment]
something like this:

`public class PaginatedList<T> where T : IEntity
{
    public List<T> Items { get; }
    public int TotalCount { get; }
    public int TotalPages { get; }

    public int? PageNumber { get; }
    public DateTime? From { get; }

    public PaginatedList(List<T> items, int count, int pageNumber, int pageSize)
    {
        PageNumber = pageNumber;
        TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        TotalCount = count;
        Items = items;
    }

    public PaginatedList(List<T> items, int count, DateTime from, int pageSize)
    {
        From = from;
        TotalPages = (int)Math.Ceiling(count / (double)pageSize);
        TotalCount = count;
        Items = items;
    }

    public bool? HasPreviousPage => PageNumber.HasValue ? PageNumber > 1 : null;

    public bool? HasNextPage => PageNumber.HasValue ? PageNumber < TotalPages : null;

    public static async Task<PaginatedList<T>> CreateAsync(IQueryable<T> source, int pageNumber, int pageSize, CancellationToken cancellationToken)
    {
        var count = await source.CountAsync(cancellationToken);
        var items = await source.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToListAsync(cancellationToken);

        return new PaginatedList<T>(items, count, pageNumber, pageSize);
    }

    public static async Task<PaginatedList<T>> CreateAsync(IQueryable<T> source, DateTime from, int pageSize, CancellationToken cancellationToken)
    {
        var filtered = source.Where(m => m.Created < from);
        var count = await filtered.CountAsync(cancellationToken);
        var items = await filtered.OrderByDescending(m => m.Created).Take(pageSize).ToListAsync(cancellationToken);

        return new PaginatedList<T>(items, count, from, pageSize);
    }
}`

**Comment by jasontaylordev** [comment]
Thanks for the example. However, I'd prefer to keep filtering separate. It's easy enough to accomplish your requirements without further changes:

```csharp
return await _context.TodoItems
    .Where(i => i.Created < from)
    .PaginatedListAsync(request.PageNumber, request.PageSize);
```

**Comment by tzdevelopteam** [comment]
Yeah, but let's consider the scenario of a chat page. I want to be able to
scroll up and view previous messages. However, with the current pagination
system, only the first 20 messages are loaded initially. If a new message
arrives, the previous last message will now be on the second page. To
address this issue, one possible solution is to pass the last date and
retrieve messages from that point onwards.

‫בתאריך יום ג׳, 11 ביולי 2023 ב-6:38 מאת ‪Jason Taylor‬‏ <‪
***@***.***‬‏>:‬

**Comment by jasontaylordev** [comment]
I understand that there will be edge cases where this capability will be useful. So that I can easily maintain and improve this template, it needs to be kept as simple as possible. I'm happy to support the general case, but not edge cases.

**Comment by tzdevelopteam** [comment]
I don't think these are edge cases. Please don't limit your thinking to
just chat scenarios. Consider all the scenarios where Infinite Scroll is
used.

‫בתאריך יום ג׳, 11 ביולי 2023 ב-13:58 מאת ‪Jason Taylor‬‏ <‪
***@***.***‬‏>:‬

**Comment by jasontaylordev** [comment]
Thanks @tzdevelopteam, I'll keep it in mind.
