### ISSUE TITLE
Migrations failing after initial setup

### ISSUE THREAD

**Issue by acesteb** [jasontaylordev/CleanArchitecture#917]
**Describe the bug**
Migration after initial setup is changing things it shouldn't be

**To Reproduce**
1. Create a Web API-only solution:
2. Run WebAPI project
3. Everything works as expected so far. i.e  Db is auto created and latest migration is applied
4. Without making **any** changes, run this command `dotnet ef migrations add "SampleMigration" --project .\src\Infrastructure --startup-project .\src\WebApi\ --output-dir Data\Migrations`
5. I would expect this to create an empty migration, but it creates a rather verbose migration that updates alot of things
6. In any case, I try to apply this "Sample Migration" to the db and expectedly get errors

**Expected behavior**
When running an empty migration after initial setup, migration file should not alter any existing schemas

**Comment by jasontaylordev** [comment]
Thanks for raising this issue! ❤️ 

It has been resolved in the [latest version](https://www.nuget.org/packages/Clean.Architecture.Solution.Template/8.0.0-preview.5.14):

```bash
dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.5.14
```

Let me know if you run into any other issues.
