### ISSUE TITLE
Where to put the types involved external resource, git/web/file

### ISSUE THREAD

**Issue by howardgod** [jasontaylordev/CleanArchitecture#94]
My scenario comes like this, I want to get the user data from JIRA server(external web resource) and then compare to my user entity data and then create a viewModel back to Presentation layer(client).

Application\Common\Interfaces
```
interface IJiraUserService
{
    JiraUserObject GetJiraUser(string queryUserName);
}
```
Application\User\GetUserJira\
```
public class GetUserFromJiraQuery : IRequest<UserVm>
{
    public string QueryUserName { get; set; }
}
```

I wonder where should "JiraUserObject" type to put into?
1. Create a folder named "ExternalTypes" in Domain, because it's just like a type for db, they all related to external resources?
2. Put it into Domain\ValueObjes\, but I'm not sure if it fits into "ValueObject"
3. Treat it like Dto or VM, put it into Application, maybe Application\User\GetUserJira or create a new  folder, Application\SharedType

Any suggestions would be much appreciated.

Howard

**Comment by jasontaylordev** [comment]
Hi Howard. Implement as follows:

1. Add the `IJiraUserService` interface within Application layer as suggested above
2. Add the types associated with the service to the Application layer also, e.g. `JiraUserObject`
3. Create the implementation within Infrastructure, mapping from Jira types to Application types, e.g. `JiraUserObject`.
4. Inject `IJiraUserService` into commands / queries that require the `JiraUserObject`. Don't create specific queries / commands just for interaction within the new service. Since queries / commands should map to business use cases.

Hope this helps.

Happy Coding! 😀

**Comment by howardgod** [comment]
Hi Jason,

Thank you very much for the comment. 

Just to extend a bit for the question. What if I had a service which actually is a business use case, e.g. every time we create a new data, we not only store to DB but Git as well. In this case, which approach would be better practice(btw, I not quite sure if it fits business use case)?

1. Implement GitService as queries / commands, and in the controller, we send both CreateDataToDbCommand and CreateDataToGitCommand. 

2. Still use the same CreateDataCommand, but in handler, we manipulate both db and git to accomplish the goal.

Thank you,

Howard

**Comment by dirocchini** [comment]
Hi Jason!
In my point of view you should make things cleaner and specific. I think you should create, in your controller, both a GitServiceCommand and DbCommand (for eg) and make both calls to specific commands.

**Comment by jasontaylordev** [comment]
I don't think of business use cases in terms of database and other infrastructure or persistence mechanisms. They are defined in business terms and are usually something like CreateCustomer or CreateOrder, ShipOrder, or UpdateOrder. I'd normal define them using this approach; https://en.wikipedia.org/wiki/Use_case#Fowler_style.

It sounds to me that you have a non-functional requirement - "Every time we create a new data, we not only store to DB but Git as well."

Described in that way, this feels very much like a cross-cutting concern at the persistence level. Given that, another approach you could take is to implement this behaviour within the DbContext. You could inject an IJiraService into the DbContext and then override SaveChangesAsync and use the EF Core ChangeTracker to determine what changes to write to Jira.

This approach treats the NFR as a cross-cutting concern and avoids the need to implement this requirement in multiple places. If this requirement changes in the future it can easily be updated or removed.

**Comment by jasontaylordev** [comment]
Thanks for your question, happy coding! 😀
