### ISSUE TITLE
Add Worker Service project for cronjobs and background queue jobs

### ISSUE THREAD

**Issue by litan1106** [jasontaylordev/CleanArchitecture#95]
[Hosted Serviced](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio)

**Comment by jasontaylordev** [comment]
This is a good idea. Thanks. I've added an item to the roadmap - https://github.com/jasontaylordev/CleanArchitecture/projects/1#card-35468080. 

I'm not sure when I will get it done.

**Comment by Greenmachine52** [comment]
Hi there! @jasontaylordev I have some free time and could it done shortly.
Would you consider Hangfire rather than IHostedServices?
