### ISSUE TITLE
Microsoft.NET.Sdk.Razor.SourceGenerators Error

### ISSUE THREAD

**Issue by maksudcs** [jasontaylordev/CleanArchitecture#950]
Hello,

I have installed .Net SDK 8.0.100-preview.6 and after build getting following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS9057	The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler, which is newer than the currently running version '4.6.0.0'.	Web	C:\Users\Fin Source\source\repos\CleanArchitecture\src\Web\CSC	1	Active

Thanks

**Comment by jasontaylordev** [comment]
Hello. I encounter this error too when building .NET 8 preview projects in Visual Studio 2022. 
Try again using [Visual Studio 2022 Preview](https://visualstudio.microsoft.com/vs/preview/) and let me know if this resolves your issue.

**Comment by maksudcs** [comment]
Hello, This is my current VS.

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.5

**Comment by jasontaylordev** [comment]
I recommend try with:

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.7.0 Preview 4.0

https://visualstudio.microsoft.com/vs/preview/

**Comment by MedBouc** [comment]
I'm facing the same issue with Visual Studio Enterprise Edition 2022 (Version 17.6.5) and .NET 8.0.100-preview.6.23330.14.
 To reproduce it, just create a new Blazor project and try to compile it

I'll give a try to VS 17.7.0 Preview 5.0 and see

**Comment by jasontaylordev** [comment]
Thanks for checking and confirming @MedBouc. Thanks also for your support. 😀
@maksudcs I'll assume that this will resolve your problem and close this issue.
