### ISSUE TITLE
VS2022 & .NET 8-prev.6: Build fails due to expecting Microsoft.NET.Sdk.Razor.SourceGenerators.dll-version 4.7.0.0

### ISSUE THREAD

**Issue by Twoleeland** [jasontaylordev/CleanArchitecture#960]
**Describe the bug**
The project "Web" fails to build with:
Error CS9057: The analyzer assembly 'C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll' references version '4.7.0.0' of the compiler, which is newer than the currently running version '4.6.0.0'.

**To Reproduce**
1. Uninstall all .NET 8-preview-SDKs.
2. Install "dotnet-sdk-8.0.100-preview.6.23330.14-win-x64.exe" as stated in global.json.
3. Create directory ```C:\Sources```.
4. Launch PowerShell.
5. Execute ```dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.6.16```, if not already done.
6. Execute ```cd C:\Sources```.
7. Execute ```dotnet new ca-sln --client-framework Angular --output CleanArchitectureSolution```.
8. Execute ```cd src/Web```.
9. Execute ```dotnet run```.
10. All gets build and the web app is running (- leaving aside issues with https and dev-certs).

BUT(!!!), going two steps back to 8. and do the following:
1. Open newly created solution in VS 2022.
2. Set project "Web" under "src" as start-up-project.
3. Try to run (or debug) the web app in web browser through VS 2022. Result: see the error at the top.

**Expected behavior**
This should also work in VS 2022. 😉

**Additional context**
My config: Windows 11 Pro with latest updates, VS 2022 Pro v17.6.5.

PS: If using previous release of .NET 8 (dotnet-sdk-8.0.100-preview.5.23303.2-win-x64.exe) and changing the version in global.json the build process works fine in VS 2022.

**Comment by jasontaylordev** [comment]
You need to use Visual Studio 2022 Preview (Version 17.7.0 Preview 5.0 or later) to avoid this issue.

**Comment by Twoleeland** [comment]
> You need to use Visual Studio 2022 Preview (Version 17.7.0 Preview 5.0 or later) to avoid this issue.

Thanks for the tip! 😉 As said, with VS2022 17.6.5 and .NET 8.0.100-preview.5.23303.2 it's also working without having to install VS2022 Preview. Although they say for the supported VS2022-version: Visual Studio 2022 (v17.7 Preview 2) and later. Really, a very curious behavior... 🙈😅
