### ISSUE TITLE
Fetch Data throwing  error : InvalidOperationException: The default Identity UI layout requires a partial view '_LoginPartial' usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work

### ISSUE THREAD

**Issue by SheikPyari** [jasontaylordev/CleanArchitecture#963]
Hi Jason,

I have created a SPA with React and ASP.NET Core with   Clean.Architecture.Solution.Template::8.0.0-preview.6.11 , once application created UI will be Look like below
![image](https://github.com/jasontaylordev/CleanArchitecture/assets/140445721/319cefb2-d2bc-412d-af11-cca2841128b7)
when Click on Fetch data getting error below, 

![image](https://github.com/jasontaylordev/CleanArchitecture/assets/140445721/3fa7ccda-a998-4e06-abea-6ff0cadc50b5)

Pls help me.

Regards,
Sheik.

**Comment by jasontaylordev** [comment]
Thanks for reporting this issue. Please can you try again ensuring you are running the latest .NET 8 SDK:

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

And the latest version of the template:

dotnet new install Clean.Architecture.Solution.Template::8.0.0-*

If you still encounter the issue, let me know the commands / approach you used to build and run the application.

**Comment by SheikPyari** [comment]
Hi Jason, still am getting same error, i have not done any coding from my end just testing your template, 

Regards,
Sheik.

**Comment by jasontaylordev** [comment]
Sorry I don't have enough information to help.

What versions of the template / .NET SDK / Node / npm are you running?
What commands did you use to build and run the application?
Have you tried building from the command-line? e.g. dotnet build
Does 'dotnet build' produce any errors or complete successfully?

**Comment by SheikPyari** [comment]
Hi Jason,

Template Using
dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.6.11

To create a SPA with React and ASP.NET Core:

dotnet new ca-sln -cf React -o YourProjectName

once project created i open from Visualstudio 2022, and run the application

**Comment by jasontaylordev** [comment]
You are using an old version of the template, make sure you upgrade to the latest;
```bash
dotnet new install Clean.Architecture.Solution.Template::8.0.0-*
```

You also need to use Visual Studio 2022 Preview;

https://visualstudio.microsoft.com/vs/preview/

**Comment by jasontaylordev** [comment]
[Tutorial: Create an ASP.NET Core app with React in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
