### ISSUE TITLE
Getting error like  The method 'get' on path '/api/Vendor' is registered multiple times

### ISSUE THREAD

**Issue by SheikPyari** [jasontaylordev/CleanArchitecture#974]
Hi Jason,
I have created the project using template

dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.6.18

and To create a ASP.NET Core Web API-only solution:

dotnet new ca-sln -cf None -o VCPAPI

I have created the endpoint to GetbyId and GetAll 

    public async Task<VendorVm> GetVendor(ISender sender)
    {
        return await sender.Send(new GetVendorQuery());
    }

[HttpGet("getvendorbyid")]
    public async Task<VendorByIdVm> GetVendorById(ISender sender, [FromBody] GetVendorByIdQuery command)
    {
        return await sender.Send(command);
    }

and added endpoint router
 public static IEndpointRouteBuilder MapGetById(this IEndpointRouteBuilder builder, Delegate handler, string pattern = "")
    {
        Guard.Against.AnonymousMethod(handler);

        builder.MapGet(pattern, handler)
            .WithName(handler.Method.Name);

        return builder;
    }

am getting below error 
Severity	Code	Description	Project	File	Line	Suppression State
Error		NSwag command line tool for .NET Core Net70, toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0));Visit http://NSwag.org for more information.;NSwag bin directory: C:\Users\Sheik\.nuget\packages\nswag.msbuild\13.19.0\tools\Net70;Executing file 'config.nswag' with variables 'Configuration=Debug'...;Launcher directory: C:\Users\Sheik\.nuget\packages\nswag.msbuild\13.19.0\tools\Net70;System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.;---> System.InvalidOperationException: The method 'get' on path '/api/Vendor' is registered multiple times.;at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver);at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver);at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups);at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithDocumentProviderAsync(IServiceProvider serviceProvider) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 300;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 289;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30;at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor);at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr);--- End of inner exception stack trace ---;at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr);at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture);at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters);at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in /_/src/NSwag.AspNetCore.Launcher/Program.cs:line 132;System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.;at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiCommand.cs:line 231;at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in /_/src/NSwag.Commands/NSwagDocumentBase.cs:line 275;at NSwag.Commands.NSwagDocument.ExecuteAsync() in /_/src/NSwag.Commands/NSwagDocument.cs:line 81;at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 85;at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32;at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input);at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input);at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61	Web	D:\Workspace\Vendor_Collaboration_Portal\Development\VCPAPI\src\Web\Web.csproj	42

**Comment by jasontaylordev** [comment]
I can help, just need a little more information. I'll assume that there is an /Endpoints/Vendors.cs file and that it contains all Vendor endpoints. Correct me if I'm wrong, otherwise please can you share the contents of that file?

**Comment by SheikPyari** [comment]
Yes.. you are right and  code below  is 

using VCPAPI.Application.TodoLists.Commands.DeleteTodoList;
using VCPAPI.Application.VENDOR.Commands.CreateVENDOR;
using VCPAPI.Application.VENDOR.Queries.GetVendor;
using VCPAPI.Application.VENDOR.Commands.DeleteVendor;
using VCPAPI.Application.VENDOR.Commands.UpdateVendor;
using VCPAPI.Application.VENDOR.Queries.GetVendorById;
using Microsoft.AspNetCore.Mvc;
using NSwag.Annotations;

namespace VCPAPI.Web.Endpoints;

public class Vendor : EndpointGroupBase
{
    public override void Map(WebApplication app)
    {
        app.MapGroup(this)
            .RequireAuthorization()
            .MapGet(GetVendor)
            .MapGetById(GetVendorById,"{VendorId}")
            .MapPost(CreateVendor)
            .MapPut(UpdateVendor)
            .MapDelete(DeleteVendor);
    }
    [HttpGet] 
    [Route("Vendor/getAllvendors")]
    public async Task<VendorVm> GetVendor(ISender sender)
    {
        return await sender.Send(new GetVendorQuery());
    }

    [HttpGet]
    //[Route("Vendor/getvendorbyid")]
    //[SwaggerOperation("GetByUsername")]
    [Route("api/Vendor/getvendorbyid")]
    public async Task<VendorByIdVm> GetVendorById(ISender sender, [FromBody] GetVendorByIdQuery command)
    {
        return await sender.Send(command);
    }

    public async Task<string> CreateVendor(ISender sender, CreateVendorCommand command)
    {
        return await sender.Send(command);
    }

    public async Task<IResult> UpdateVendor(ISender sender,UpdateVendorCommand command)
    {
       // if (vendorId != command.VENDORID) return Results.BadRequest();
        await sender.Send(command);
        return Results.NoContent();
    }

    //public async Task<IResult> DeleteVendor(ISender sender, string VendorId)
    //{
    //    await sender.Send(new DeleteVendorCommand(VendorId));
    //    return Results.NoContent();
    //}

    public async Task<IResult> DeleteVendor(ISender sender, [FromBody] DeleteVendorCommand command)
    {
        await sender.Send(command);
        return Results.NoContent();
    }
    //[HttpDelete]
    //public async Task<IResult> Delete(ISender sender,string VendorId)
    //{
    //    await sender.Send(new DeleteVendorCommand ( VendorId ));

    //    return Results.NoContent();
    //}
}

**Comment by jasontaylordev** [comment]
Thanks for sharing the code. Start by removing any attrributes, they are not required. For example:

```csharp
[HttpGet]
//[Route("Vendor/getvendorbyid")]
//[SwaggerOperation("GetByUsername")]
[Route("api/Vendor/getvendorbyid")]
```

Get requests don't have a body, so update the signature of `GetVendorById`:

```diff
-public async Task<VendorByIdVm> GetVendorById(ISender sender, [FromBody] GetVendorByIdQuery command)
+public async Task<VendorByIdVm> GetVendorById(ISender sender, int vendorId)
```

Take a look at the code inside the **Web\Infrastructure**:

* **WebApplicationExtensions.cs**: Includes `MapGroup` extension methods
* **IEndpointRouteBuilderExtensions**: Includes `Map[Get|Post|Put|Delete]` extension methods

This will help you understand what's happening under the hood.

Also review the [Minimal API quick reference](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-8.0) to help get up to speed with Minimal API.

I've adapted the TodoLists example to include a GetById:

```csharp
public class TodoLists : EndpointGroupBase
{
    public override void Map(WebApplication app)
    {
        app.MapGroup(this)
            .RequireAuthorization()
            .MapGet(GetTodoLists)
            .MapGet(GetTodoListById, "{id}")
            .MapPost(CreateTodoList)
            .MapPut(UpdateTodoList, "{id}")
            .MapDelete(DeleteTodoList, "{id}");
    }

    public async Task<TodosVm> GetTodoLists(ISender sender)
    {
        return await sender.Send(new GetTodosQuery());
    }

    public async Task<TodoListDto> GetTodoListById(ISender sender, int id)
    {
        await Task.CompletedTask;

        return new TodoListDto { Id = id, Title = "Todo List" };
    }

    public async Task<int> CreateTodoList(ISender sender, CreateTodoListCommand command)
    {
        return await sender.Send(command);
    }

    public async Task<IResult> UpdateTodoList(ISender sender, int id, UpdateTodoListCommand command)
    {
        if (id != command.Id) return Results.BadRequest();
        await sender.Send(command);
        return Results.NoContent();
    }

    public async Task<IResult> DeleteTodoList(ISender sender, int id)
    {
        await sender.Send(new DeleteTodoListCommand(id));
        return Results.NoContent();
    }
}

```

The preceding code is working correctly. Hope this helps, happy coding! 😀

**Comment by SheikPyari** [comment]
Hi Jason,

Very thanks for your help, but I don't want to send the  Id from query string, I want to send from body pls help me  how to do that.

**Comment by SheikPyari** [comment]
Hi Jason,

I got it how to do, thanks for your help.

**Comment by SheikPyari** [comment]
Thank you so much for your help.
