### ISSUE TITLE
Fetching Entity Data with User details in application layer 

### ISSUE THREAD

**Issue by 3kwartappel** [jasontaylordev/CleanArchitecture#98]
**The Problem**
Another question regarding the ApplicationUser.. it would be great to have an example of this in the project. As discussed in other threads its not recommended to move the ApplicationUser to the Domain layer.

In our Application Layer, we are trying to fetch all ToDoItems in the database, including the Email Address (and other user details) of the user that created the TodoItem. How to do this as elegantly as possible?

Currently, the only solution I can think of is doing the DB call to fetch all the TodoItems which includes the UserIds linked. Then do a separate fetch through the userManager or something?
![image](https://user-images.githubusercontent.com/302664/78379320-75e8e280-75d2-11ea-86df-2ef8bd87dfef.png)

...and then join this data in the Application layer. But this feels a bit backwards. I am sure lots of systems needs the user detail (like email and username) linked to other data which needs to be displayed.

**Ideal solution**
An example of how this can be implemented in the project here, or somewhere else in the project would be nice
![image](https://user-images.githubusercontent.com/302664/78378264-07efeb80-75d1-11ea-8683-68fa6ddf512f.png)

**Alternatives I have considered**
I have read through the previous issues regarding getting user information in the Application/Domain layer.
https://github.com/jasontaylordev/CleanArchitecture/issues/87
https://github.com/jasontaylordev/CleanArchitecture/issues/58
https://github.com/jasontaylordev/CleanArchitecture/issues/71
https://github.com/jasontaylordev/CleanArchitecture/issues/30
https://github.com/jasontaylordev/CleanArchitecture/issues/74

**Comment by jasontaylordev** [comment]
With the current design, it will be necessary to do in two queries. Alternatively, you could make a User that is part of the Domain model. The user might start out something like this:

public class User 
{
    public int Id { get; set; }
    public string ApplicationUserId { get; set; } // From Identity
    public string Name { get; set; } // User display name
    public string Email { get; set; }
}

Now that user will be part of the Domain model, you can implement using a single query.

You will need to keep ApplicationUser and User in sync, but this would be a fairly trivial exercise within the relevant commands.

Happy Coding! 😀

**Comment by michelebenolli** [comment]
"With the current design, it will be necessary to do in two queries." In N+1 queries, one in addition for each user. What do you suggest for a user-centric application? Is there a clean way to link the User domain entity with the IdentityUser?
