### ISSUE TITLE
search and sort missing

### ISSUE THREAD

**Issue by mukeshsalaria01** [jasontaylordev/CleanArchitecture#985]
**Is your feature request related to a problem? Please describe.**
I was looking for search and sort feature in the architecture. But I didn't find any extension which will do filters and sort of columns. Any suggestions how it can be done?

**Describe the solution you'd like**
I want to do search and sort by passing column name and sort order for sorting and for search again column names and search based on that.

**Describe alternatives you've considered**
N/A

**Additional context**
Like PaginatedListAsync() can we have Sort() and Search() methods while doing query?

**Comment by DennisJansenDev** [comment]
Did you try googling on how to accomplish that?

**Comment by ShreyasJejurkar** [comment]
This might be helpful! https://github.com/jasontaylordev/CleanArchitecture/pull/121

**Comment by jasontaylordev** [comment]
Hi @mukeshsalaria01. These features are provided by EF Core. The following tutorial covers sort, filter, page, and group along with many other great topics; [Razor Pages with Entity Framework Core in ASP.NET Core](https://learn.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-8.0&tabs=visual-studio). Happy coding! 😀
