### ISSUE TITLE
[Support/Guidance] Update old solution to use new template

### ISSUE THREAD

**Issue by SuliemanMansouri** [jasontaylordev/CleanArchitecture#99]
Hi,
How do I update an old solution that is using version 1.0.2 to the latest version 1.0.10.
Reinstalling the template with --force option will replaced old files with new ones. This will result in loss of old code.

If this feature is not included in dotnet command line tools, how can I update my project to use the latest fixes in the template?

Thanks

**Comment by jasontaylordev** [comment]
Hi @SuliemanMansouri,

There is no supported upgrade process. I'd suggest the following approach:

1. Uninstall the current version of the template:
   `dotnet new --uninstall Clean.Architecture.Solution.Template`
2. Install the old version of the template:
    `dotnet new --install Clean.Architecture.Solution.Template::1.0.2`
3. Create a new project based on the old template:
   `dotnet new ca-sln`
4. Create a new local git repo and commit initial changes:
   `git init`
   `git add .`
   `git commit -m "Initial Commit"`
5. Install the latest version of the template:
    `dotnet new --install Clean.Architecture.Solution.Template`
6. Overwrite the old template with the new template:
   `dotnet new ca-sln --force`
7. Compare the changes using your favourite tool, e.g. VS Code:
   ![image](https://user-images.githubusercontent.com/1988321/78557961-1cdcb100-7855-11ea-9606-ec758db19796.png)

I hope this helps, at least you can clearly see what has changed and decide whether or not to apply these changes to your project. 

Apologies there is not a simpler approach. 

Happy Coding! 😀

**Comment by SuliemanMansouri** [comment]
Hi @jasontaylordev 
Thanks for the reply. I was hoping that dotnet has a merge feature that I didn't know about.
Cheers
