### ISSUE TITLE
Add a docker support for Clean Architecture

### ISSUE THREAD

**Issue by mansoor1998** [jasontaylordev/CleanArchitecture#990]
**Is your feature request related to a problem? Please describe.**
Docker support would be great.

**Describe the solution you'd like**
Dockerfile and docker yml

**Comment by petrubocsanean** [comment]
With .net 8 you don't need a Dockerfile. 
You can build a docker image by running the following command: 

`dotnet publish src/Web/Web.csproj --os linux --arch x64 /t:PublishContainer -c Release --self-contained true`

You can read more here:
https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container
