### ISSUE TITLE
Getting error CS1061	'AspNetCoreOpenApiDocumentGeneratorSettings' does not contain a definition for 'SchemaProcessors' and no accessible extension method 'SchemaProcessors' accepting a first argument of type 'AspNetCoreOpenApiDocumentGeneratorSettings' could be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by SheikPyari** [jasontaylordev/CleanArchitecture#999]
Hi Jason,

Hi Jason,
I have created the project using template

dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.6.18

and To create a ASP.NET Core Web API-only solution:

dotnet new ca-sln -cf None -o VCPAPI

am getting error like 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'AspNetCoreOpenApiDocumentGeneratorSettings' does not contain a definition for 'SchemaProcessors' and no accessible extension method 'SchemaProcessors' accepting a first argument of type 'AspNetCoreOpenApiDocumentGeneratorSettings' could be found (are you missing a using directive or an assembly reference?)	Web	D:\Workspace\Vendor_Collaboration_Portal\Development\VCPAPI\src\Web\DependencyInjection.cs	50	Active

For this i added the Swashbuckle.AspNetCore.SwaggerUi from nuget packages, still same error.

Regards,
Sheik

**Comment by jasontaylordev** [comment]
Hi Sheik. If possible, could you try with the latest version of the template? 

https://www.nuget.org/packages/Clean.Architecture.Solution.Template/8.0.0-preview.7.2

**Comment by OsamaAbuSitta** [comment]
I have the same issue on the latest version 8.0.0-preview.7.2 , and I replace it with 
```
 configure.SchemaSettings.SchemaProcessors.Add(fluentValidationSchemaProcessor);
```

**Comment by sl-kevinmichaut** [comment]
need  :  configure.SchemaProcessors.Add(fluentValidationSchemaProcessor) 
and not  configure.SchemaSettings.SchemaProcessors.Add(fluentValidationSchemaProcessor);
